/*
  WP-112 / #461: unified static world presentation.
  Admin invariant: NPCs are the only normal independently dynamic world-image layer.
  Every non-NPC visual is flattened into one 100x100 RGBA logical-tile composite
  before it reaches the existing background texture upload path.
*/
(function installStaticTileCompositor(global) {
  'use strict';
  const Game = global.Game = global.Game || {};
  const VERSION = 'wp112-static-tile-compositor-v1';
  const COMPOSITE_TILE_PX = 100;
  const SOURCE_TILE_PX = 256;
  const MAX_CACHE_TILES = 512;
  const CARDINAL = Object.freeze([{name:'N',dr:-1,dc:0},{name:'E',dr:0,dc:1},{name:'S',dr:1,dc:0},{name:'W',dr:0,dc:-1}]);
  const BLOCKED_TERRAIN = new Set(['water','deep_water','wall','cliff','blocked']);
  const LEGACY_STATIC_LAYER_IDS = Object.freeze(['starterVillageRoadOverlay','starterVillageExteriorOverlay','worldObjectCompositionOverlay','starterVillageDevOverlay','vectorLayerDebugOverlay','starterVillageInteriorOverlay']);
  const BUILDING_FAMILIES = new Set(['home','inn','village_hall','bakery','market','smithy','workshop','guard_post','mill','farmstead','storage','well']);
  const BUILDING_ALIASES = Object.freeze({dwelling:'home',house:'home',tavern:'inn',lodging:'inn',hall:'village_hall',civic:'village_hall',shop:'market',food:'bakery',production:'workshop',guard:'guard_post',service:'guard_post',farm:'farmstead',agricultural:'farmstead',storehouse:'storage',barn:'storage'});
  const imageCache=new Map(),tileCache=new Map(),invalidatedTiles=new Set();
  let registryModulePromise=null,roadRegistry=null,mainRoadRegistry=null,buildingRegistry=null,objectRegistry=null,objectRegistryEntries=[],baseSnapshot=null,baseCanvasIdentity=null,lastStaticSignature='',renderHookInstalled=false,composing=false,composeQueued=false,uploadQueued=false,fullInvalidation=true;
  let lastStats=Object.freeze({version:VERSION,tilePixelSize:COMPOSITE_TILE_PX,staticTiles:0,overlays:0,roads:0,buildings:0,objects:0,cacheTiles:0,legacyLayersRemoved:0,reason:'not-composed'});
  const key=(r,c)=>`${r},${c}`; const parseKey=v=>String(v).split(',').map(Number);
  function makeCanvas(w,h){const c=document.createElement('canvas');c.width=Math.max(1,Math.trunc(w));c.height=Math.max(1,Math.trunc(h));return c;}
  function detachLegacyStaticLayers(){let removed=0;if(typeof document==='undefined')return removed;for(const id of LEGACY_STATIC_LAYER_IDS){const n=document.getElementById(id);if(n){n.remove();removed++;}}return removed;}
  function worldDimensions(){const w=Game.State?.world;return{rows:Math.max(1,Math.trunc(Number(w?.rows)||100)),cols:Math.max(1,Math.trunc(Number(w?.cols)||100))};}
  function backgroundCellRect(bg,r,c){const d=worldDimensions();return{x:c*bg.width/d.cols,y:r*bg.height/d.rows,width:bg.width/d.cols,height:bg.height/d.rows};}
  function validCell(r,c){const d=worldDimensions();return Number.isInteger(r)&&Number.isInteger(c)&&r>=0&&c>=0&&r<d.rows&&c<d.cols;}
  function captureBaseSnapshot(force=false){const bg=Game.State?.render?.worldBackgroundCanvas;if(!bg||!bg.width||!bg.height)return false;const changed=bg!==baseCanvasIdentity||!baseSnapshot||baseSnapshot.width!==bg.width||baseSnapshot.height!==bg.height;if(!force&&!changed)return false;const s=makeCanvas(bg.width,bg.height);s.getContext('2d').drawImage(bg,0,0);baseSnapshot=s;baseCanvasIdentity=bg;lastStaticSignature='';fullInvalidation=true;tileCache.clear();return true;}
  function registryModule(){if(!registryModulePromise)registryModulePromise=import(new URL('js/tile_registry.js',document.baseURI).href);return registryModulePromise;}
  async function ensureRegistries(){const m=await registryModule();if(!roadRegistry)roadRegistry=m.createCanonicalRoadTileRegistry();if(!mainRoadRegistry)mainRoadRegistry=m.createCanonicalMainRoadTileRegistry();if(!buildingRegistry)buildingRegistry=m.createCanonicalStarterBuildingTileRegistry();if(!objectRegistry)objectRegistry=new m.SemanticTileRegistry(objectRegistryEntries);return m;}
  async function configureObjectRegistry(entries){const m=await registryModule();objectRegistryEntries=Array.isArray(entries)?entries.map(e=>({...e})):[];objectRegistry=new m.SemanticTileRegistry(objectRegistryEntries);invalidateAll('object-registry-change');return objectRegistryEntries.length;}
  function imageCacheKey(e){return`${e.family}:${e.type}:${e.size}:${e.source}`;}
  async function loadEntryImage(registry,family,type,size=SOURCE_TILE_PX){const m=await ensureRegistries();const e=registry.resolve(family,type,size);const k=imageCacheKey(e),cached=imageCache.get(k);if(cached?.state==='ready')return cached.image;if(cached?.state==='error')throw cached.error;if(cached?.promise)return cached.promise;const rec={state:'loading',image:null,error:null,promise:null};rec.promise=new Promise((resolve,reject)=>{const image=new Image();image.decoding='async';image.onload=()=>{rec.state='ready';rec.image=image;resolve(image);};image.onerror=()=>{rec.state='error';rec.error=new Error(`Failed to load static tile asset ${e.source}.`);reject(rec.error);};image.src=m.resolveTileUrl(e,document.baseURI);});imageCache.set(k,rec);return rec.promise;}
  function authoritativeRoadTiles(){const roads=Game.State?.world?.originVillage?.roadTiles;if(!Array.isArray(roads))return[];const d=new Map();for(const p of roads){const r=Number(p?.row),c=Number(p?.col);if(validCell(r,c))d.set(key(r,c),{row:r,col:c});}return[...d.values()].sort((a,b)=>a.row-b.row||a.col-b.col);}
  function roadTopology(){const roads=authoritativeRoadTiles(),set=new Set(roads.map(p=>key(p.row,p.col)));return roads.map(p=>{const links=CARDINAL.filter(d=>set.has(key(p.row+d.dr,p.col+d.dc)));return{row:p.row,col:p.col,mask:links.map(d=>d.name).join(''),degree:links.length};});}
  function buildingFootprintSet(){const bs=Game.State?.world?.originVillage?.buildings,out=new Set();if(!Array.isArray(bs))return out;for(const b of bs){if(b?.passable===true)continue;const f=b?.footprint,r=Number(f?.row),c=Number(f?.col),h=Number(f?.height),w=Number(f?.width);if(![r,c,h,w].every(Number.isFinite))continue;const er=Number(b?.entrance?.row),ec=Number(b?.entrance?.col),ek=Number.isInteger(er)&&Number.isInteger(ec)?key(er,ec):null;for(let rr=r;rr<r+h;rr++)for(let cc=c;cc<c+w;cc++){const k=key(rr,cc);if(k!==ek)out.add(k);}}return out;}
  function invalidRoadTileSet(topology){const occupied=buildingFootprintSet(),world=Game.State?.world,invalid=new Set();for(const t of topology){const k=key(t.row,t.col),terrain=String(world?.terrain?.[t.row]?.[t.col]?.type||'').toLowerCase();if(occupied.has(k)||BLOCKED_TERRAIN.has(terrain))invalid.add(k);}return invalid;}
  function roadVisual(t){if(!t||t.degree<=0)return null;const l=new Set(String(t.mask||'').split(''));if(t.degree>=4)return{family:'road',type:'cross',quarterTurns:0};if(t.degree===3){const m=CARDINAL.find(d=>!l.has(d.name))?.name,q={N:0,E:1,S:2,W:3}[m];return q===undefined?null:{family:'road',type:'t_junction',quarterTurns:q};}if(t.degree===2){if(l.has('N')&&l.has('S'))return{family:'road',type:'straight_vertical',quarterTurns:0};if(l.has('E')&&l.has('W'))return{family:'road',type:'straight_horizontal',quarterTurns:0};if(l.has('N')&&l.has('E'))return{family:'road',type:'turn_ne',quarterTurns:0};if(l.has('E')&&l.has('S'))return{family:'road',type:'turn_es',quarterTurns:0};if(l.has('S')&&l.has('W'))return{family:'road',type:'turn_sw',quarterTurns:0};if(l.has('W')&&l.has('N'))return{family:'road',type:'turn_wn',quarterTurns:0};return null;}const d=CARDINAL.find(x=>l.has(x.name))?.name;if(d==='N')return{family:'road',type:'straight_vertical',quarterTurns:0,clip:[0,0,256,128]};if(d==='S')return{family:'road',type:'straight_vertical',quarterTurns:0,clip:[0,128,256,128]};if(d==='W')return{family:'road',type:'straight_horizontal',quarterTurns:0,clip:[0,0,128,256]};if(d==='E')return{family:'road',type:'straight_horizontal',quarterTurns:0,clip:[128,0,128,256]};return null;}
  function roadGrid(){const d=worldDimensions(),g=Array.from({length:d.rows},()=>Array.from({length:d.cols},()=>null));for(const p of authoritativeRoadTiles())g[p.row][p.col]={type:'road'};return g;}
  function mainRoadVisual(s){if(!s||!Array.isArray(s.memberships)||!s.memberships.length)return null;if(s.kind==='main-road-intersection'||s.orientation==='cross')return{family:'main_road',type:'main_intersection_cross',quarterTurns:0};const m=s.memberships[0];if(s.orientation==='vertical'){if(m.longitudinalRole==='start'||m.longitudinalRole==='end')return{family:'main_road',type:'main_transition_vertical',quarterTurns:0};return{family:'main_road',type:m.lane==='a'?'main_straight_vertical_left':'main_straight_vertical_right',quarterTurns:0};}if(s.orientation==='horizontal'){if(m.longitudinalRole==='start'||m.longitudinalRole==='end')return{family:'main_road',type:'main_transition_horizontal',quarterTurns:0};return{family:'main_road',type:m.lane==='a'?'main_straight_horizontal_top':'main_straight_horizontal_bottom',quarterTurns:0};}return null;}
  function canonicalBuildingFamily(b){const raw=String(b?.type||'').toLowerCase(),f=BUILDING_ALIASES[raw]||raw;return BUILDING_FAMILIES.has(f)?f:null;}
  function entranceCell(b){const f=b?.footprint,e=b?.entrance;if(!f||!e)return null;const r=Number(f.row),c=Number(f.col),h=Number(f.height),w=Number(f.width),er=Number(e.row),ec=Number(e.col);if(![r,c,h,w,er,ec].every(Number.isFinite))return null;if(er===r-1&&ec>=c&&ec<c+w)return{row:0,col:ec-c};if(er===r+h&&ec>=c&&ec<c+w)return{row:h-1,col:ec-c};if(ec===c-1&&er>=r&&er<r+h)return{row:er-r,col:0};if(ec===c+w&&er>=r&&er<r+h)return{row:er-r,col:w-1};return null;}
  function buildingSemanticType(b,lr,lc,h,w,door){const f=canonicalBuildingFamily(b);if(f==='well')return'family_feature';if(door&&door.row===lr&&door.col===lc)return'entrance';const fr=h>2?h-2:h-1,fc=Math.floor((w-1)/2);if(lr===fr&&lc===fc)return'family_feature';if(lr===0){if(w===1)return'roof_ridge';if(lc===0)return'roof_corner_nw';if(lc===w-1)return'roof_corner_ne';if(lc===Math.floor(w/2))return'roof_ridge';return'roof_edge_n';}if(lr===h-1){if(w===1)return'wall_center';if(lc===0)return'base_corner_sw';if(lc===w-1)return'base_corner_se';return lc%2?'wall_window':'wall_center';}if(lc===0)return'wall_edge_w';if(lc===w-1)return'wall_edge_e';return lc%2?'wall_window':'wall_center';}
  function buildingCells(){const bs=Game.State?.world?.originVillage?.buildings;if(!Array.isArray(bs))return[];const cells=[];for(const b of bs){const family=canonicalBuildingFamily(b),f=b?.footprint;if(!family||!f)continue;const r=Number(f.row),c=Number(f.col),h=Math.trunc(Number(f.height)),w=Math.trunc(Number(f.width));if(![r,c,h,w].every(Number.isFinite)||h<=0||w<=0)continue;const door=entranceCell(b);for(let lr=0;lr<h;lr++)for(let lc=0;lc<w;lc++){const rr=r+lr,cc=c+lc;if(validCell(rr,cc))cells.push({row:rr,col:cc,family,type:buildingSemanticType(b,lr,lc,h,w,door),buildingId:String(b?.id||`${family}:${r}:${c}`)});}}return cells;}
  function parseSemanticKey(v){const p=String(v||'').split(':').map(x=>x.trim()).filter(Boolean);if(p.length<2)return null;const size=p.length>=3?Number(p[2]):SOURCE_TILE_PX;return Number.isInteger(size)&&size>0?{family:p[0],type:p[1],size}:null;}
  function objectCells(){const ds=Game.State?.world?.objectPresentationDescriptors;if(!Array.isArray(ds)||!objectRegistry||!objectRegistryEntries.length)return[];const cells=[];for(const d of ds){if(!d||d.authority!=='simulation')continue;const s=parseSemanticKey(d.visual?.semanticKey||d.semanticType);if(!s||!objectRegistry.has(s.family,s.type,s.size))continue;const occupied=d.footprint?.occupiedCells;if(!Array.isArray(occupied)||occupied.length!==1)continue;const r=Number(occupied[0]?.row),c=Number(occupied[0]?.col);if(validCell(r,c))cells.push({row:r,col:c,family:s.family,type:s.type,size:s.size,objectId:d.objectId});}return cells;}
  function addOverlay(stacks,r,c,o){if(!validCell(r,c))return;const k=key(r,c),list=stacks.get(k)||[];list.push(o);stacks.set(k,list);}
  async function buildOverlayStacks(){await ensureRegistries();const stacks=new Map(),topology=roadTopology(),invalid=invalidRoadTileSet(topology);let classification=null;try{classification=Game.MainRoadSemantics?.classify?.(roadGrid())||null;}catch(_){}const main=new Map();for(const [k,s] of Object.entries(classification?.cells||{})){const v=mainRoadVisual(s);if(v)main.set(k,v);}for(const t of topology){const k=key(t.row,t.col);if(invalid.has(k))continue;const v=main.get(k)||roadVisual(t);if(v)addOverlay(stacks,t.row,t.col,{...v,category:10,source:'road'});}for(const c of buildingCells())addOverlay(stacks,c.row,c.col,{family:c.family,type:c.type,size:SOURCE_TILE_PX,category:20,source:`building:${c.buildingId}`});for(const c of objectCells())addOverlay(stacks,c.row,c.col,{family:c.family,type:c.type,size:c.size,category:30,source:`object:${c.objectId}`,customRegistry:true});for(const list of stacks.values())list.sort((a,b)=>a.category-b.category||String(a.family).localeCompare(String(b.family))||String(a.type).localeCompare(String(b.type))||String(a.source).localeCompare(String(b.source)));return stacks;}
  function staticSignature(){const w=Game.State?.world,v=w?.originVillage,roads=Array.isArray(v?.roadTiles)?v.roadTiles.map(p=>`${p.row},${p.col}`).sort().join('|'):'',buildings=Array.isArray(v?.buildings)?v.buildings.map(b=>{const f=b?.footprint||{},e=b?.entrance||{};return[b?.id,b?.type,f.row,f.col,f.height,f.width,e.row,e.col,b?.passable].join(':');}).sort().join('|'):'',objects=Array.isArray(w?.objectPresentationDescriptors)?w.objectPresentationDescriptors.map(d=>{const p=d?.position||{};return[d?.objectId,d?.semanticType,p.regionX,p.regionY,p.row,p.col,d?.visual?.semanticKey].join(':');}).sort().join('|'):'',bg=Game.State?.render?.worldBackgroundCanvas;return`${w?.seed||''}|${w?.regionX||0},${w?.regionY||0}|${bg?.width||0}x${bg?.height||0}|r:${roads}|b:${buildings}|o:${objects}|or:${objectRegistryEntries.length}`;}
  function cachePut(k,canvas,signature){if(tileCache.has(k))tileCache.delete(k);tileCache.set(k,{canvas,signature,usedAt:Date.now()});while(tileCache.size>MAX_CACHE_TILES)tileCache.delete(tileCache.keys().next().value);}
  function drawOverlayImage(ctx,image,o){ctx.save();if(o.clip){const[sx,sy,sw,sh]=o.clip;ctx.beginPath();ctx.rect(sx/SOURCE_TILE_PX*COMPOSITE_TILE_PX,sy/SOURCE_TILE_PX*COMPOSITE_TILE_PX,sw/SOURCE_TILE_PX*COMPOSITE_TILE_PX,sh/SOURCE_TILE_PX*COMPOSITE_TILE_PX);ctx.clip();}if(o.quarterTurns){ctx.translate(50,50);ctx.rotate(o.quarterTurns*Math.PI*.5);ctx.translate(-50,-50);}ctx.drawImage(image,0,0,100,100);ctx.restore();}
  async function composeCell(bg,r,c,overlays,signature){const k=key(r,c),rect=backgroundCellRect(bg,r,c),canvas=makeCanvas(100,100),ctx=canvas.getContext('2d');if(!ctx||!baseSnapshot)return{drawn:0,tileCanvas:null};ctx.drawImage(baseSnapshot,rect.x,rect.y,rect.width,rect.height,0,0,100,100);let drawn=0;for(const o of overlays){const registry=o.customRegistry?objectRegistry:o.family==='road'?roadRegistry:o.family==='main_road'?mainRoadRegistry:buildingRegistry;if(!registry)continue;try{const image=await loadEntryImage(registry,o.family,o.type,o.size||256);drawOverlayImage(ctx,image,o);drawn++;}catch(error){console.warn(`Static tile overlay unavailable at ${k}: ${o.family}:${o.type}`,error);}}cachePut(k,canvas,signature);return{drawn,tileCanvas:canvas};}
  function requestBackgroundUpload(){if(uploadQueued)return;uploadQueued=true;global.requestAnimationFrame(()=>{uploadQueued=false;const r=Game.State?.render;if(r){r.needsBackgroundUpload=true;r.backgroundTextureReady=false;}if(Game.Renderer?.renderWorld)Game.Renderer.renderWorld(false);});}
  async function composeNow(reason='manual'){if(composing){composeQueued=true;return false;}composing=true;try{detachLegacyStaticLayers();const render=Game.State?.render,bg=render?.worldBackgroundCanvas;if(!bg||!bg.width||!bg.height)return false;if(!baseSnapshot||bg!==baseCanvasIdentity||baseSnapshot.width!==bg.width||baseSnapshot.height!==bg.height)captureBaseSnapshot(true);if(!baseSnapshot)return false;const sig=staticSignature(),full=fullInvalidation||sig!==lastStaticSignature;if(!full&&invalidatedTiles.size===0)return true;const stacks=await buildOverlayStacks(),targets=full?new Set(stacks.keys()):new Set(invalidatedTiles),ctx=bg.getContext('2d');if(!ctx)return false;if(full){ctx.clearRect(0,0,bg.width,bg.height);ctx.drawImage(baseSnapshot,0,0);tileCache.clear();}else for(const k of targets){const[r,c]=parseKey(k);if(!validCell(r,c))continue;const rect=backgroundCellRect(bg,r,c);ctx.drawImage(baseSnapshot,rect.x,rect.y,rect.width,rect.height,rect.x,rect.y,rect.width,rect.height);tileCache.delete(k);}let overlays=0,roads=0,buildings=0,objects=0;const ordered=[...targets].sort((a,b)=>{const[ar,ac]=parseKey(a),[br,bc]=parseKey(b);return ar-br||ac-bc;});for(const k of ordered){const list=stacks.get(k)||[];if(!list.length)continue;const[r,c]=parseKey(k),result=await composeCell(bg,r,c,list,`${sig}|${k}`);if(!result.tileCanvas)continue;const rect=backgroundCellRect(bg,r,c);ctx.drawImage(result.tileCanvas,rect.x,rect.y,rect.width,rect.height);overlays+=result.drawn;roads+=list.filter(o=>o.source==='road').length;buildings+=list.filter(o=>String(o.source).startsWith('building:')).length;objects+=list.filter(o=>String(o.source).startsWith('object:')).length;}lastStaticSignature=sig;invalidatedTiles.clear();fullInvalidation=false;lastStats=Object.freeze({version:VERSION,tilePixelSize:100,staticTiles:ordered.length,overlays,roads,buildings,objects,cacheTiles:tileCache.size,legacyLayersRemoved:detachLegacyStaticLayers(),reason,backgroundWidth:bg.width,backgroundHeight:bg.height,npcDynamicException:true});requestBackgroundUpload();return true;}finally{composing=false;if(composeQueued){composeQueued=false;queueCompose('queued');}}}
  function queueCompose(reason='scheduled'){if(composeQueued)return;composeQueued=true;global.requestAnimationFrame(()=>{composeQueued=false;composeNow(reason).catch(e=>console.warn('Static tile composition failed.',e));});}
  function invalidateTile(r,c,reason='static-change'){if(!validCell(r,c))return false;invalidatedTiles.add(key(r,c));queueCompose(reason);return true;}
  function invalidateTiles(cells,reason='static-change'){if(!Array.isArray(cells))return 0;let n=0;for(const cell of cells)if(invalidateTile(Number(cell?.row),Number(cell?.col),reason))n++;return n;}
  function invalidateAll(reason='static-change'){fullInvalidation=true;lastStaticSignature='';queueCompose(reason);return true;}
  function installRenderHook(){if(renderHookInstalled||!Game.Renderer||typeof Game.Renderer.renderWorld!=='function')return false;const prior=Game.Renderer.renderWorld.bind(Game.Renderer);Game.Renderer.renderWorld=function(force){const render=Game.State?.render,dirty=Boolean(render?.needsBackgroundRebuild),before=render?.worldBackgroundCanvas||null,result=prior(force),after=Game.State?.render?.worldBackgroundCanvas||null;if(!baseSnapshot||after!==baseCanvasIdentity||before!==after||dirty){captureBaseSnapshot(true);fullInvalidation=true;}queueCompose(dirty?'base-background-rebuild':'render');return result;};renderHookInstalled=true;return true;}
  function initialize(attempt=0){detachLegacyStaticLayers();if(!(Game.State&&Game.Renderer?.renderWorld)){if(attempt<160)global.setTimeout(()=>initialize(attempt+1),50);return false;}installRenderHook();captureBaseSnapshot(false);queueCompose('initialize');return true;}
  Game.StaticTileCompositor=Object.freeze({version:VERSION,authority:'presentation-only',tilePixelSize:100,sourceTilePixelSize:256,layerPolicy:'static-background-plus-dynamic-npc-only',npcDynamicException:true,configureObjectRegistry,composeNow,invalidateTile,invalidateTiles,invalidateAll,detachLegacyStaticLayers,diagnostics(){return{...lastStats,invalidatedTiles:invalidatedTiles.size,fullInvalidation,objectRegistryEntries:objectRegistryEntries.length};},initialize});
  if(typeof document!=='undefined'&&document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>initialize(),{once:true});else initialize();
})(typeof window!=='undefined'?window:globalThis);
