(function(){
"use strict";

const VERSION="advisor-command-v1";
const SCHEMA="AdvisorCommandLedger";
const SCHEMA_VERSION=1;
const REGISTRY_KIND="advisor-command-ledger";
const REGISTRY_KEY="command-analyses";
const MAX_SOURCES=10;
const MAX_FACTS=64;
const MAX_ANALYSES=24;
const MAX_LEDGER_BYTES=48*1024;
const MAX_QUERY_RESULTS=12;
const MAX_BLOCKERS=12;
const MAX_RISKS=12;
const MAX_UNKNOWNS=12;
const MAX_DETAILS=12;
const MAX_AUTHORITY_SCOPES=16;
const SOURCE_SYSTEMS=Object.freeze(["ProtagonistAuthority","ProtagonistHealth","ProtagonistInventory","RoutePlanner","WorldRoadGraph","WorldState"]);
const SOURCE_FIELDS=Object.freeze({
  ProtagonistAuthority:Object.freeze(["scopes","rankTier"]),
  ProtagonistHealth:Object.freeze(["conditionMilli","fatigueMilli","activeInjuryCount"]),
  ProtagonistInventory:Object.freeze(["equipmentCoverage","supplyCoverage","missingRequirementCount"]),
  RoutePlanner:Object.freeze(["routeFound","routeRisk","routeSeconds","stepCount","maxSlopeAngleDegrees"]),
  WorldRoadGraph:Object.freeze(["routeFound","routeRisk","routeSeconds","stepCount"]),
  WorldState:Object.freeze(["capability","cohesion","equipmentCoverage","supplyCoverage","availableActors","groupSize","condition","threat"])
});
const FIELD_SPECS=Object.freeze({
  rankTier:Object.freeze({kind:"count",polarity:"positive"}),
  conditionMilli:Object.freeze({kind:"scaled",max:100000,polarity:"positive"}),
  fatigueMilli:Object.freeze({kind:"scaled",max:100000,polarity:"negative"}),
  activeInjuryCount:Object.freeze({kind:"count",polarity:"negative"}),
  equipmentCoverage:Object.freeze({kind:"ratio",polarity:"positive"}),
  supplyCoverage:Object.freeze({kind:"ratio",polarity:"positive"}),
  missingRequirementCount:Object.freeze({kind:"count",polarity:"negative"}),
  routeFound:Object.freeze({kind:"boolean",polarity:"positive"}),
  routeRisk:Object.freeze({kind:"ratio",polarity:"negative"}),
  routeSeconds:Object.freeze({kind:"count",polarity:"negative"}),
  stepCount:Object.freeze({kind:"count",polarity:"negative"}),
  maxSlopeAngleDegrees:Object.freeze({kind:"number",min:0,max:90,polarity:"negative"}),
  capability:Object.freeze({kind:"ratio",polarity:"positive"}),
  cohesion:Object.freeze({kind:"ratio",polarity:"positive"}),
  availableActors:Object.freeze({kind:"count",polarity:"positive"}),
  groupSize:Object.freeze({kind:"count",polarity:"positive"}),
  condition:Object.freeze({kind:"ratio",polarity:"positive"}),
  threat:Object.freeze({kind:"ratio",polarity:"negative"})
});

function root(){return typeof window!=="undefined"?window:globalThis}
function clone(v){if(v==null||typeof v!=="object")return v;if(Array.isArray(v))return v.map(clone);const o={};for(const[k,x]of Object.entries(v))o[k]=clone(x);return o}
function freeze(v){if(v==null||typeof v!=="object"||Object.isFrozen(v))return v;for(const x of Object.values(v))freeze(x);return Object.freeze(v)}
function stable(v){if(v==null||typeof v!=="object")return JSON.stringify(v);if(Array.isArray(v))return "["+v.map(stable).join(",")+"]";return "{"+Object.keys(v).sort().map(k=>JSON.stringify(k)+":"+stable(v[k])).join(",")+"}"}
function hashText(v){let h=2166136261>>>0;for(const c of String(v==null?"":v)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)>>>0}h^=h>>>16;h=Math.imul(h,2246822507);h^=h>>>13;return(h>>>0).toString(16).toUpperCase().padStart(8,"0")}
function utf8Bytes(v){const s=String(v==null?"":v);if(typeof TextEncoder!=="undefined")return new TextEncoder().encode(s).length;let n=0;for(let i=0;i<s.length;i++){const c=s.charCodeAt(i);n+=c<0x80?1:c<0x800?2:(c>=0xD800&&c<=0xDBFF&&i+1<s.length&&s.charCodeAt(i+1)>=0xDC00&&s.charCodeAt(i+1)<=0xDFFF?(i++,4):3)}return n}
function plain(v){return Boolean(v)&&typeof v==="object"&&!Array.isArray(v)}
function cleanText(v,max=160){return String(v==null?"":v).trim().replace(/\s+/g," ").slice(0,max)}
function cleanId(v,max=160){return cleanText(v,max).replace(/[^A-Za-z0-9:_|.@/\-]/g,"-")}
function seed(v){const s=cleanText(v,160);if(!s)throw new Error("Campaign SEED is required.");return s}
function validTimestamp(v){return /^\d{4,}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(String(v||""))}
function timestamp(v){const s=cleanText(v,32);if(!validTimestamp(s))throw new Error("Fantasy timestamp must be YYYY-MM-DD HH:MM:SS.");return s}
function round4(v){return Number(Number(v).toFixed(4))}
function registryContext(seedValue){const s=seed(seedValue),profileId="ADVISOR-"+hashText(s+"|advisor-profile-v1"),world=root().WorldState,ref=world?.structuralRef?.(s,REGISTRY_KIND,profileId,REGISTRY_KEY,{role:"advisor-command-history",advisorProfileId:profileId,authority:"AdvisorCommand compact analysis references"})||null;return freeze({seed:s,advisorProfileId:profileId,ref})}
function emptyLedger(ctx){return {schema:SCHEMA,schemaVersion:SCHEMA_VERSION,version:VERSION,seed:ctx.seed,advisorProfileId:ctx.advisorProfileId,registryId:ctx.ref?.id||null,revision:0,lastFantasyTimestamp:null,analyses:[],bounds:{maxAnalyses:MAX_ANALYSES,maxBytes:MAX_LEDGER_BYTES,maxQueryResults:MAX_QUERY_RESULTS}}}
function compactValid(row,s){return plain(row)&&/^CMD-[0-9A-F]{8}$/.test(String(row.id||""))&&row.seed===s&&row.operationId&&validTimestamp(row.fantasyTimestamp)&&Array.isArray(row.sourceRefIds)&&row.sourceRefIds.length<=MAX_SOURCES&&Array.isArray(row.blockers)&&row.blockers.length<=MAX_BLOCKERS&&Array.isArray(row.unknowns)&&row.unknowns.length<=MAX_UNKNOWNS&&Number.isInteger(row.commandLevel)&&row.commandLevel>=1&&row.commandLevel<=20&&(row.readinessScore==null||(Number.isFinite(row.readinessScore)&&row.readinessScore>=0&&row.readinessScore<=1))}
function compatible(raw,ctx){if(!plain(raw)||raw.schema!==SCHEMA||Number(raw.schemaVersion)!==SCHEMA_VERSION||raw.version!==VERSION||raw.seed!==ctx.seed||raw.advisorProfileId!==ctx.advisorProfileId||raw.registryId!==(ctx.ref?.id||null)||!Array.isArray(raw.analyses)||raw.analyses.length>MAX_ANALYSES)return false;const ids=new Set();let latest=null;for(const row of raw.analyses){if(!compactValid(row,ctx.seed)||ids.has(row.id))return false;ids.add(row.id);if(latest===null||row.fantasyTimestamp>latest)latest=row.fantasyTimestamp}return raw.lastFantasyTimestamp===latest&&utf8Bytes(stable(raw))<=MAX_LEDGER_BYTES}
function readLedger(seedValue){const ctx=registryContext(seedValue),resolved=ctx.ref&&root().WorldState?.resolve?.(ctx.seed,ctx.ref)||null,raw=resolved?.current?.advisorCommand;if(raw==null)return{ctx,resolved,compatible:true,ledger:emptyLedger(ctx),reason:"empty"};if(!compatible(raw,ctx))return{ctx,resolved,compatible:false,ledger:null,reason:"ledger-incompatible"};return{ctx,resolved,compatible:true,ledger:clone(raw),reason:"ok"}}
function writeLedger(seedValue,ledgerValue,reasonValue){const read=readLedger(seedValue),ctx=read.ctx,world=root().WorldState;if(!read.compatible)return freeze({ok:false,reason:read.reason});if(!ctx.ref||!world?.applyDelta)return freeze({ok:false,reason:"world-state-unavailable"});const next=clone(ledgerValue);next.schema=SCHEMA;next.schemaVersion=SCHEMA_VERSION;next.version=VERSION;next.seed=ctx.seed;next.advisorProfileId=ctx.advisorProfileId;next.registryId=ctx.ref.id;next.revision=Math.max(0,Number(next.revision)||0)+1;if(!compatible(next,ctx))return freeze({ok:false,reason:"ledger-invalid-or-over-budget"});const result=world.applyDelta(ctx.seed,ctx.ref,{advisorCommand:next},String(reasonValue||"advisor-command"));return freeze({ok:Boolean(result?.ok),reason:result?.reason||"ok",ledgerRevision:next.revision,deltaRevision:Number(result?.entry?.revision||0),analysisCount:next.analyses.length,serializedBytes:utf8Bytes(stable(next))})}
function normalizeOperation(v){if(!plain(v)||v.validated!==true)throw new Error("Validated operation context is required.");const id=cleanId(v.id||v.operationId,160),refId=cleanId(v.refId||id,160),objectiveId=cleanId(v.objectiveId,160),targetRefId=cleanId(v.targetRefId,160),requiredAuthorityScope=cleanId(v.requiredAuthorityScope||"",120)||null;if(!id||!refId||!objectiveId||!targetRefId)throw new Error("Operation id, objectiveId and targetRefId are required.");const req=plain(v.requirements)?v.requirements:{};const requirements={routeRequired:req.routeRequired===true,minCapability:req.minCapability==null?null:ratio(req.minCapability,"minCapability"),minSupplyCoverage:req.minSupplyCoverage==null?null:ratio(req.minSupplyCoverage,"minSupplyCoverage"),minEquipmentCoverage:req.minEquipmentCoverage==null?null:ratio(req.minEquipmentCoverage,"minEquipmentCoverage"),minCondition:req.minCondition==null?null:ratio(req.minCondition,"minCondition"),minAvailableActors:req.minAvailableActors==null?null:count(req.minAvailableActors,"minAvailableActors")};return freeze({id,refId,objectiveId,targetRefId,requiredAuthorityScope,requirements:freeze(requirements),validated:true})}
function ratio(v,name){const n=Number(v);if(!Number.isFinite(n)||n<0||n>1)throw new Error(name+" must be within 0..1.");return round4(n)}
function count(v,name){const n=Number(v);if(!Number.isInteger(n)||n<0||n>1000000000)throw new Error(name+" must be a bounded non-negative integer.");return n}
function normalizeValue(field,v){const spec=FIELD_SPECS[field];if(!spec)throw new Error("Unsupported Command fact: "+field);if(spec.kind==="boolean"){if(v!==true&&v!==false)throw new Error(field+" must be boolean.");return v}if(spec.kind==="ratio")return ratio(v,field);if(spec.kind==="count")return count(v,field);const n=Number(v);if(!Number.isFinite(n))throw new Error(field+" must be numeric.");if(spec.kind==="scaled"){if(!Number.isInteger(n)||n<0||n>spec.max)throw new Error(field+" is out of range.");return n}if(n<spec.min||n>spec.max)throw new Error(field+" is out of range.");return round4(n)}
function normalizeSources(value,when){const rows=Array.isArray(value)?value:[];if(rows.length>MAX_SOURCES)throw new Error("Command source limit exceeded.");const refs=new Set(),facts=[],sources=[];for(const row of rows){if(!plain(row)||row.validated!==true)throw new Error("Command sources must be validated.");const sourceSystem=cleanText(row.sourceSystem,80),refId=cleanId(row.refId,160);if(!SOURCE_SYSTEMS.includes(sourceSystem)||!refId)throw new Error("Invalid Command source reference.");if(refs.has(refId))throw new Error("Duplicate Command source reference.");refs.add(refId);const sourceTimestamp=timestamp(row.fantasyTimestamp);if(sourceTimestamp>when)throw new Error("Command source cannot be from the future.");const values=plain(row.values)?row.values:{};const keys=Object.keys(values);if(keys.length>24)throw new Error("Command source field limit exceeded.");for(const field of keys){if(field==="scopes"){if(sourceSystem!=="ProtagonistAuthority"||!Array.isArray(values.scopes)||values.scopes.length>MAX_AUTHORITY_SCOPES)throw new Error("Invalid authority scopes.");const scopes=[];for(const raw of values.scopes){const scope=cleanId(raw,120);if(scope&&!scopes.includes(scope))scopes.push(scope)}facts.push(freeze({field:"scopes",value:freeze(scopes),sourceSystem,refId,fantasyTimestamp:sourceTimestamp}));continue}if(!FIELD_SPECS[field]||!SOURCE_FIELDS[sourceSystem].includes(field))throw new Error("Unsupported Command field for "+sourceSystem+": "+field);facts.push(freeze({field,value:normalizeValue(field,values[field]),sourceSystem,refId,fantasyTimestamp:sourceTimestamp}));if(facts.length>MAX_FACTS)throw new Error("Command fact limit exceeded.");}sources.push(freeze({sourceSystem,refId,fantasyTimestamp:sourceTimestamp,fieldCount:keys.length}));}return freeze({sources:freeze(sources),facts:freeze(facts)})}
function latestFacts(facts){const out={};for(const fact of facts){const prior=out[fact.field];if(!prior||fact.fantasyTimestamp>prior.fantasyTimestamp||(fact.fantasyTimestamp===prior.fantasyTimestamp&&fact.refId<prior.refId))out[fact.field]=fact}return freeze(out)}
function skillContext(seedValue){let level=1,totalXp=0;try{const row=root().AdvisorProgression?.getSkill?.(seedValue,"command");if(row){level=Math.max(1,Math.min(20,Math.floor(Number(row.level)||1)));totalXp=Math.max(0,Math.floor(Number(row.totalXp)||0))}}catch(_){}return freeze({level,totalXp,detailLimit:Math.min(MAX_DETAILS,4+Math.floor((level-1)/2)),precision:level>=15?4:level>=8?3:2})}
function normalizedScalar(field,fact){if(!fact)return null;const spec=FIELD_SPECS[field];if(spec.kind==="ratio")return fact.value;if(field==="conditionMilli")return fact.value/100000;if(field==="fatigueMilli")return 1-fact.value/100000;if(field==="activeInjuryCount")return Math.max(0,1-Math.min(1,fact.value/6));if(field==="missingRequirementCount")return fact.value===0?1:Math.max(0,1-Math.min(1,fact.value/4));if(field==="routeFound")return fact.value?1:0;if(field==="routeRisk")return 1-fact.value;if(field==="threat")return 1-fact.value;if(field==="cohesion"||field==="capability"||field==="equipmentCoverage"||field==="supplyCoverage"||field==="condition")return fact.value;if(field==="availableActors"||field==="groupSize")return null;return null}
function blocker(id,reason,refs){return freeze({id,reason,sourceRefIds:freeze([...new Set((refs||[]).filter(Boolean))].sort())})}
function risk(id,strength,refs){return freeze({id,strength:round4(Math.max(0,Math.min(1,Number(strength)||0))),sourceRefIds:freeze([...new Set((refs||[]).filter(Boolean))].sort())})}
function assess(operation,facts){const blockers=[],risks=[],unknowns=[],req=operation.requirements,opRef=operation.refId;
  const scopes=facts.scopes?.value||[];
  if(operation.requiredAuthorityScope&&!scopes.includes(operation.requiredAuthorityScope))blockers.push(blocker("authority-scope-missing","required legitimate authority scope is missing",[opRef,facts.scopes?.refId]));
  if(req.routeRequired===true){if(!facts.routeFound)unknowns.push("missing:routeFound");else if(facts.routeFound.value!==true)blockers.push(blocker("route-unavailable","required route is not available",[opRef,facts.routeFound.refId]))}
  const checks=[
    ["capability",req.minCapability,"capability-below-required"],
    ["supplyCoverage",req.minSupplyCoverage,"supplies-below-required"],
    ["equipmentCoverage",req.minEquipmentCoverage,"equipment-below-required"],
    ["availableActors",req.minAvailableActors,"actors-below-required"]
  ];
  for(const [field,min,id] of checks){if(min==null)continue;const f=facts[field];if(!f)unknowns.push("missing:"+field);else if(Number(f.value)<Number(min))blockers.push(blocker(id,field+" is below explicit operation requirement",[opRef,f.refId]))}
  if(req.minCondition!=null){const c=facts.condition?facts.condition.value:(facts.conditionMilli?facts.conditionMilli.value/100000:null);if(c==null)unknowns.push("missing:condition");else if(c<req.minCondition)blockers.push(blocker("condition-below-required","actor/group condition is below explicit operation requirement",[opRef,facts.condition?.refId||facts.conditionMilli?.refId]))}
  for(const u of unknowns){if(u.startsWith("missing:")&&["routeFound","capability","supplyCoverage","equipmentCoverage","availableActors","condition"].includes(u.slice(8)))blockers.push(blocker("critical-"+u,u+" prevents readiness confirmation",[opRef]))}
  if(facts.fatigueMilli&&facts.fatigueMilli.value>60000)risks.push(risk("high-fatigue",facts.fatigueMilli.value/100000,[facts.fatigueMilli.refId]));
  if(facts.activeInjuryCount&&facts.activeInjuryCount.value>0)risks.push(risk("active-injuries",Math.min(1,facts.activeInjuryCount.value/4),[facts.activeInjuryCount.refId]));
  if(facts.routeRisk&&facts.routeRisk.value>.45)risks.push(risk("route-risk",facts.routeRisk.value,[facts.routeRisk.refId]));
  if(facts.threat&&facts.threat.value>.5)risks.push(risk("threat-pressure",facts.threat.value,[facts.threat.refId]));
  if(facts.cohesion&&facts.cohesion.value<.55)risks.push(risk("low-cohesion",1-facts.cohesion.value,[facts.cohesion.refId]));
  if(facts.supplyCoverage&&facts.supplyCoverage.value<.65)risks.push(risk("limited-supplies",1-facts.supplyCoverage.value,[facts.supplyCoverage.refId]));
  const metrics=[];for(const field of ["capability","cohesion","equipmentCoverage","supplyCoverage","condition","conditionMilli","fatigueMilli","activeInjuryCount","missingRequirementCount","routeFound","routeRisk","threat"]){const f=facts[field],n=normalizedScalar(field,f);if(n!=null)metrics.push(freeze({field,value:round4(n),sourceRefId:f.refId}))}
  const readinessScore=metrics.length?round4(metrics.reduce((s,x)=>s+x.value,0)/metrics.length):null;
  const status=blockers.length?"blocked":readinessScore==null?"unknown":readinessScore>=.72?"ready":readinessScore>=.52?"caution":"not-ready";
  blockers.sort((a,b)=>a.id.localeCompare(b.id));risks.sort((a,b)=>b.strength-a.strength||a.id.localeCompare(b.id));
  return freeze({status,readinessScore,blockers:freeze(blockers.slice(0,MAX_BLOCKERS)),risks:freeze(risks.slice(0,MAX_RISKS)),unknowns:freeze([...new Set(unknowns)].slice(0,MAX_UNKNOWNS)),metrics:freeze(metrics)})}
function detailsFor(facts,skill){const rows=[];for(const field of Object.keys(facts).sort()){if(field==="scopes")continue;const f=facts[field];let value=f.value;if(typeof value==="number"&&!Number.isInteger(value))value=Number(value.toFixed(skill.precision));rows.push(freeze({field,value,sourceRefId:f.refId,fantasyTimestamp:f.fantasyTimestamp}))}return freeze(rows.slice(0,skill.detailLimit))}
function progressionEvidence(row){return freeze({campaignSeed:row.seed,kind:"advisor-tool-result",authority:"AdvisorToolResolution",validated:true,rewardBand:row.status==="blocked"||row.status==="unknown"?"practice":"success",fantasyTimestamp:row.fantasyTimestamp,toolId:"advisor.command",outcomeId:row.id,sourceSystem:"AdvisorCommand"})}
function analyze(seedValue,inputValue){const s=seed(seedValue),input=plain(inputValue)?inputValue:{},read=readLedger(s);if(!read.compatible)return freeze({ok:false,reason:read.reason,result:null});let operation,when,norm;try{operation=normalizeOperation(input.operation);when=timestamp(input.fantasyTimestamp);norm=normalizeSources(input.sources,when)}catch(error){return freeze({ok:false,reason:String(error.message||error),result:null})}const facts=latestFacts(norm.facts),skill=skillContext(s),assessment=assess(operation,facts),details=detailsFor(facts,skill),sourceRefIds=freeze(norm.sources.map(x=>x.refId).sort()),basis={seed:s,operation,when,sourceRefIds,facts:norm.facts.map(x=>({field:x.field,value:x.value,refId:x.refId,fantasyTimestamp:x.fantasyTimestamp})).sort((a,b)=>a.field.localeCompare(b.field)||a.refId.localeCompare(b.refId)),commandLevel:skill.level},id="CMD-"+hashText(stable(basis));const compact=freeze({id,seed:s,operationId:operation.id,fantasyTimestamp:when,sourceRefIds,status:assessment.status,readinessScore:assessment.readinessScore,blockers:freeze(assessment.blockers.map(x=>x.id)),riskCount:assessment.risks.length,unknowns:assessment.unknowns,commandLevel:skill.level,detailLimit:skill.detailLimit});const full=()=>freeze({...clone(compact),operation,sourceCount:norm.sources.length,factCount:norm.facts.length,assessment,details,skill,advisoryOnly:true,executionAuthority:false,orderAuthority:false,combatAuthority:false,routeAuthority:false,resourceAuthority:false,authorityGrant:false,directWorldMutation:false,directPositionMutation:false,protagonistDecisionAuthority:false,simulationValidationBypass:false,providerPayloadUsed:false,presentationStateUsed:false});const existing=read.ledger.analyses.find(x=>x.id===id);if(existing)return freeze({ok:true,reason:"duplicate",duplicate:true,result:full(),progressionEvidence:progressionEvidence(existing)});if(read.ledger.analyses.length>=MAX_ANALYSES)return freeze({ok:false,reason:"command-analysis-limit-reached",result:null});if(read.ledger.lastFantasyTimestamp&&when<read.ledger.lastFantasyTimestamp)return freeze({ok:false,reason:"cannot-rewind-command-chronology",result:null});const next=clone(read.ledger);next.analyses.push(clone(compact));next.lastFantasyTimestamp=when;const write=writeLedger(s,next,"advisor-command:"+id);if(!write.ok)return freeze({...write,result:null});return freeze({...write,duplicate:false,result:full(),progressionEvidence:progressionEvidence(compact)})}
function listAnalyses(seedValue,optionsValue){const read=readLedger(seedValue),o=plain(optionsValue)?optionsValue:{};if(!read.compatible)return freeze([]);const operationId=cleanId(o.operationId||"",160)||null,limit=Math.max(0,Math.min(MAX_QUERY_RESULTS,Math.floor(Number(o.limit)||MAX_QUERY_RESULTS)));return freeze(read.ledger.analyses.filter(x=>!operationId||x.operationId===operationId).slice().sort((a,b)=>String(b.fantasyTimestamp).localeCompare(String(a.fantasyTimestamp))||String(a.id).localeCompare(String(b.id))).slice(0,limit).map(x=>freeze(clone(x))))}
function snapshot(seedValue){const s=seed(seedValue),read=readLedger(s);if(!read.compatible)return freeze({version:VERSION,schema:SCHEMA,schemaVersion:SCHEMA_VERSION,seed:s,compatible:false,reason:read.reason,analyses:freeze([]),bounded:true});return freeze({version:VERSION,schema:SCHEMA,schemaVersion:SCHEMA_VERSION,seed:s,advisorProfileId:read.ctx.advisorProfileId,registryId:read.ctx.ref?.id||null,compatible:true,reason:read.reason,ledgerRevision:Number(read.ledger.revision||0),deltaRevision:Number(read.resolved?.delta?.revision||0),lastFantasyTimestamp:read.ledger.lastFantasyTimestamp,analysisCount:read.ledger.analyses.length,serializedBytes:utf8Bytes(stable(read.ledger)),analyses:freeze(read.ledger.analyses.map(x=>freeze(clone(x)))),maxSources:MAX_SOURCES,maxFacts:MAX_FACTS,maxAnalyses:MAX_ANALYSES,maxLedgerBytes:MAX_LEDGER_BYTES,maxQueryResults:MAX_QUERY_RESULTS,maxBlockers:MAX_BLOCKERS,maxRisks:MAX_RISKS,maxUnknowns:MAX_UNKNOWNS,maxDetails:MAX_DETAILS,maxAuthorityScopes:MAX_AUTHORITY_SCOPES,bounded:true,persistenceAuthority:"WorldState CampaignStateDelta",chronologyAuthority:"Fantasy Game Time",sourceAuthority:"validated bounded authority/health/inventory/route/world summaries only",fullWorldScan:false,wholeArmyScan:false,wholeHistoryScan:false,perFrameScan:false,directWorldMutation:false,directPositionMutation:false,unitMutation:false,combatMutation:false,resourceMutation:false,inventoryMutation:false,routeMutation:false,authorityMutation:false,orderExecution:false,protagonistDecisionAuthority:false,worldTruthAuthority:false,simulationValidationBypass:false,providerPayloadPersisted:false})}
const api=Object.freeze({VERSION,SCHEMA,SCHEMA_VERSION,MAX_SOURCES,MAX_FACTS,MAX_ANALYSES,MAX_LEDGER_BYTES,MAX_QUERY_RESULTS,MAX_BLOCKERS,MAX_RISKS,MAX_UNKNOWNS,MAX_DETAILS,MAX_AUTHORITY_SCOPES,SOURCE_SYSTEMS,SOURCE_FIELDS,FIELD_SPECS,analyze,listAnalyses,snapshot});
root().AdvisorCommand=api;
if(typeof module!=="undefined"&&module.exports)module.exports=api;
})();