(function(){
"use strict";
const VERSION="local-market-v1",SCHEMA="LocalMarketSnapshot",SCHEMA_VERSION=1;
const MAX_PROVIDERS=8,MAX_OFFERS=16,MAX_QUERY_RESULTS=16,STALE_HOURS=72,MAX_PRICE_COPPER=100000;
const OFFER_DEFS=Object.freeze([
  Object.freeze({id:"travel-ration",provider:"general-shop",kind:"item",category:"food",label:"Travel ration",itemRef:Object.freeze({kind:"commodity",id:"TRAVEL-RATION"}),basePrice:4,baseStock:10,driver:"food",core:true}),
  Object.freeze({id:"rope-coil",provider:"general-shop",kind:"item",category:"basic-good",label:"Rope coil",itemRef:Object.freeze({kind:"gear",id:"ROPE-COIL"}),basePrice:8,baseStock:5,driver:"production",core:true}),
  Object.freeze({id:"lamp-oil",provider:"general-shop",kind:"item",category:"basic-good",label:"Lamp oil",itemRef:Object.freeze({kind:"commodity",id:"LAMP-OIL"}),basePrice:3,baseStock:8,driver:"trade",core:false}),
  Object.freeze({id:"bread-loaf",provider:"market-stalls",kind:"item",category:"food",label:"Bread loaf",itemRef:Object.freeze({kind:"commodity",id:"BREAD-LOAF"}),basePrice:2,baseStock:16,driver:"food",core:true}),
  Object.freeze({id:"cloth-wrap",provider:"market-stalls",kind:"item",category:"basic-good",label:"Cloth wrap",itemRef:Object.freeze({kind:"commodity",id:"CLOTH-WRAP"}),basePrice:5,baseStock:9,driver:"trade",core:true}),
  Object.freeze({id:"lodging-night",provider:"inn-tavern",kind:"service",category:"service",label:"One night lodging",serviceRef:Object.freeze({kind:"service",id:"LODGING-NIGHT"}),basePrice:6,baseStock:5,driver:"service",core:true}),
  Object.freeze({id:"hot-meal",provider:"inn-tavern",kind:"service",category:"food",label:"Hot meal",serviceRef:Object.freeze({kind:"service",id:"HOT-MEAL"}),basePrice:3,baseStock:12,driver:"food",core:true}),
  Object.freeze({id:"iron-tool",provider:"smithy",kind:"item",category:"basic-good",label:"Iron hand tool",itemRef:Object.freeze({kind:"gear",id:"IRON-HAND-TOOL"}),basePrice:20,baseStock:3,driver:"production",core:true}),
  Object.freeze({id:"basic-repair",provider:"smithy",kind:"service",category:"service",label:"Basic equipment repair",serviceRef:Object.freeze({kind:"service",id:"BASIC-REPAIR"}),basePrice:7,baseStock:5,driver:"service",core:true}),
  Object.freeze({id:"stable-care",provider:"stable-road-service",kind:"service",category:"service",label:"Stable care",serviceRef:Object.freeze({kind:"service",id:"STABLE-CARE"}),basePrice:5,baseStock:8,driver:"service",core:true}),
  Object.freeze({id:"fish-bundle",provider:"fish-market",kind:"item",category:"food",label:"Fresh fish bundle",itemRef:Object.freeze({kind:"commodity",id:"FISH-BUNDLE"}),basePrice:3,baseStock:14,driver:"food",core:true}),
  Object.freeze({id:"grain-sack",provider:"granary",kind:"item",category:"food",label:"Grain sack",itemRef:Object.freeze({kind:"commodity",id:"GRAIN-SACK"}),basePrice:6,baseStock:18,driver:"food",core:true}),
  Object.freeze({id:"wooden-utensils",provider:"craft-workshop",kind:"item",category:"basic-good",label:"Wooden utensils",itemRef:Object.freeze({kind:"commodity",id:"WOODEN-UTENSILS"}),basePrice:4,baseStock:8,driver:"production",core:true})
]);
function R(){return typeof window!=="undefined"?window:globalThis}
function C(v){if(v==null||typeof v!=="object")return v;if(Array.isArray(v))return v.map(C);return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,C(x)]))}
function F(v){if(v==null||typeof v!=="object"||Object.isFrozen(v))return v;Object.values(v).forEach(F);return Object.freeze(v)}
function S(v){if(v==null||typeof v!=="object")return JSON.stringify(v);if(Array.isArray(v))return "["+v.map(S).join(",")+"]";return "{"+Object.keys(v).sort().map(k=>JSON.stringify(k)+":"+S(v[k])).join(",")+"}"}
function H(v){let h=2166136261>>>0;for(const ch of String(v??"")){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)>>>0}return(h>>>0).toString(16).toUpperCase().padStart(8,"0")}
function txt(v,n=160){return String(v??"").trim().replace(/\\s+/g," ").slice(0,n)}
function id(v,n=160){return txt(v,n).replace(/[^A-Za-z0-9:_|.@/-]/g,"-")}
function clamp(v,a=0,b=1){const n=Number(v);return Number.isFinite(n)?Math.max(a,Math.min(b,n)):a}
function round(v,d=4){const f=10**d;return Math.round(Number(v)*f)/f}
function seed(v){const s=txt(v);if(!s)throw new Error("Campaign SEED is required.");return s}
function ts(v){const x=txt(v,32);if(!/^\\d{4,}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}$/.test(x))throw new Error("Fantasy timestamp must be YYYY-MM-DD HH:MM:SS.");return x}
function leap(y){return y%4===0&&(y%100!==0||y%400===0)}
function seconds(v){const m=ts(v).match(/^(\\d+)-(\\d{2})-(\\d{2}) (\\d{2}):(\\d{2}):(\\d{2})$/),y=Number(m[1]),mo=Number(m[2]),d=Number(m[3]),hh=Number(m[4]),mm=Number(m[5]),ss=Number(m[6]);if(mo<1||mo>12||d<1||d>31||hh>23||mm>59||ss>59)throw new Error("Fantasy timestamp fields are invalid.");const prior=y-1,monthDays=[31,28+(leap(y)?1:0),31,30,31,30,31,31,30,31,30,31];let days=365*prior+Math.floor(prior/4)-Math.floor(prior/100)+Math.floor(prior/400);for(let i=0;i<mo-1;i++)days+=monthDays[i];days+=d-1;return days*86400+hh*3600+mm*60+ss}
function foundationUnit(s,key){return parseInt(H(s+"|"+key),16)/4294967296}
function validPlan(p){return!!(p&&id(p.id)===p.id&&p.classId&&Number.isFinite(Number(p.population?.planned))&&Number.isFinite(Number(p.prosperity?.value))&&p.inputs?.local?.resources)}
function providerRef(seedValue,planId,functionId){return F({kind:"settlement-function",id:"SFP-"+H(seedValue+"|"+planId+"|"+functionId)})}
function normalizeAggregate(seedValue,whenValue,plan,raw){if(!raw)return null;const a=raw.values&&typeof raw.values==="object"?raw.values:raw,settlementId=txt(raw.settlementId||plan.id),sourceSystem=txt(raw.sourceSystem||"RegionalSettlementSimulation",80),validated=raw.validated!==false;if(settlementId!==plan.id||sourceSystem!=="RegionalSettlementSimulation"||!validated)return null;const fantasyTimestamp=txt(raw.fantasyTimestamp||a.lastSimulatedTimestamp||a.reconciliation?.lastAggregateTimestamp,32);if(!fantasyTimestamp)return null;let ageHours;try{ageHours=(seconds(whenValue)-seconds(fantasyTimestamp))/3600}catch(_){return null}const future=ageHours<0,stale=future||ageHours>STALE_HOURS;return F({sourceSystem,settlementId:plan.id,refId:id(raw.refId||raw.id||("AGG-"+H(seedValue+"|"+plan.id+"|"+fantasyTimestamp))),fantasyTimestamp,revision:Math.max(0,Math.floor(Number(raw.revision??a.revision)||0)),ageHours:round(ageHours,2),stale,future,values:F({foodSupply:clamp(a.foodSupply??a.food??plan.inputs.local.resources.agriculture??0.5),productionOutput:clamp(a.productionOutput??a.production??0.5),tradeActivity:clamp(a.tradeActivity??a.trade??plan.tradeMarketTendency??0.5),prosperity:clamp(a.prosperity??plan.prosperity.value),employmentPressure:clamp(a.employmentPressure??0.5)})})}
function liveAggregate(seedValue,whenValue,plan,options){if(options&&options.aggregate!==undefined)return normalizeAggregate(seedValue,whenValue,plan,options.aggregate);const w=R().WorldState,ref=w?.settlementRef?.(seedValue,plan),resolved=ref&&w?.resolve?.(seedValue,ref),a=resolved?.current?.state?.aggregate;if(!a)return null;return normalizeAggregate(seedValue,whenValue,plan,{sourceSystem:"RegionalSettlementSimulation",settlementId:plan.id,refId:ref.id,fantasyTimestamp:a.lastSimulatedTimestamp||a.reconciliation?.lastAggregateTimestamp,revision:a.revision,values:a,validated:true})}
function composition(seedValue,plan,options){const supplied=options?.composition;if(supplied){if(supplied.settlementId!==plan.id||!Array.isArray(supplied.selected))return null;return supplied}return R().SettlementBuildingCatalog?.compose?.(seedValue,plan)||null}
function providerRows(seedValue,plan,comp){const supported=new Set(OFFER_DEFS.map(x=>x.provider)),rows=[];for(const row of Array.isArray(comp?.selected)?comp.selected:[]){if(!supported.has(row.id))continue;rows.push(F({functionId:id(row.id,80),label:txt(row.label||row.id,120),count:Math.max(1,Math.floor(Number(row.count)||1)),category:txt(row.category||"",80),ref:providerRef(seedValue,plan.id,row.id),compositionRevision:txt(comp.revision||comp.id||"",160)}));if(rows.length>=MAX_PROVIDERS)break}return F(rows)}
function driverValue(def,agg,plan){if(!agg)return 1;const v=agg.values;if(def.driver==="food")return v.foodSupply;if(def.driver==="production")return v.productionOutput;if(def.driver==="trade")return v.tradeActivity;return clamp((v.productionOutput+v.tradeActivity+(1-v.employmentPressure))/3)}
function priceFor(seedValue,plan,provider,def,agg){const foundation=0.90+foundationUnit(seedValue,"market-price|"+plan.id+"|"+provider.functionId+"|"+def.id)*0.20,prosperity=agg?agg.values.prosperity:clamp(plan.prosperity.value),driver=agg?driverValue(def,agg,plan):0.65,scarcity=1-driver,mult=clamp(foundation+(prosperity-0.5)*0.16+scarcity*0.58-(agg?.values.tradeActivity??clamp(plan.tradeMarketTendency??0.5))*0.12,0.65,1.85);return Math.max(1,Math.min(MAX_PRICE_COPPER,Math.round(def.basePrice*mult)))}
function quantityFor(seedValue,plan,provider,def,agg){const classScale=({hamlet:0.65,village:1,town:1.35,city:1.75,"national-capital":2.1})[plan.classId]||1,foundation=0.88+foundationUnit(seedValue,"market-stock|"+plan.id+"|"+provider.functionId+"|"+def.id)*0.24,driver=agg?driverValue(def,agg,plan):0.72,availability=clamp((driver-0.08)/0.92),q=Math.round(def.baseStock*Math.max(1,provider.count)*classScale*foundation*availability);return Math.max(0,Math.min(999,q))}
function selectedDefinitions(seedValue,plan,provider){return OFFER_DEFS.filter(x=>x.provider===provider.functionId).filter(def=>def.core||foundationUnit(seedValue,"market-assort|"+plan.id+"|"+provider.functionId+"|"+def.id)>=0.42)}
function buildOffer(seedValue,whenValue,plan,provider,def,agg){const offerId="OFFER-"+H(seedValue+"|"+plan.id+"|"+provider.ref.id+"|"+def.id),lastKnownPrice=priceFor(seedValue,plan,provider,def,agg),lastKnownQuantity=quantityFor(seedValue,plan,provider,def,agg),freshness=!agg?"foundation":agg.stale?"stale":"fresh",unknown=!!agg?.stale,state=unknown?"unknown":lastKnownQuantity>0?"available":"unavailable";return F({offerId,settlementId:plan.id,providerRef:provider.ref,providerFunctionId:provider.functionId,providerLabel:provider.label,offerKind:def.kind,category:def.category,label:def.label,itemRef:def.itemRef||null,serviceRef:def.serviceRef||null,currency:"copper",unitPriceCopper:unknown?null:lastKnownPrice,quantityAvailable:unknown?null:lastKnownQuantity,lastKnownUnitPriceCopper:lastKnownPrice,lastKnownQuantity,availabilityState:state,freshness,fantasyTimestamp:whenValue,sourceTimestamp:agg?.fantasyTimestamp||null,sourceRefs:F([{kind:"settlement-composition",id:provider.compositionRevision||plan.id},...(agg?[{kind:"settlement-aggregate",id:agg.refId}]:[])]),readOnly:true})}
function snapshot(seedValue,whenValue,planValue,optionsValue){const s=seed(seedValue),when=ts(whenValue),plan=planValue,options=optionsValue&&typeof optionsValue==="object"?optionsValue:{};if(!validPlan(plan))return F({ok:false,reason:"canonical-settlement-plan-required",version:VERSION,schema:SCHEMA,schemaVersion:SCHEMA_VERSION,seed:s,fantasyTimestamp:when,offers:F([])});const comp=composition(s,plan,options);if(!comp||comp.settlementId!==plan.id)return F({ok:false,reason:"settlement-composition-unavailable",version:VERSION,schema:SCHEMA,schemaVersion:SCHEMA_VERSION,seed:s,settlementId:plan.id,fantasyTimestamp:when,offers:F([])});const providers=providerRows(s,plan,comp),agg=liveAggregate(s,when,plan,options),offers=[];for(const provider of providers){for(const def of selectedDefinitions(s,plan,provider)){offers.push(buildOffer(s,when,plan,provider,def,agg));if(offers.length>=MAX_OFFERS)break}if(offers.length>=MAX_OFFERS)break}offers.sort((a,b)=>a.category.localeCompare(b.category)||a.providerFunctionId.localeCompare(b.providerFunctionId)||a.offerId.localeCompare(b.offerId));const snapshotId="MKT-"+H(S({version:VERSION,seed:s,settlementId:plan.id,when,compositionRevision:comp.revision||comp.id||null,aggregateRef:agg?.refId||null,aggregateRevision:agg?.revision||0,offers:offers.map(x=>[x.offerId,x.unitPriceCopper,x.quantityAvailable,x.availabilityState])}));return F({ok:true,reason:"ok",version:VERSION,schema:SCHEMA,schemaVersion:SCHEMA_VERSION,snapshotId,seed:s,settlementId:plan.id,settlementName:txt(plan.name||plan.id,120),classId:txt(plan.classId,40),fantasyTimestamp:when,compositionRef:F({kind:"settlement-composition",id:txt(comp.revision||comp.id||plan.id,160)}),aggregate:agg,providerCount:providers.length,offerCount:offers.length,providers,offers:F(offers),limits:F({maxProviders:MAX_PROVIDERS,maxOffers:MAX_OFFERS,maxQueryResults:MAX_QUERY_RESULTS,staleHours:STALE_HOURS}),authority:F({foundation:"Campaign SEED + canonical SettlementArchetypes/SettlementBuildingCatalog",liveContext:"RegionalSettlementSimulation via WorldState campaign delta when available",readOnly:true,fullWorldScan:false,wholeSettlementScan:false,perFrameScan:false,directWorldMutation:false,currencyMutation:false,inventoryMutation:false,marketMutation:false,buildingMutation:false,resourceMutation:false,sellerNpcFabrication:false})})}
function list(seedValue,whenValue,planValue,optionsValue={}){const snap=snapshot(seedValue,whenValue,planValue,optionsValue);if(!snap.ok)return F([]);const category=txt(optionsValue.category||"",40),state=txt(optionsValue.availabilityState||"",40),limit=Math.max(0,Math.min(MAX_QUERY_RESULTS,Math.floor(Number(optionsValue.limit)||MAX_QUERY_RESULTS)));return F(snap.offers.filter(x=>(!category||x.category===category)&&(!state||x.availabilityState===state)).slice(0,limit))}
function get(seedValue,whenValue,planValue,offerIdValue,optionsValue={}){const oid=id(offerIdValue),snap=snapshot(seedValue,whenValue,planValue,optionsValue);if(!oid||!snap.ok)return null;return snap.offers.find(x=>x.offerId===oid)||null}
function summary(seedValue,whenValue,planValue,optionsValue={}){const snap=snapshot(seedValue,whenValue,planValue,optionsValue);if(!snap.ok)return F({ok:false,reason:snap.reason,text:"Local market information is unavailable.",grounded:true,readOnly:true});const available=snap.offers.filter(x=>x.availabilityState==="available").length,unavailable=snap.offers.filter(x=>x.availabilityState==="unavailable").length,unknown=snap.offers.filter(x=>x.availabilityState==="unknown").length;return F({ok:true,reason:"ok",text:available+" local offer"+(available===1?" is":"s are")+" currently available; "+unavailable+" unavailable; "+unknown+" unknown.",grounded:true,source:"LocalMarket canonical settlement context",settlementId:snap.settlementId,available,unavailable,unknown,readOnly:true})}
R().LocalMarket=Object.freeze({VERSION,SCHEMA,SCHEMA_VERSION,OFFER_DEFS,MAX_PROVIDERS,MAX_OFFERS,MAX_QUERY_RESULTS,STALE_HOURS,MAX_PRICE_COPPER,snapshot,list,get,summary});
if(typeof module!=="undefined"&&module.exports)module.exports=R().LocalMarket;
})();
