(function(){
"use strict";
const VERSION="protagonist-wealth-v1",SCHEMA="ProtagonistWealthLedger",SCHEMA_VERSION=1;
const REGISTRY_KIND="protagonist-wealth-ledger",REGISTRY_KEY="authoritative-currency",CURRENCY="copper";
const MAX_TRANSACTIONS=64,MAX_LEDGER_BYTES=65536,MAX_QUERY_RESULTS=24,MAX_OPERATION_IDS=96,MAX_AMOUNT=1000000,MAX_BALANCE=100000000,MAX_CUMULATIVE=9000000000000;
function R(){return typeof window!=="undefined"?window:globalThis}
function C(v){if(v==null||typeof v!=="object")return v;if(Array.isArray(v))return v.map(C);return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,C(x)]))}
function F(v){if(v==null||typeof v!=="object"||Object.isFrozen(v))return v;Object.values(v).forEach(F);return Object.freeze(v)}
function S(v){if(v==null||typeof v!=="object")return JSON.stringify(v);if(Array.isArray(v))return "["+v.map(S).join(",")+"]";return "{"+Object.keys(v).sort().map(k=>JSON.stringify(k)+":"+S(v[k])).join(",")+"}"}
function H(v){let h=2166136261>>>0;for(const ch of String(v??"")){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)>>>0}return(h>>>0).toString(16).toUpperCase().padStart(8,"0")}
function bytes(v){return typeof TextEncoder!=="undefined"?new TextEncoder().encode(String(v)).length:String(v).length}
function txt(v,n=160){return String(v??"").trim().replace(/\s+/g," ").slice(0,n)}
function id(v,n=160){return txt(v,n).replace(/[^A-Za-z0-9:_|.@/\-]/g,"-")}
function seed(v){const s=txt(v);if(!s)throw new Error("Campaign SEED is required.");return s}
function ts(v){const x=txt(v||R().GameTime?.getTimestampKey?.(),32);if(!/^\d{4,}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(x))throw new Error("Fantasy timestamp must be YYYY-MM-DD HH:MM:SS.");return x}
function actor(s,k){try{return R().ProtagonistProfile?.derive?.(s,k)?.protagonistId||("PROTAGONIST-"+H(s+"|"+k+"|identity-v1"))}catch(_){return"PROTAGONIST-"+H(s+"|"+k+"|identity-v1")}}
function stableRef(v){const x=v&&typeof v==="object"?v:{},kind=id(x.kind||x.type||"",64),rid=id(x.id||x.refId||x.entityId||"",160);return kind&&rid?F({kind,id:rid}):null}
function openingBalance(s,protagonistId){return 18+(parseInt(H(s+"|"+protagonistId+"|wealth-opening-v1"),16)%19)}
function ctx(seedValue,identityValue){const s=seed(seedValue),identityKey=id(identityValue||"protagonist",96)||"protagonist",protagonistId=actor(s,identityKey),w=R().WorldState;const ref=w?.structuralRef?.(s,REGISTRY_KIND,protagonistId,REGISTRY_KEY,{role:"protagonist-wealth",protagonistId,identityKey,currency:CURRENCY,authority:"ProtagonistWealth"})||null;return F({seed:s,identityKey,protagonistId,openingBalance:openingBalance(s,protagonistId),ref})}
function empty(c){return{schema:SCHEMA,schemaVersion:SCHEMA_VERSION,version:VERSION,seed:c.seed,protagonistId:c.protagonistId,identityKey:c.identityKey,registryId:c.ref?.id||null,currency:CURRENCY,openingBalance:c.openingBalance,balance:c.openingBalance,totalCredited:0,totalDebited:0,lastFantasyTimestamp:null,revision:0,transactions:[],recentOperations:[]}}
function validTransaction(x){return!!(x&&/^TXN-[0-9A-F]{8}$/.test(x.id)&&id(x.operationId)===x.operationId&&(x.direction==="credit"||x.direction==="debit")&&Number.isInteger(x.amount)&&x.amount>0&&x.amount<=MAX_AMOUNT&&id(x.reasonCode,96)===x.reasonCode&&stableRef(x.sourceRef)&&(!x.transferRef||stableRef(x.transferRef))&&/^\d{4,}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(x.fantasyTimestamp)&&Number.isInteger(x.balanceBefore)&&Number.isInteger(x.balanceAfter)&&x.balanceBefore>=0&&x.balanceAfter>=0&&x.balanceAfter<=MAX_BALANCE&&x.balanceAfter===x.balanceBefore+(x.direction==="credit"?x.amount:-x.amount)&&/^SIG-[0-9A-F]{16}$/.test(x.signature))}
function compatible(l,c){if(!l||l.schema!==SCHEMA||l.schemaVersion!==SCHEMA_VERSION||l.version!==VERSION||l.seed!==c.seed||l.protagonistId!==c.protagonistId||l.identityKey!==c.identityKey||l.registryId!==(c.ref?.id||null)||l.currency!==CURRENCY||l.openingBalance!==c.openingBalance||!Number.isInteger(l.balance)||l.balance<0||l.balance>MAX_BALANCE||!Number.isInteger(l.totalCredited)||l.totalCredited<0||l.totalCredited>MAX_CUMULATIVE||!Number.isInteger(l.totalDebited)||l.totalDebited<0||l.totalDebited>MAX_CUMULATIVE||l.balance!==l.openingBalance+l.totalCredited-l.totalDebited||!(l.lastFantasyTimestamp===null||/^\d{4,}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(l.lastFantasyTimestamp))||!Array.isArray(l.transactions)||!Array.isArray(l.recentOperations)||l.transactions.length>MAX_TRANSACTIONS||l.recentOperations.length>MAX_OPERATION_IDS)return false;const tids=new Set(),ops=new Set();for(const x of l.transactions){if(!validTransaction(x)||tids.has(x.id)||ops.has(x.operationId))return false;tids.add(x.id);ops.add(x.operationId)}const seenOps=new Set();for(const op of l.recentOperations){if(!op||!id(op.operationId)||op.operationId!==id(op.operationId)||!/^TXN-[0-9A-F]{8}$/.test(op.transactionId)||!/^SIG-[0-9A-F]{16}$/.test(op.signature)||seenOps.has(op.operationId))return false;seenOps.add(op.operationId)}return bytes(S(l))<=MAX_LEDGER_BYTES}
function read(seedValue,identityValue){const c=ctx(seedValue,identityValue),resolved=c.ref&&R().WorldState?.resolve?.(c.seed,c.ref),raw=resolved?.current?.protagonistWealth;if(raw==null)return{c,resolved,ok:true,ledger:empty(c),reason:"empty"};return compatible(raw,c)?{c,resolved,ok:true,ledger:C(raw),reason:"ok"}:{c,resolved,ok:false,ledger:null,reason:"wealth-ledger-incompatible"}}
function write(seedValue,identityValue,l,reason){const r=read(seedValue,identityValue);if(!r.ok)return F({ok:false,reason:r.reason});if(!r.c.ref||!R().WorldState?.applyDelta)return F({ok:false,reason:"world-state-unavailable"});const n=C(l);Object.assign(n,{schema:SCHEMA,schemaVersion:SCHEMA_VERSION,version:VERSION,seed:r.c.seed,protagonistId:r.c.protagonistId,identityKey:r.c.identityKey,registryId:r.c.ref.id,currency:CURRENCY,openingBalance:r.c.openingBalance,revision:(Number(n.revision)||0)+1});if(!compatible(n,r.c))return F({ok:false,reason:"wealth-invalid-or-over-budget"});const out=R().WorldState.applyDelta(r.c.seed,r.c.ref,{protagonistWealth:n},reason);return F({ok:!!out?.ok,reason:out?.reason||"ok",balance:n.balance,transactionCount:n.transactions.length,serializedBytes:bytes(S(n)),ledgerRevision:n.revision,deltaRevision:Number(out?.entry?.revision||0)})}
function auth(seedValue,v){const o=v&&typeof v==="object"?v:{};if(o.authority!=="simulation"||o.authoritative!==true)return{ok:false,reason:"simulation-authority-required"};const campaignSeed=txt(o.campaignSeed);if(!campaignSeed)return{ok:false,reason:"campaign-seed-required"};if(campaignSeed!==seedValue)return{ok:false,reason:"campaign-seed-mismatch"};const operationId=id(o.operationId||o.eventId||o.id);if(!operationId)return{ok:false,reason:"operation-id-required"};try{return{ok:true,operationId,fantasyTimestamp:ts(o.fantasyTimestamp||o.timestamp)}}catch(e){return{ok:false,reason:String(e.message||e)}}}
function amount(v){const n=Number(v);return Number.isInteger(n)&&n>0&&n<=MAX_AMOUNT?n:null}
function normalizeTransaction(v){const x=v&&typeof v==="object"?v:{},direction=x.direction==="credit"?"credit":x.direction==="debit"?"debit":null,a=amount(x.amount),reasonCode=id(x.reasonCode||x.reason||"",96),sourceRef=stableRef(x.sourceRef),transferRef=x.transferRef==null?null:stableRef(x.transferRef);if(!direction)return{ok:false,reason:"transaction-direction-invalid"};if(!a)return{ok:false,reason:"transaction-amount-invalid"};if(!reasonCode)return{ok:false,reason:"transaction-reason-required"};if(!sourceRef)return{ok:false,reason:"transaction-source-required"};if(x.transferRef!=null&&!transferRef)return{ok:false,reason:"transfer-reference-invalid"};return{ok:true,transaction:{direction,amount:a,reasonCode,sourceRef,transferRef}}}
function signature(c,a,t){const payload=S({version:VERSION,seed:c.seed,protagonistId:c.protagonistId,operationId:a.operationId,fantasyTimestamp:a.fantasyTimestamp,direction:t.direction,amount:t.amount,reasonCode:t.reasonCode,sourceRef:t.sourceRef,transferRef:t.transferRef});return "SIG-"+H("A|"+payload)+H("B|"+payload)}
function duplicateResult(seedValue,identityValue,found,sig){if(found.signature!==sig)return F({ok:false,reason:"duplicate-operation-conflict",duplicate:false,operationId:found.operationId,transactionId:found.transactionId});return F({ok:true,reason:"duplicate-operation",duplicate:true,operationId:found.operationId,transactionId:found.transactionId,snapshot:snapshot(seedValue,identityValue)})}
function remember(l,op){l.recentOperations=[...l.recentOperations.filter(x=>x.operationId!==op.operationId),op].slice(-MAX_OPERATION_IDS)}
function apply(seedValue,transactionValue,optionsValue,identityValue){const s=seed(seedValue),a=auth(s,optionsValue);if(!a.ok)return F(a);const n=normalizeTransaction(transactionValue);if(!n.ok)return F(n);const r=read(s,identityValue);if(!r.ok)return F({ok:false,reason:r.reason});const sig=signature(r.c,a,n.transaction),found=r.ledger.recentOperations.find(x=>x.operationId===a.operationId);if(found)return duplicateResult(s,identityValue,found,sig);if(r.ledger.lastFantasyTimestamp&&a.fantasyTimestamp<r.ledger.lastFantasyTimestamp)return F({ok:false,reason:"timestamp-before-current-state"});const before=r.ledger.balance,after=before+(n.transaction.direction==="credit"?n.transaction.amount:-n.transaction.amount);if(after<0)return F({ok:false,reason:"insufficient-funds",balance:before,required:n.transaction.amount});if(after>MAX_BALANCE)return F({ok:false,reason:"balance-limit-exceeded",balance:before,amount:n.transaction.amount});const creditTotal=r.ledger.totalCredited+(n.transaction.direction==="credit"?n.transaction.amount:0),debitTotal=r.ledger.totalDebited+(n.transaction.direction==="debit"?n.transaction.amount:0);if(creditTotal>MAX_CUMULATIVE||debitTotal>MAX_CUMULATIVE)return F({ok:false,reason:"cumulative-limit-exceeded"});const txSig=sig,transactionId="TXN-"+H(txSig),record=F({id:transactionId,operationId:a.operationId,direction:n.transaction.direction,amount:n.transaction.amount,currency:CURRENCY,reasonCode:n.transaction.reasonCode,sourceRef:n.transaction.sourceRef,transferRef:n.transaction.transferRef,fantasyTimestamp:a.fantasyTimestamp,balanceBefore:before,balanceAfter:after,signature:txSig}),l=C(r.ledger);l.balance=after;l.totalCredited=creditTotal;l.totalDebited=debitTotal;l.lastFantasyTimestamp=a.fantasyTimestamp;l.transactions=[...l.transactions,C(record)].slice(-MAX_TRANSACTIONS);remember(l,{operationId:a.operationId,transactionId,signature:txSig});const w=write(s,identityValue,l,"protagonist-wealth-"+n.transaction.direction+":"+transactionId);return F({...w,duplicate:false,operationId:a.operationId,transactionId,transaction:w.ok?record:null})}
function credit(seedValue,amountValue,detailsValue,optionsValue,identityValue){const d=detailsValue&&typeof detailsValue==="object"?detailsValue:{};return apply(seedValue,{direction:"credit",amount:amountValue,reasonCode:d.reasonCode||d.reason,sourceRef:d.sourceRef,transferRef:d.transferRef},optionsValue,identityValue)}
function debit(seedValue,amountValue,detailsValue,optionsValue,identityValue){const d=detailsValue&&typeof detailsValue==="object"?detailsValue:{};return apply(seedValue,{direction:"debit",amount:amountValue,reasonCode:d.reasonCode||d.reason,sourceRef:d.sourceRef,transferRef:d.transferRef},optionsValue,identityValue)}
function list(seedValue,o={},identityValue){const r=read(seedValue,identityValue);if(!r.ok)return F([]);const limit=Math.max(0,Math.min(MAX_QUERY_RESULTS,Math.floor(Number(o.limit)||MAX_QUERY_RESULTS))),direction=o.direction==="credit"||o.direction==="debit"?o.direction:null;return F(C(r.ledger.transactions).reverse().filter(x=>!direction||x.direction===direction).slice(0,limit).map(F))}
function get(seedValue,transactionIdValue,identityValue){const tid=id(transactionIdValue);if(!tid)return null;const r=read(seedValue,identityValue);if(!r.ok)return null;const x=r.ledger.transactions.find(y=>y.id===tid);return x?F(C(x)):null}
function snapshot(seedValue,identityValue){const s=seed(seedValue),r=read(s,identityValue);if(!r.ok)return F({version:VERSION,schema:SCHEMA,schemaVersion:SCHEMA_VERSION,seed:s,compatible:false,reason:r.reason,currency:CURRENCY,balance:null,transactions:F([]),bounded:true});const l=r.ledger,transactions=C(l.transactions).map(F);return F({version:VERSION,schema:SCHEMA,schemaVersion:SCHEMA_VERSION,seed:s,protagonistId:r.c.protagonistId,compatible:true,currency:CURRENCY,openingBalance:l.openingBalance,balance:l.balance,totalCredited:l.totalCredited,totalDebited:l.totalDebited,lastFantasyTimestamp:l.lastFantasyTimestamp,transactionCount:transactions.length,operationIdCount:l.recentOperations.length,serializedBytes:bytes(S(l)),maxTransactions:MAX_TRANSACTIONS,maxLedgerBytes:MAX_LEDGER_BYTES,maxQueryResults:MAX_QUERY_RESULTS,maxOperationIds:MAX_OPERATION_IDS,maxAmount:MAX_AMOUNT,maxBalance:MAX_BALANCE,transactions:F(transactions),persistenceAuthority:"WorldState CampaignStateDelta",foundationAuthority:"Campaign SEED only",mutationAuthority:"explicit Simulation-authorized transactions only",bounded:true,readOnlySnapshot:true,fullWorldScan:false,wholeHistoryScan:false,perFrameScan:false,directActionExecution:false,directInventoryMutation:false,settlementEconomyAuthority:false,presentationAuthority:false,providerAuthority:false})}
function canAfford(seedValue,amountValue,identityValue){const a=amount(amountValue),s=snapshot(seedValue,identityValue);if(!a)return F({ok:false,reason:"transaction-amount-invalid",affordable:false,balance:s.balance,currency:CURRENCY,readOnly:true});if(!s.compatible)return F({ok:false,reason:s.reason,affordable:false,balance:null,currency:CURRENCY,readOnly:true});return F({ok:true,reason:a<=s.balance?"ok":"insufficient-funds",affordable:a<=s.balance,amount:a,balance:s.balance,currency:CURRENCY,readOnly:true,fullWorldScan:false,directActionExecution:false})}
function conversationSummary(seedValue,identityValue){const s=snapshot(seedValue,identityValue);if(!s.compatible)return null;return F({text:"I currently have "+s.balance+" copper coin"+(s.balance===1?"":"s")+".",source:"ProtagonistWealth authoritative state",grounded:true,currency:CURRENCY,balance:s.balance,readOnly:true})}
function commandContext(seedValue,identityValue){const s=snapshot(seedValue,identityValue);return F({version:VERSION,protagonistId:s.protagonistId||null,compatible:s.compatible,currency:CURRENCY,balance:s.balance,openingBalance:s.openingBalance,recentTransactions:F((s.transactions||[]).slice(-8).reverse().map(x=>F({transactionId:x.id,direction:x.direction,amount:x.amount,reasonCode:x.reasonCode,sourceRef:C(x.sourceRef),transferRef:C(x.transferRef),fantasyTimestamp:x.fantasyTimestamp}))),summary:conversationSummary(seedValue,identityValue),bounded:true,source:"ProtagonistWealth",readOnly:true,fullWorldScan:false,wholeHistoryScan:false,perFrameScan:false,directActionExecution:false,directInventoryMutation:false,settlementEconomyAuthority:false})}
R().ProtagonistWealth=Object.freeze({VERSION,SCHEMA,SCHEMA_VERSION,REGISTRY_KIND,REGISTRY_KEY,CURRENCY,MAX_TRANSACTIONS,MAX_LEDGER_BYTES,MAX_QUERY_RESULTS,MAX_OPERATION_IDS,MAX_AMOUNT,MAX_BALANCE,openingBalance,apply,credit,debit,get,list,snapshot,canAfford,conversationSummary,commandContext});
if(typeof module!=="undefined"&&module.exports)module.exports=R().ProtagonistWealth;
})();
