(function(){
"use strict";
const VERSION="protagonist-housing-v1",SCHEMA="ProtagonistHousingLedger",SCHEMA_VERSION=1;
const REGISTRY_KIND="protagonist-housing-ledger",REGISTRY_KEY="housing";
const MAX_RESIDENCES=16,MAX_PAYMENTS=24,MAX_LEDGER_BYTES=32768,MAX_QUERY_RESULTS=12,MAX_RENT_COPPER=100000,MAX_CADENCE_DAYS=30;
const BASES=Object.freeze(["free-household","owned","rented"]);
function R(){return typeof window!=="undefined"?window:globalThis}
function C(v){if(v==null||typeof v!=="object")return v;if(Array.isArray(v))return v.map(C);return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,C(x)]))}
function F(v){if(v==null||typeof v!=="object"||Object.isFrozen(v))return v;Object.values(v).forEach(F);return Object.freeze(v)}
function S(v){if(v==null||typeof v!=="object")return JSON.stringify(v);if(Array.isArray(v))return"["+v.map(S).join(",")+"]";return"{"+Object.keys(v).sort().map(k=>JSON.stringify(k)+":"+S(v[k])).join(",")+"}"}
function H(v){let h=2166136261>>>0;for(const ch of String(v??"")){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)>>>0}return(h>>>0).toString(16).toUpperCase().padStart(8,"0")}
function B(v){return typeof TextEncoder!=="undefined"?new TextEncoder().encode(String(v)).length:String(v).length}
function T(v,n=160){return String(v??"").trim().replace(/\s+/g," ").slice(0,n)}
function I(v,n=160){return T(v,n).replace(/[^A-Za-z0-9:_|.@/\-]/g,"-")}
function P(v){return!!v&&typeof v==="object"&&!Array.isArray(v)}
function seed(v){const s=T(v);if(!s)throw new Error("Campaign SEED is required.");return s}
function validTs(v){return /^[0-9]{4,}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$/.test(String(v||""))}
function ts(v){const x=T(v,32);if(!validTs(x))throw new Error("Fantasy timestamp must be YYYY-MM-DD HH:MM:SS.");return x}
function ref(v){if(!P(v))return null;const kind=I(v.kind||v.type,64),id=I(v.id||v.refId||v.entityId,160);return kind&&id?F({kind,id}):null}
function eqRef(a,b){return!!a&&!!b&&a.kind===b.kind&&a.id===b.id}
function actor(s,k){try{return R().ProtagonistProfile?.derive?.(s,k)?.protagonistId||("PROTAGONIST-"+H(s+"|"+k+"|housing"))}catch(_){return"PROTAGONIST-"+H(s+"|"+k+"|housing")}}
function ctx(seedValue,identityValue){const s=seed(seedValue),identityKey=I(identityValue||"protagonist",96)||"protagonist",protagonistId=actor(s,identityKey),w=R().WorldState,structural=w?.structuralRef?.(s,REGISTRY_KIND,protagonistId,REGISTRY_KEY,{role:"protagonist-housing",protagonistId,identityKey,authority:"ProtagonistHousing"})||null;return F({seed:s,identityKey,protagonistId,ref:structural})}
function leap(y){return y%4===0&&(y%100!==0||y%400===0)}
function dim(y,m){return m===2?(leap(y)?29:28):([4,6,9,11].includes(m)?30:31)}
function parts(v){const x=ts(v),m=/^([0-9]+)-([0-9]{2})-([0-9]{2}) ([0-9]{2}):([0-9]{2}):([0-9]{2})$/.exec(x),p={y:Number(m[1]),mo:Number(m[2]),d:Number(m[3]),h:Number(m[4]),mi:Number(m[5]),s:Number(m[6])};if(p.mo<1||p.mo>12||p.d<1||p.d>dim(p.y,p.mo)||p.h>23||p.mi>59||p.s>59)throw new Error("Fantasy timestamp components are invalid.");return p}
function stamp(p){return String(p.y).padStart(4,"0")+"-"+String(p.mo).padStart(2,"0")+"-"+String(p.d).padStart(2,"0")+" "+String(p.h).padStart(2,"0")+":"+String(p.mi).padStart(2,"0")+":"+String(p.s).padStart(2,"0")}
function addDays(v,n){const p=parts(v),count=Math.max(0,Math.min(MAX_CADENCE_DAYS,Math.floor(Number(n)||0)));for(let i=0;i<count;i++){p.d++;if(p.d>dim(p.y,p.mo)){p.d=1;p.mo++;if(p.mo>12){p.mo=1;p.y++}}}return stamp(p)}
function auth(s,v,kind="simulation"){const x=P(v)?v:{};if(x.authority!==kind||x.authoritative!==true)return{ok:false,reason:kind+"-authority-required"};if(T(x.campaignSeed)!==s)return{ok:false,reason:"campaign-seed-mismatch"};try{return{ok:true,fantasyTimestamp:ts(x.fantasyTimestamp||x.timestamp),economicTransactionId:I(x.economicTransactionId)}}catch(e){return{ok:false,reason:String(e.message||e)}}}
function houses(s){const rows=R().HousePlans?.build?.(s);if(!Array.isArray(rows))return null;if(rows.length>MAX_RESIDENCES)return null;return rows}
function residence(s,v){const r=ref(v);if(!r||r.kind!=="house-plan")return null;const list=houses(s);if(!list)return null;const plan=list.find(x=>I(x?.id)===r.id)||null;return plan?F({ref:r,label:T(plan.kind||"home",64)+" "+r.id,planId:r.id,kind:T(plan.kind||"home",32)}):null}
function foundation(c){const list=houses(c.seed);if(!list||!list.length)return null;const index=parseInt(H(c.seed+"|"+c.protagonistId+"|foundation-residence"),16)%list.length,plan=list[index],residenceRef=F({kind:"house-plan",id:I(plan.id)}),householdRef=F({kind:"household",id:"HOUSEHOLD-"+I(plan.id)}),sourceRef=F({kind:"seed-foundation",id:"HOUSING-"+H(c.seed+"|"+c.protagonistId+"|"+plan.id)});return F({arrangementId:"HOU-"+H(S({seed:c.seed,protagonistId:c.protagonistId,residenceRef,occupancyBasis:"free-household",sourceRef})),residenceRef,householdRef,occupancyBasis:"free-household",rentCopper:0,cadenceDays:0,effectiveAt:null,nextDueAt:null,obligationId:null,sourceRef,foundation:true})}
function empty(c){return{schema:SCHEMA,schemaVersion:SCHEMA_VERSION,version:VERSION,seed:c.seed,protagonistId:c.protagonistId,identityKey:c.identityKey,registryId:c.ref?.id||null,revision:0,currentArrangement:null,payments:[]}}
function arrangementValid(x){return!!(P(x)&&/^HOU-[0-9A-F]{8}$/.test(String(x.arrangementId||""))&&ref(x.residenceRef)?.kind==="house-plan"&&ref(x.householdRef)?.kind==="household"&&BASES.includes(x.occupancyBasis)&&Number.isInteger(x.rentCopper)&&x.rentCopper>=0&&x.rentCopper<=MAX_RENT_COPPER&&Number.isInteger(x.cadenceDays)&&x.cadenceDays>=0&&x.cadenceDays<=MAX_CADENCE_DAYS&&((x.occupancyBasis==="rented"&&x.rentCopper>0&&x.cadenceDays>0&&validTs(x.effectiveAt)&&validTs(x.nextDueAt)&&/^HOB-[0-9A-F]{8}$/.test(String(x.obligationId||"")))||(x.occupancyBasis!=="rented"&&x.rentCopper===0&&x.cadenceDays===0&&x.nextDueAt==null&&x.obligationId==null))&&ref(x.sourceRef))}
function paymentValid(x){return!!(P(x)&&/^HPAY-[0-9A-F]{8}$/.test(String(x.paymentId||""))&&I(x.requestId)===x.requestId&&/^HSIG-[0-9A-F]{16}$/.test(String(x.signature||""))&&/^HOB-[0-9A-F]{8}$/.test(String(x.obligationId||""))&&/^HOU-[0-9A-F]{8}$/.test(String(x.arrangementId||""))&&["pending","completed"].includes(x.state)&&Number.isInteger(x.amountCopper)&&x.amountCopper>0&&x.amountCopper<=MAX_RENT_COPPER&&validTs(x.dueAt)&&validTs(x.startedAt)&&(/^EXO-[0-9A-F]{8}$/.test(String(x.economicTransactionId||"")))&&(!x.wealthTransactionId||/^TXN-[0-9A-F]{8}$/.test(String(x.wealthTransactionId))))}
function compatible(l,c){if(!P(l)||l.schema!==SCHEMA||l.schemaVersion!==SCHEMA_VERSION||l.version!==VERSION||l.seed!==c.seed||l.protagonistId!==c.protagonistId||l.identityKey!==c.identityKey||l.registryId!==(c.ref?.id||null)||!Number.isInteger(l.revision)||l.revision<0||!Array.isArray(l.payments)||l.payments.length>MAX_PAYMENTS)return false;if(l.currentArrangement!=null&&!arrangementValid(l.currentArrangement))return false;const ids=new Set(),reqs=new Set();for(const p of l.payments){if(!paymentValid(p)||ids.has(p.paymentId)||reqs.has(p.requestId))return false;ids.add(p.paymentId);reqs.add(p.requestId)}return B(S(l))<=MAX_LEDGER_BYTES}
function read(seedValue,identityValue){const c=ctx(seedValue,identityValue),resolved=c.ref&&R().WorldState?.resolve?.(c.seed,c.ref),raw=resolved?.current?.protagonistHousing;if(raw==null)return{ok:true,c,ledger:empty(c),reason:"empty"};return compatible(raw,c)?{ok:true,c,ledger:C(raw),reason:"ok"}:{ok:false,c,ledger:null,reason:"housing-ledger-incompatible"}}
function write(seedValue,identityValue,l,reason){const r=read(seedValue,identityValue);if(!r.ok)return F({ok:false,reason:r.reason});if(!r.c.ref||!R().WorldState?.applyDelta)return F({ok:false,reason:"world-state-unavailable"});const n=C(l);Object.assign(n,{schema:SCHEMA,schemaVersion:SCHEMA_VERSION,version:VERSION,seed:r.c.seed,protagonistId:r.c.protagonistId,identityKey:r.c.identityKey,registryId:r.c.ref.id,revision:(Number(n.revision)||0)+1});if(!compatible(n,r.c))return F({ok:false,reason:"housing-ledger-invalid-or-over-budget"});const out=R().WorldState.applyDelta(r.c.seed,r.c.ref,{protagonistHousing:n},reason);return F({ok:!!out?.ok,reason:out?.reason||"ok",ledgerRevision:n.revision,paymentCount:n.payments.length,serializedBytes:B(S(n)),deltaRevision:Number(out?.entry?.revision||0)})}
function active(r){return r.ledger.currentArrangement?F(C(r.ledger.currentArrangement)):foundation(r.c)}
function obligationState(arr,payments,whenValue){if(!arr||arr.occupancyBasis!=="rented")return F({state:"none",amountCopper:0,cadenceDays:0,nextDueAt:null,obligationId:null,lastPayment:null});const pending=payments.find(p=>p.obligationId===arr.obligationId&&p.state==="pending")||null,last=[...payments].reverse().find(p=>p.obligationId===arr.obligationId&&p.state==="completed")||null;let state="unknown";if(pending)state="payment-pending";else if(validTs(whenValue)){const w=ts(whenValue);state=w<arr.nextDueAt?"upcoming":w===arr.nextDueAt?"due":"overdue"}return F({state,amountCopper:arr.rentCopper,cadenceDays:arr.cadenceDays,nextDueAt:arr.nextDueAt,obligationId:arr.obligationId,lastPayment:last?F(C(last)):null,pendingPayment:pending?F(C(pending)):null})}
function snapshot(seedValue,whenValue,identityValue){const r=read(seedValue,identityValue);if(!r.ok)return F({version:VERSION,compatible:false,reason:r.reason});const arr=active(r);if(!arr)return F({version:VERSION,compatible:false,reason:"residence-foundation-unavailable"});if(!residence(r.c.seed,arr.residenceRef))return F({version:VERSION,compatible:false,reason:"residence-reference-invalid"});const o=obligationState(arr,r.ledger.payments,whenValue);return F({version:VERSION,schema:SCHEMA,schemaVersion:SCHEMA_VERSION,compatible:true,protagonistId:r.c.protagonistId,arrangement:F(C(arr)),obligation:o,paymentCount:r.ledger.payments.length,payments:F(C(r.ledger.payments).map(F)),serializedBytes:B(S(r.ledger)),foundationActive:r.ledger.currentArrangement==null,persistenceAuthority:"WorldState CampaignStateDelta",residenceAuthority:"Campaign SEED HousePlans or Simulation-validated arrangement",currencyAuthority:"EconomicTransaction -> ProtagonistWealth only",eventDriven:true,bounded:true,fullSettlementScan:false,fullPropertyScan:false,wholeHistoryScan:false,perFrameBilling:false,directCurrencyMutation:false,directWorldMutation:false,directRelationshipMutation:false,forcedEviction:false,forcedHomelessness:false})}
function establish(seedValue,arrangementValue,optionsValue,identityValue){let s;try{s=seed(seedValue)}catch(e){return F({ok:false,reason:String(e.message||e)})}const a=auth(s,optionsValue);if(!a.ok)return F(a);const x=P(arrangementValue)?arrangementValue:{},basis=I(x.occupancyBasis||x.basis,32).toLowerCase(),rr=ref(x.residenceRef),sr=ref(x.sourceRef||optionsValue?.sourceRef);if(!BASES.includes(basis))return F({ok:false,reason:"occupancy-basis-invalid"});const home=residence(s,rr);if(!home)return F({ok:false,reason:"residence-reference-invalid"});if(!sr)return F({ok:false,reason:"simulation-source-reference-required"});const r=read(s,identityValue);if(!r.ok)return F({ok:false,reason:r.reason});if(r.ledger.payments.some(p=>p.state==="pending"))return F({ok:false,reason:"housing-payment-pending"});const amount=basis==="rented"?Number(x.rentCopper):0,cadence=basis==="rented"?Number(x.cadenceDays):0;if(basis==="rented"&&(!Number.isInteger(amount)||amount<=0||amount>MAX_RENT_COPPER))return F({ok:false,reason:"rent-amount-invalid"});if(basis==="rented"&&(!Number.isInteger(cadence)||cadence<=0||cadence>MAX_CADENCE_DAYS))return F({ok:false,reason:"rent-cadence-invalid"});const c=r.c,householdRef=ref(x.householdRef)||F({kind:"household",id:"HOUSEHOLD-"+rr.id}),base={seed:s,protagonistId:c.protagonistId,residenceRef:rr,householdRef,occupancyBasis:basis,rentCopper:amount,cadenceDays:cadence,effectiveAt:a.fantasyTimestamp,sourceRef:sr},arrangementId="HOU-"+H(S(base)),obligationId=basis==="rented"?"HOB-"+H(arrangementId+"|rent"):null,nextDueAt=basis==="rented"?addDays(a.fantasyTimestamp,cadence):null,arr=F({arrangementId,residenceRef:rr,householdRef,occupancyBasis:basis,rentCopper:amount,cadenceDays:cadence,effectiveAt:a.fantasyTimestamp,nextDueAt,obligationId,sourceRef:sr,foundation:false});const l=C(r.ledger);l.currentArrangement=C(arr);const saved=write(s,identityValue,l,"housing-arrangement:"+arrangementId);return saved.ok?F({ok:true,reason:"established",arrangement:arr,ledgerRevision:saved.ledgerRevision}):F({ok:false,reason:saved.reason})}
function requestPayload(arr){const n={arrangementId:arr.arrangementId,obligationId:arr.obligationId,residenceRef:arr.residenceRef,householdRef:arr.householdRef,amountCopper:arr.rentCopper,currency:"copper",dueAt:arr.nextDueAt,cycleKey:arr.nextDueAt},requestId="HREQ-"+H(S(n)),signature="HSIG-"+H("A|"+S({...n,requestId}))+H("B|"+S({...n,requestId}));return F({...n,requestId,signature})}
function paymentRequest(seedValue,whenValue,identityValue){const snap=snapshot(seedValue,whenValue,identityValue);if(!snap.compatible)return F({ok:false,reason:snap.reason});const arr=snap.arrangement;if(arr.occupancyBasis!=="rented")return F({ok:false,reason:"no-rent-obligation"});const pending=snap.obligation.pendingPayment;if(pending)return F({ok:true,reason:"payment-pending",request:F(C(pending.request)),state:"payment-pending",overdue:validTs(whenValue)&&ts(whenValue)>pending.dueAt});if(!validTs(whenValue))return F({ok:false,reason:"fantasy-time-required"});if(ts(whenValue)<arr.nextDueAt)return F({ok:false,reason:"obligation-not-due",nextDueAt:arr.nextDueAt});const request=requestPayload(arr);return F({ok:true,reason:snap.obligation.state,request,state:snap.obligation.state,overdue:snap.obligation.state==="overdue",readOnly:true})}
function validatePaymentRequest(seedValue,requestValue,optionsValue,identityValue){let s;try{s=seed(seedValue)}catch(e){return F({ok:false,reason:String(e.message||e)})}const a=auth(s,optionsValue);if(!a.ok)return F(a);const req=P(requestValue)?C(requestValue):{},requestId=I(req.requestId),signature=I(req.signature);if(!requestId||!/^HSIG-[0-9A-F]{16}$/.test(signature))return F({ok:false,reason:"housing-payment-request-invalid"});const r=read(s,identityValue);if(!r.ok)return F({ok:false,reason:r.reason});const existing=r.ledger.payments.find(p=>p.requestId===requestId)||null;if(existing){if(existing.signature!==signature||S(existing.request)!==S(req))return F({ok:false,reason:"duplicate-housing-payment-conflict"});return F({ok:true,reason:existing.state==="completed"?"duplicate-payment":"payment-pending",duplicate:existing.state==="completed",pending:existing.state==="pending",payment:F(C(existing)),request:F(req)})}const current=paymentRequest(s,a.fantasyTimestamp,identityValue);if(!current.ok)return F(current);if(S(current.request)!==S(req))return F({ok:false,reason:"stale-or-forged-housing-payment-request"});return F({ok:true,reason:"validated",duplicate:false,pending:false,request:F(req)})}
function beginPayment(seedValue,requestValue,optionsValue,identityValue){let s;try{s=seed(seedValue)}catch(e){return F({ok:false,reason:String(e.message||e)})}const a=auth(s,optionsValue,"economic-transaction");if(!a.ok)return F(a);if(!/^EXO-[0-9A-F]{8}$/.test(a.economicTransactionId))return F({ok:false,reason:"economic-transaction-reference-required"});const checked=validatePaymentRequest(s,requestValue,{authority:"simulation",authoritative:true,campaignSeed:s,fantasyTimestamp:a.fantasyTimestamp},identityValue);if(!checked.ok)return F(checked);if(checked.duplicate)return F({ok:true,reason:"duplicate-payment",duplicate:true,payment:checked.payment});const r=read(s,identityValue);if(!r.ok)return F({ok:false,reason:r.reason});const existing=r.ledger.payments.find(p=>p.requestId===requestValue.requestId)||null;if(existing){if(existing.economicTransactionId!==a.economicTransactionId)return F({ok:false,reason:"housing-payment-transaction-conflict"});return F({ok:true,reason:"payment-pending",duplicate:false,pending:true,payment:F(C(existing))})}if(r.ledger.payments.length>=MAX_PAYMENTS)return F({ok:false,reason:"housing-payment-cap-reached"});const row=F({paymentId:"HPAY-"+H(requestValue.requestId+"|"+a.economicTransactionId),requestId:requestValue.requestId,signature:requestValue.signature,obligationId:requestValue.obligationId,arrangementId:requestValue.arrangementId,state:"pending",amountCopper:requestValue.amountCopper,dueAt:requestValue.dueAt,startedAt:a.fantasyTimestamp,completedAt:null,economicTransactionId:a.economicTransactionId,wealthTransactionId:null,request:F(C(requestValue))}),l=C(r.ledger);l.payments.push(C(row));const saved=write(s,identityValue,l,"housing-payment:"+row.paymentId+":pending");return saved.ok?F({ok:true,reason:"payment-pending",pending:true,payment:row}):F({ok:false,reason:saved.reason})}
function completePayment(seedValue,requestValue,optionsValue,identityValue){let s;try{s=seed(seedValue)}catch(e){return F({ok:false,reason:String(e.message||e)})}const a=auth(s,optionsValue,"economic-transaction");if(!a.ok)return F(a);const wealthTransactionId=I(optionsValue?.wealthTransactionId);if(!/^EXO-[0-9A-F]{8}$/.test(a.economicTransactionId)||!/^TXN-[0-9A-F]{8}$/.test(wealthTransactionId))return F({ok:false,reason:"economic-payment-evidence-required"});const r=read(s,identityValue);if(!r.ok)return F({ok:false,reason:r.reason});const i=r.ledger.payments.findIndex(p=>p.requestId===I(requestValue?.requestId));if(i<0)return F({ok:false,reason:"housing-payment-not-prepared"});const row=r.ledger.payments[i];if(row.signature!==I(requestValue.signature)||row.economicTransactionId!==a.economicTransactionId)return F({ok:false,reason:"housing-payment-evidence-conflict"});if(row.state==="completed")return F({ok:true,reason:"duplicate-payment",duplicate:true,payment:F(C(row))});const arr=r.ledger.currentArrangement;if(!arr||arr.arrangementId!==row.arrangementId||arr.obligationId!==row.obligationId||arr.nextDueAt!==row.dueAt)return F({ok:false,reason:"housing-obligation-changed"});const l=C(r.ledger),done=F({...C(row),state:"completed",completedAt:a.fantasyTimestamp,wealthTransactionId}),next=F({...C(arr),nextDueAt:addDays(row.dueAt,arr.cadenceDays)});l.payments[i]=C(done);l.currentArrangement=C(next);const saved=write(s,identityValue,l,"housing-payment:"+row.paymentId+":completed");return saved.ok?F({ok:true,reason:"completed",duplicate:false,payment:done,arrangement:next}):F({ok:false,reason:saved.reason})}
function pay(seedValue,requestValue,optionsValue,identityValue){const tx=R().EconomicTransaction;if(!tx?.executeObligation)return F({ok:false,reason:"economic-transaction-unavailable"});return tx.executeObligation(seedValue,requestValue,optionsValue,identityValue)}
function decisionContext(seedValue,whenValue,identityValue){const snap=snapshot(seedValue,whenValue,identityValue);if(!snap.compatible)return F({ok:false,reason:snap.reason});const o=snap.obligation,priority=o.state==="overdue"?"high":o.state==="due"||o.state==="payment-pending"?"medium":"low";return F({ok:true,version:VERSION,residenceRef:snap.arrangement.residenceRef,householdRef:snap.arrangement.householdRef,occupancyBasis:snap.arrangement.occupancyBasis,obligation:F({state:o.state,obligationId:o.obligationId,amountCopper:o.amountCopper,nextDueAt:o.nextDueAt,priority}),advisoryContextOnly:true,directActionExecution:false,directCurrencyMutation:false,directEviction:false,directHomelessness:false,directRelationshipMutation:false,simulationValidationRequired:true})}
function listPayments(seedValue,o={},identityValue){const r=read(seedValue,identityValue);if(!r.ok)return F([]);const limit=Math.max(0,Math.min(MAX_QUERY_RESULTS,Math.floor(Number(o.limit)||MAX_QUERY_RESULTS))),state=I(o.state,24);return F(C(r.ledger.payments).reverse().filter(x=>!state||x.state===state).slice(0,limit).map(F))}
R().ProtagonistHousing=Object.freeze({VERSION,SCHEMA,SCHEMA_VERSION,REGISTRY_KIND,REGISTRY_KEY,BASES,MAX_RESIDENCES,MAX_PAYMENTS,MAX_LEDGER_BYTES,MAX_QUERY_RESULTS,MAX_RENT_COPPER,MAX_CADENCE_DAYS,addDays,snapshot,establish,paymentRequest,validatePaymentRequest,beginPayment,completePayment,pay,decisionContext,listPayments});
if(typeof module!=="undefined"&&module.exports)module.exports=R().ProtagonistHousing;
})();