(function(){
"use strict";

const VERSION="protagonist-needs-v1";
const SCHEMA="ProtagonistNeedsState";
const SCHEMA_VERSION=1;
const REGISTRY_KIND="protagonist-needs-state";
const REGISTRY_KEY="live-condition-v1";
const DEFAULT_IDENTITY_KEY="protagonist";
const NEED_KEYS=Object.freeze(["hunger","fatigue","safety","social"]);
const MAX_EVENT_IDS=64;
const MAX_STATE_BYTES=8192;
const PRESSURE_MAX=100000;
const URGENT_THRESHOLD=75000;
const EVENT_EFFECTS=Object.freeze({
  meal:Object.freeze({hunger:-35000}),
  snack:Object.freeze({hunger:-15000}),
  rest:Object.freeze({fatigue:-45000}),
  "brief-rest":Object.freeze({fatigue:-20000}),
  "safe-shelter":Object.freeze({safety:-30000}),
  danger:Object.freeze({safety:35000}),
  "social-contact":Object.freeze({social:-25000}),
  isolation:Object.freeze({social:20000}),
  "hard-exertion":Object.freeze({fatigue:20000,hunger:8000})
});
const telemetryState={reads:0,writes:0,initializations:0,advances:0,events:0,duplicates:0,rejections:0};

function root(){return typeof window!=="undefined"?window:globalThis}
function clone(value){if(value==null||typeof value!=="object")return value;if(Array.isArray(value))return value.map(clone);const out={};for(const [key,item] of Object.entries(value))out[key]=clone(item);return out}
function freeze(value){if(value==null||typeof value!=="object"||Object.isFrozen(value))return value;for(const item of Object.values(value))freeze(item);return Object.freeze(value)}
function stableStringify(value){if(value==null||typeof value!=="object")return JSON.stringify(value);if(Array.isArray(value))return "["+value.map(stableStringify).join(",")+"]";return "{"+Object.keys(value).sort().map(key=>JSON.stringify(key)+":"+stableStringify(value[key])).join(",")+"}"}
function hashText(value){let h=2166136261>>>0;for(const ch of String(value==null?"":value)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)>>>0}h^=h>>>16;h=Math.imul(h,2246822507);h^=h>>>13;return (h>>>0).toString(16).toUpperCase().padStart(8,"0")}
function utf8Bytes(value){const text=String(value==null?"":value);if(typeof TextEncoder!=="undefined")return new TextEncoder().encode(text).length;let n=0;for(let i=0;i<text.length;i++){const c=text.charCodeAt(i);n+=c<0x80?1:c<0x800?2:(c>=0xD800&&c<=0xDBFF&&i+1<text.length&&text.charCodeAt(i+1)>=0xDC00&&text.charCodeAt(i+1)<=0xDFFF?(i++,4):3)}return n}
function cleanText(value,max=160){return String(value==null?"":value).trim().replace(/\s+/g," ").slice(0,max)}
function cleanIdentityKey(value){return cleanText(value||DEFAULT_IDENTITY_KEY,96).replace(/[^A-Za-z0-9:_|.@/\-]/g,"-")||DEFAULT_IDENTITY_KEY}
function cleanId(value,max=160){return cleanText(value,max).replace(/[^A-Za-z0-9:_|.@/\-]/g,"-")}
function requiredSeed(value){const seed=cleanText(value,160);if(!seed)throw new Error("Campaign SEED is required.");return seed}
function bump(key){telemetryState[key]=Math.min(Number.MAX_SAFE_INTEGER,(telemetryState[key]||0)+1)}
function unit(seed,identity,label){return (parseInt(hashText(seed+"|"+identity+"|"+label),16)>>>0)/0xFFFFFFFF}
function rangeInt(seed,identity,label,min,max){return Math.round(min+unit(seed,identity,label)*(max-min))}
function canonicalProtagonistId(seed,identityKey){return root().ProtagonistProfile?.derive?.(seed,identityKey)?.protagonistId||("PROTAGONIST-"+hashText(seed+"|"+identityKey+"|identity-v1"))}
function validTimestamp(value){return /^\d{4,}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(String(value||""))}
function timestampParts(value){const text=String(value||""),m=text.match(/^(\d{4,})-(\d{2})-(\d{2}) (\d{2}):(\d{2}):(\d{2})$/);if(!m)return null;const p={year:Number(m[1]),month:Number(m[2]),day:Number(m[3]),hour:Number(m[4]),minute:Number(m[5]),second:Number(m[6])};if(p.month<1||p.month>12||p.day<1||p.day>31||p.hour>23||p.minute>59||p.second>59)return null;return p}
function daysFromCivil(year,month,day){const y=year-(month<=2?1:0),era=Math.floor(y/400),yoe=y-era*400,mp=month+(month>2?-3:9),doy=Math.floor((153*mp+2)/5)+day-1,doe=yoe*365+Math.floor(yoe/4)-Math.floor(yoe/100)+doy;return era*146097+doe}
function secondIndex(value){const p=timestampParts(value);if(!p)return null;return daysFromCivil(p.year,p.month,p.day)*86400+p.hour*3600+p.minute*60+p.second}
function currentTimestamp(){return root().GameTime?.getTimestampKey?.()||null}
function campaignStartTimestamp(){const campaign=root().SeedSystem?.getCampaign?.()||null;return campaign?.fantasyStart&&root().GameTime?.toTimestampKey?.(campaign.fantasyStart)||null}
function pressureBaseline(seed,identityKey){return freeze({
  hunger:rangeInt(seed,identityKey,"baseline:hunger",15000,26000),
  fatigue:rangeInt(seed,identityKey,"baseline:fatigue",12000,24000),
  safety:rangeInt(seed,identityKey,"baseline:safety",8000,18000),
  social:rangeInt(seed,identityKey,"baseline:social",12000,26000)
})}
function driftRates(seed,identityKey){return freeze({
  hunger:rangeInt(seed,identityKey,"rate:hunger",32,44),
  fatigue:rangeInt(seed,identityKey,"rate:fatigue",20,32),
  safety:rangeInt(seed,identityKey,"rate:safety",3,7),
  social:rangeInt(seed,identityKey,"rate:social",7,13)
})}
function context(seedValue,identityValue){const seed=requiredSeed(seedValue),identityKey=cleanIdentityKey(identityValue),protagonistId=canonicalProtagonistId(seed,identityKey),world=root().WorldState;const ref=world?.structuralRef?.(seed,REGISTRY_KIND,protagonistId,REGISTRY_KEY,{role:"protagonist-needs",protagonistId,identityKey,authority:"ProtagonistNeeds"})||null;return freeze({seed,identityKey,protagonistId,ref})}
function stateCompatible(raw,ctx){if(!raw||typeof raw!=="object")return false;if(raw.schema!==SCHEMA||Number(raw.schemaVersion)!==SCHEMA_VERSION||raw.version!==VERSION)return false;if(raw.seed!==ctx.seed||raw.identityKey!==ctx.identityKey||raw.protagonistId!==ctx.protagonistId)return false;if(!validTimestamp(raw.lastFantasyTimestamp)||!Number.isInteger(raw.lastSecondIndex))return false;if(!raw.pressureMilli||!raw.driftRemainder||!Array.isArray(raw.appliedEventIds)||raw.appliedEventIds.length>MAX_EVENT_IDS)return false;if(!Number.isInteger(raw.revision)||raw.revision<1||!Number.isInteger(raw.sourceEventCount)||raw.sourceEventCount<0)return false;const ids=new Set();for(const id of raw.appliedEventIds){if(!id||cleanId(id)!==id||ids.has(id))return false;ids.add(id)}for(const key of NEED_KEYS){if(!Number.isInteger(raw.pressureMilli[key])||raw.pressureMilli[key]<0||raw.pressureMilli[key]>PRESSURE_MAX)return false;if(!Number.isInteger(raw.driftRemainder[key])||raw.driftRemainder[key]<0||raw.driftRemainder[key]>=60)return false}return utf8Bytes(stableStringify(raw))<=MAX_STATE_BYTES}
function readState(seedValue,identityValue){bump("reads");const ctx=context(seedValue,identityValue),resolved=ctx.ref&&root().WorldState?.resolve?.(ctx.seed,ctx.ref)||null,raw=resolved?.current?.protagonistNeedsState;if(raw==null)return {ctx,resolved,compatible:true,exists:false,state:null,reason:"empty"};if(!stateCompatible(raw,ctx))return {ctx,resolved,compatible:false,exists:true,state:null,reason:"needs-state-incompatible"};return {ctx,resolved,compatible:true,exists:true,state:clone(raw),reason:"ok"}}
function initialState(ctx,timestampValue){const timestamp=String(timestampValue||"");const index=secondIndex(timestamp);if(index==null)throw new Error("Valid fantasy timestamp is required.");const pressureMilli=clone(pressureBaseline(ctx.seed,ctx.identityKey));return {schema:SCHEMA,schemaVersion:SCHEMA_VERSION,version:VERSION,seed:ctx.seed,protagonistId:ctx.protagonistId,identityKey:ctx.identityKey,lastFantasyTimestamp:timestamp,lastSecondIndex:index,pressureMilli,driftRemainder:{hunger:0,fatigue:0,safety:0,social:0},appliedEventIds:[],revision:1,sourceEventCount:0}}
function writeState(ctx,stateValue,reasonValue){const world=root().WorldState;if(!ctx.ref||!world?.applyDelta)return freeze({ok:false,reason:"world-state-unavailable"});const next=clone(stateValue);if(!stateCompatible(next,ctx))return freeze({ok:false,reason:"needs-state-invalid"});const serializedBytes=utf8Bytes(stableStringify(next));if(serializedBytes>MAX_STATE_BYTES)return freeze({ok:false,reason:"needs-state-size-exceeded",serializedBytes,maxStateBytes:MAX_STATE_BYTES});const result=world.applyDelta(ctx.seed,ctx.ref,{protagonistNeedsState:next},String(reasonValue||"protagonist-needs"));if(result?.ok)bump("writes");return freeze({ok:Boolean(result?.ok),reason:result?.reason||"ok",stateRevision:next.revision,deltaRevision:Number(result?.entry?.revision||0),serializedBytes})}
function resolveStartTimestamp(optionsValue,targetTimestamp){const options=optionsValue&&typeof optionsValue==="object"?optionsValue:{};return options.startTimestamp||campaignStartTimestamp()||targetTimestamp||currentTimestamp()||null}
function initialize(seedValue,identityValue,startTimestampValue){const read=readState(seedValue,identityValue);if(!read.compatible){bump("rejections");return freeze({ok:false,reason:read.reason})}if(read.exists)return freeze({ok:true,reason:"already-initialized",created:false,snapshot:snapshotFromRead(read)});const timestamp=startTimestampValue||campaignStartTimestamp()||currentTimestamp();if(!validTimestamp(timestamp)){bump("rejections");return freeze({ok:false,reason:"fantasy-timestamp-required"})}const state=initialState(read.ctx,timestamp),write=writeState(read.ctx,state,"protagonist-needs-initialize");if(!write.ok){bump("rejections");return write}bump("initializations");return freeze({...write,created:true,snapshot:snapshot(seedValue,identityValue)})}
function applyDrift(stateValue,deltaSeconds,rateValue){const state=clone(stateValue),rates=rateValue;for(const key of NEED_KEYS){const total=Number(state.driftRemainder[key]||0)+Number(rates[key])*deltaSeconds,increment=Math.floor(total/60),next=Math.min(PRESSURE_MAX,Number(state.pressureMilli[key])+increment);state.pressureMilli[key]=next;state.driftRemainder[key]=next>=PRESSURE_MAX?0:total%60}return state}
function ensure(seedValue,identityValue,targetTimestamp,optionsValue){let read=readState(seedValue,identityValue);if(!read.compatible)return {ok:false,reason:read.reason,read};if(!read.exists){const start=resolveStartTimestamp(optionsValue,targetTimestamp),init=initialize(seedValue,identityValue,start);if(!init.ok)return {ok:false,reason:init.reason,read};read=readState(seedValue,identityValue)}return {ok:true,read}}
function advance(seedValue,identityValue,targetTimestampValue,optionsValue){const target=targetTimestampValue||currentTimestamp();if(!validTimestamp(target)){bump("rejections");return freeze({ok:false,reason:"fantasy-timestamp-required"})}const ensured=ensure(seedValue,identityValue,target,optionsValue);if(!ensured.ok){bump("rejections");return freeze({ok:false,reason:ensured.reason})}const read=ensured.read,state=clone(read.state),targetIndex=secondIndex(target);if(targetIndex<state.lastSecondIndex){bump("rejections");return freeze({ok:false,reason:"cannot-rewind-needs-state",snapshot:snapshotFromRead(read)})}if(targetIndex===state.lastSecondIndex)return freeze({ok:true,reason:"no-op",advancedSeconds:0,snapshot:snapshotFromRead(read)});const deltaSeconds=targetIndex-state.lastSecondIndex,rates=driftRates(read.ctx.seed,read.ctx.identityKey),next=applyDrift(state,deltaSeconds,rates);next.lastFantasyTimestamp=target;next.lastSecondIndex=targetIndex;next.revision+=1;const write=writeState(read.ctx,next,"protagonist-needs-advance");if(!write.ok){bump("rejections");return write}bump("advances");return freeze({...write,advancedSeconds:deltaSeconds,snapshot:snapshot(seedValue,identityValue)})}
function effectFor(kind){return EVENT_EFFECTS[String(kind||"").trim()]||null}
function applyEvent(seedValue,identityValue,eventValue,optionsValue){const event=eventValue&&typeof eventValue==="object"?eventValue:{},eventId=cleanId(event.eventId||event.id),timestamp=String(event.fantasyTimestamp||event.timestamp||""),kind=String(event.kind||"").trim(),effect=effectFor(kind);if(event.authoritative!==true||event.authority!=="simulation"){bump("rejections");return freeze({ok:false,reason:"simulation-authority-required"})}if(!eventId||!validTimestamp(timestamp)||!effect){bump("rejections");return freeze({ok:false,reason:!eventId?"event-id-required":(!validTimestamp(timestamp)?"fantasy-timestamp-required":"unsupported-condition-event")})}const ensured=ensure(seedValue,identityValue,timestamp,optionsValue);if(!ensured.ok){bump("rejections");return freeze({ok:false,reason:ensured.reason})}const read=ensured.read;if(read.state.appliedEventIds.includes(eventId)){bump("duplicates");return freeze({ok:true,reason:"duplicate",duplicate:true,eventId,snapshot:snapshotFromRead(read)})}const eventIndex=secondIndex(timestamp);if(eventIndex<read.state.lastSecondIndex){bump("rejections");return freeze({ok:false,reason:"event-before-current-state",eventId,snapshot:snapshotFromRead(read)})}let next=clone(read.state);if(eventIndex>next.lastSecondIndex)next=applyDrift(next,eventIndex-next.lastSecondIndex,driftRates(read.ctx.seed,read.ctx.identityKey));next.lastFantasyTimestamp=timestamp;next.lastSecondIndex=eventIndex;for(const [key,delta] of Object.entries(effect))next.pressureMilli[key]=Math.max(0,Math.min(PRESSURE_MAX,Number(next.pressureMilli[key])+Number(delta)));next.appliedEventIds=[...next.appliedEventIds,eventId].slice(-MAX_EVENT_IDS);next.sourceEventCount+=1;next.revision+=1;const write=writeState(read.ctx,next,"protagonist-needs-event:"+kind+":"+eventId);if(!write.ok){bump("rejections");return write}bump("events");return freeze({...write,eventId,eventKind:kind,duplicate:false,snapshot:snapshot(seedValue,identityValue)})}
function displayPressure(milli){return Math.round(Number(milli)/100)/10}
function snapshotFromRead(read){if(!read?.compatible||!read?.exists||!read.state)return freeze({version:VERSION,schema:SCHEMA,schemaVersion:SCHEMA_VERSION,compatible:Boolean(read?.compatible),exists:false,reason:read?.reason||"empty",bounded:true,fullWorldScan:false,perFrameScan:false,actionExecution:false});const state=read.state,rates=driftRates(read.ctx.seed,read.ctx.identityKey),pressures={},urgent=[];let dominantNeed=NEED_KEYS[0];for(const key of NEED_KEYS){pressures[key]=displayPressure(state.pressureMilli[key]);if(state.pressureMilli[key]>state.pressureMilli[dominantNeed])dominantNeed=key;if(state.pressureMilli[key]>=URGENT_THRESHOLD)urgent.push(key)}const serializedBytes=utf8Bytes(stableStringify(state));return freeze({version:VERSION,schema:SCHEMA,schemaVersion:SCHEMA_VERSION,compatible:true,exists:true,seed:read.ctx.seed,protagonistId:read.ctx.protagonistId,identityKey:read.ctx.identityKey,lastFantasyTimestamp:state.lastFantasyTimestamp,lastSecondIndex:state.lastSecondIndex,revision:state.revision,sourceEventCount:state.sourceEventCount,pressures:freeze(pressures),pressureMilli:freeze(clone(state.pressureMilli)),driftRemainder:freeze(clone(state.driftRemainder)),ratesMilliPerMinute:rates,dominantNeed,urgentNeeds:freeze(urgent),appliedEventIds:freeze(clone(state.appliedEventIds)),serializedBytes,maxStateBytes:MAX_STATE_BYTES,maxEventIds:MAX_EVENT_IDS,semantics:"0 = satisfied/stable; 100 = severe pressure",persistenceAuthority:"WorldState CampaignStateDelta",chronologyAuthority:"Fantasy Game Time + explicit Simulation events",bounded:true,eventDriven:true,fullWorldScan:false,wholeCampaignScan:false,perFrameScan:false,realTimeAuthority:false,presentationAuthority:false,actionExecution:false,inventoryAuthority:false,healthTreatmentAuthority:false,goalExecutionAuthority:false,rankAuthority:false})}
function snapshot(seedValue,identityValue){return snapshotFromRead(readState(seedValue,identityValue))}
function telemetry(){return freeze({...clone(telemetryState),boundedScalarCounters:true,authority:false,fullWorldScan:false,perFrameScan:false,maxStateBytes:MAX_STATE_BYTES,maxEventIds:MAX_EVENT_IDS})}

root().ProtagonistNeeds=Object.freeze({VERSION,SCHEMA,SCHEMA_VERSION,REGISTRY_KIND,REGISTRY_KEY,DEFAULT_IDENTITY_KEY,NEED_KEYS,MAX_EVENT_IDS,MAX_STATE_BYTES,PRESSURE_MAX,URGENT_THRESHOLD,EVENT_EFFECTS,initialize,advance,applyEvent,snapshot,telemetry,driftRates,pressureBaseline});
if(typeof module!=="undefined"&&module.exports)module.exports=root().ProtagonistNeeds;
})();