'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path');
global.window=global;global.TextEncoder=global.TextEncoder||require('util').TextEncoder;
function H(v){let h=2166136261>>>0;for(const ch of String(v??'')){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)>>>0}h^=h>>>16;h=Math.imul(h,2246822507);h^=h>>>13;return(h>>>0).toString(16).toUpperCase().padStart(8,'0')}
function C(v){return v==null||typeof v!=='object'?v:JSON.parse(JSON.stringify(v))}
function merge(a,b){const out=C(a||{});for(const[k,v]of Object.entries(b||{}))out[k]=v&&typeof v==='object'&&!Array.isArray(v)?merge(out[k],v):C(v);return out}
const stores=new Map();function fresh(seed){return{seed,sequence:0,entries:{}}}function ensure(seed){if(!stores.has(seed))stores.set(seed,fresh(seed));return stores.get(seed)}
global.WorldState={
 structuralRef(seed,kind,parent,key,initial){return{id:'STR|'+String(kind).toUpperCase()+'|'+H([seed,kind,parent,key].join('|')),kind,key:{initial:C(initial||{})}}},
 resolve(seed,ref){const s=ensure(seed),e=s.entries[ref.id];return{current:merge(ref.key?.initial||{},e?.changes||{}),delta:e||null}},
 applyDelta(seed,ref,changes,reason){const s=ensure(seed),p=s.entries[ref.id];s.sequence++;s.entries[ref.id]={revision:(p?.revision||0)+1,reason,changes:merge(p?.changes||{},changes)};return{ok:true,reason:'ok',entry:C(s.entries[ref.id])}},
 serializeState(seed){return C(ensure(seed))},restoreSerializedState(campaign,state){stores.set(String(campaign.seed),C(state));return{ok:true}}
};
global.ProtagonistProfile={derive(seed,key='protagonist'){return{protagonistId:'PROTAGONIST-'+H(seed+'|'+key+'|identity-v1')}}};
let now='1201-10-01 12:00:00';global.GameTime={getTimestampKey(){return now}};
const authorityPath=path.resolve(__dirname,'../world/protagonist-authority.js');delete require.cache[require.resolve(authorityPath)];const Authority=require(authorityPath);global.ProtagonistAuthority=Authority;
const seed='WP-S014-006-SEED',identity='protagonist';assert(Authority.initialize(seed,identity,now).ok);
assert(Authority.ROLE_DEFS.knight,'Knight must be a fixed ProtagonistAuthority role');assert.deepStrictEqual(Authority.ROLE_DEFS.knight.scopes,['self','martial:personal-defense','local:protection-service']);assert.equal(Authority.ROLE_DEFS.knight.rankTier,1);
for(const forbidden of ['army','tax','realm','siege','estate','land'])assert(!Authority.ROLE_DEFS.knight.scopes.some(x=>x.includes(forbidden)),'Knight scope leaks later authority: '+forbidden);

let martialLevel=2,serviceStanding=12,reliabilityStanding=4,standingIds=['MER-SERVICE-1'],serviceResults=[
 {id:'SVR-1',contractId:'SVC-SQUIRE',dutyId:'attend-patron',resultState:'completed',simulationStatus:'terminal-success',fantasyTimestamp:'1201-09-15 09:00:00'},
 {id:'SVR-2',contractId:'SVC-SQUIRE',dutyId:'training-service',resultState:'completed',simulationStatus:'terminal-success',fantasyTimestamp:'1201-09-20 09:00:00'}
],oathRows=[{id:'OATH-SQUIRE',counterpartRef:{kind:'resident',id:'R01'},institutionRef:{kind:'workplace',id:'GUARD-POST'},state:'active',swornAt:'1201-09-01 08:00:00'}];
let roster=[{id:'R01',displayName:'Alda Reed',profession:'guard',workplaceId:'GUARD-POST'},{id:'R02',displayName:'Mira Vale',profession:'shopkeeper',workplaceId:'SHOP'}];
global.DailyActivity={build(){return C(roster)}};
global.ProtagonistSkills={qualificationCheck(_seed,req){assert.deepStrictEqual(req,[{skillId:'martial',minLevel:2}]);const row={skillId:'martial',minLevel:2,currentLevel:martialLevel,currentPoints:martialLevel*2500};return{qualified:martialLevel>=2,passed:martialLevel>=2?[row]:[],failed:martialLevel>=2?[]:[row],readOnly:true}}};
global.ProtagonistServiceContracts={snapshot(){return{compatible:true,contracts:[{id:'SVC-SQUIRE',roleType:'squire',state:'active',activatedAt:'1201-09-01 08:00:00',patronRef:{kind:'resident',id:'R01'},organizationRef:{kind:'workplace',id:'GUARD-POST'}}],results:C(serviceResults)}}};
global.ProtagonistStanding={summary(_seed,scope){assert.deepStrictEqual(scope,{kind:'local',id:'GUARD-POST'});return{ok:true,scope:C(scope),domains:{service:{score:serviceStanding,scopedDelta:serviceStanding},reliability:{score:reliabilityStanding,scopedDelta:reliabilityStanding}},sourceRecordIds:C(standingIds),readOnly:true}}};
global.ProtagonistOathAllegiance={snapshot(){return{compatible:true,oaths:C(oathRows)}}};
const terminal=new Map();function put(id,{targetId='R01',action='accept-knight-appointment',status='terminal-success',time='1201-10-01 11:59:00',auth=true}={}){const row=Object.freeze({attemptId:id,resultId:'IRX-'+H(id+'|'+status),targetKind:'person',targetId,action,updatedFantasyTimestamp:time,status,simulation:Object.freeze({delegate:'SimulationTest',authoritativeTerminalSuccess:status==='terminal-success'&&auth})});terminal.set(id,row);return row}
global.ProtagonistInteractionPipeline={claimCompletion(_seed,input){const row=terminal.get(input.attemptId);return row?.status==='terminal-success'&&row.simulation.authoritativeTerminalSuccess?{ok:true,interaction:row}:{ok:false,reason:'claimed-success-not-authoritative',interaction:row||null}}};

const modulePath=path.resolve(__dirname,'../world/protagonist-knight-appointment.js');delete require.cache[require.resolve(modulePath)];const Knight=require(modulePath);global.ProtagonistKnightAppointment=Knight;
assert.equal(Knight.VERSION,'protagonist-knight-appointment-v1');assert.deepStrictEqual(Knight.REQUIREMENTS,{martialMinLevel:2,minCompletedServiceResults:2,minServiceStanding:6,minReliabilityStanding:0});
let q=Knight.qualification(seed,now,{},identity);assert(q.qualified,JSON.stringify(q));assert.equal(q.status,'qualified');assert.equal(q.currentRoleId,'local-resident');assert.equal(q.martial.level,2);assert.equal(q.service.contractId,'SVC-SQUIRE');assert.deepStrictEqual(q.service.completedResultIds,['SVR-1','SVR-2']);assert.equal(q.oath.oathId,'OATH-SQUIRE');assert.equal(q.appointingActorRef.id,'R01');assert.equal(q.institutionRef.id,'GUARD-POST');assert.equal(Authority.snapshot(seed,identity).currentRole.roleId,'local-resident','qualification must not mutate authority');

martialLevel=1;q=Knight.qualification(seed,now,{},identity);assert(!q.qualified&&q.blockers.includes('martial-qualification-required'));martialLevel=2;
const goodResults=C(serviceResults);serviceResults=[serviceResults[0]];q=Knight.qualification(seed,now,{},identity);assert(!q.qualified&&q.blockers.includes('completed-squire-service-required'));serviceResults=goodResults;
serviceStanding=2;q=Knight.qualification(seed,now,{},identity);assert(!q.qualified&&q.blockers.includes('service-standing-required'));serviceStanding=12;
const goodOaths=C(oathRows);oathRows=[];q=Knight.qualification(seed,now,{},identity);assert(!q.qualified&&q.blockers.includes('formal-service-oath-required'));oathRows=[{...goodOaths[0],state:'breached',endedAt:'1201-09-25 08:00:00',endReason:'breached'}];q=Knight.qualification(seed,now,{},identity);assert(!q.qualified&&q.blockers.includes('formal-service-oath-breached'));oathRows=goodOaths;
const goodRoster=C(roster);roster=[{...roster[0],profession:'shopkeeper'},roster[1]];q=Knight.qualification(seed,now,{},identity);assert(!q.qualified&&q.blockers.includes('appointing-patron-authority-not-grounded'));roster=goodRoster;

put('IAX-KNIGHT-1');
const request={appointingActorId:'R01',institutionRef:{kind:'workplace',id:'GUARD-POST'},serviceContractId:'SVC-SQUIRE',interactionAttemptId:'IAX-KNIGHT-1'};
const options={authority:'simulation',authoritative:true,operationId:'KNIGHT-APPOINT-1',fantasyTimestamp:now};
for(const forged of ['ui','advisor','llm'])assert.equal(Knight.appointment(seed,request,{...options,authority:forged},identity).reason,'simulation-authority-required');
assert.equal(Knight.appointment(seed,{...request,appointingActorId:'R02'},options,identity).reason,'appointing-actor-not-authoritative-patron');
assert.equal(Knight.appointment(seed,{...request,institutionRef:{kind:'workplace',id:'SHOP'}},{...options,operationId:'KNIGHT-WRONG-INSTITUTION'},identity).reason,'appointing-institution-not-authoritative-service-institution');
put('IAX-WRONG-ACTION',{action:'talk'});assert.equal(Knight.appointment(seed,{...request,interactionAttemptId:'IAX-WRONG-ACTION'},{...options,operationId:'KNIGHT-WRONG-ACTION'},identity).reason,'knight-appointment-evidence-mismatch');
put('IAX-STALE',{time:'1201-10-01 10:00:00'});assert.equal(Knight.appointment(seed,{...request,interactionAttemptId:'IAX-STALE'},{...options,operationId:'KNIGHT-STALE'},identity).reason,'knight-appointment-evidence-stale');
const beforeHistory=Authority.snapshot(seed,identity).history.length,appointed=Knight.appointment(seed,request,options,identity);assert(appointed.ok,JSON.stringify(appointed));assert.equal(appointed.reason,'appointed-knight');assert.equal(appointed.rankStateOwnedBy,'ProtagonistAuthority');assert.equal(appointed.parallelRankState,false);assert.equal(appointed.appointment.targetRoleId,'knight');assert(/^KTR-[0-9A-F]{8}$/.test(appointed.appointment.authorityTransitionId));
const knightAuthority=Authority.snapshot(seed,identity);assert.equal(knightAuthority.currentRole.roleId,'knight');assert.deepStrictEqual(knightAuthority.currentRole.scopes,['self','martial:personal-defense','local:protection-service']);assert.equal(knightAuthority.history.length,beforeHistory+1);assert.equal(knightAuthority.history.at(-1).transitionId,appointed.appointment.authorityTransitionId);assert.deepStrictEqual(knightAuthority.history.at(-1).sourceRef,{kind:'workplace',id:'GUARD-POST'});
const dup=Knight.appointment(seed,request,options,identity);assert(dup.ok&&dup.duplicate&&dup.reason==='duplicate-knight-appointment');assert.equal(Authority.snapshot(seed,identity).history.length,beforeHistory+1,'duplicate must not create another role transition');
put('IAX-CONFLICT');const conflict=Knight.appointment(seed,{...request,interactionAttemptId:'IAX-CONFLICT'},options,identity);assert(!conflict.ok&&conflict.reason==='duplicate-knight-appointment-conflict');

const snap1=Knight.snapshot(seed,identity);assert.equal(snap1.appointmentCount,1);assert.equal(snap1.rankStateAuthority,'ProtagonistAuthority only');assert.equal(snap1.parallelRankState,false);assert.equal(snap1.directArmyControl,false);assert.equal(snap1.taxationAuthority,false);assert.equal(snap1.landOwnershipAuthority,false);assert.equal(snap1.lawmakingAuthority,false);assert.equal(snap1.nobleEstateAuthority,false);assert.equal(snap1.siegeAuthority,false);assert.equal(snap1.realmWarAuthority,false);assert(snap1.serializedBytes<=snap1.bounds.maxLedgerBytes);assert(!Object.prototype.hasOwnProperty.call(snap1.appointments[0],'scopes'));assert(!Object.prototype.hasOwnProperty.call(snap1.appointments[0],'rankTier'));
const saved=WorldState.serializeState(seed),authBeforeReload=C(Authority.snapshot(seed,identity)),auditBeforeReload=C(snap1);stores.set(seed,fresh(seed));assert.equal(Knight.snapshot(seed,identity).appointmentCount,0);WorldState.restoreSerializedState({seed},saved);assert.deepStrictEqual(Authority.snapshot(seed,identity).currentRole,authBeforeReload.currentRole);assert.deepStrictEqual(Authority.snapshot(seed,identity).history,authBeforeReload.history);assert.deepStrictEqual(Knight.snapshot(seed,identity).appointments,auditBeforeReload.appointments);

const replaySeed='WP-S014-006-REPLAY',replayWhen='1201-10-02 12:00:00';put('IAX-REPLAY',{time:'1201-10-02 11:59:00'});function replay(){now=replayWhen;assert(Authority.initialize(replaySeed,identity,replayWhen).ok);const r=Knight.appointment(replaySeed,{...request,interactionAttemptId:'IAX-REPLAY'},{...options,operationId:'KNIGHT-REPLAY',fantasyTimestamp:replayWhen},identity);assert(r.ok,JSON.stringify(r));return{appointment:C(r.appointment),transition:C(Authority.snapshot(replaySeed,identity).history.at(-1))}}const ra=replay();stores.set(replaySeed,fresh(replaySeed));const rb=replay();assert.deepStrictEqual(rb,ra,'same SEED + Fantasy Game Time + authoritative evidence must replay identically');
assert.equal(Knight.snapshot('OTHER-SEED',identity).appointmentCount,0);
const tele=Knight.telemetry();assert(tele.qualificationReads>0&&tele.authorityReads>0&&tele.skillReads>0&&tele.serviceReads>0&&tele.standingReads>0&&tele.oathReads>0&&tele.residentReads>0&&tele.evidenceReads>0&&tele.writes>0&&tele.appointments>0&&tele.duplicates>0&&tele.rejections>0);assert.equal(tele.fullWorldScan,false);assert.equal(tele.fullSettlementScan,false);assert.equal(tele.wholeHistoryScan,false);assert.equal(tele.perFrameScan,false);
const src=fs.readFileSync(modulePath,'utf8');for(const forbidden of ['Math.random','Date.now','new Date(','innerWidth','innerHeight','devicePixelRatio','navigator.','setPosition(','teleport(','army:','realm:request','settlement:administration','region:adjudication'])assert(!src.includes(forbidden),'forbidden authority/non-determinism: '+forbidden);for(const required of ['simulation-authority-required','completed-squire-service-required','formal-service-oath-required','service-standing-required','martial-qualification-required','rankStateAuthority:"ProtagonistAuthority only"','directArmyControl:false','taxationAuthority:false','realmWarAuthority:false','fullWorldScan:false','fullSettlementScan:false','wholeHistoryScan:false','perFrameScan:false'])assert(src.includes(required),'missing guard '+required);
const html=fs.readFileSync(path.resolve(__dirname,'../../index.html'),'utf8'),script='scripts/world/protagonist-knight-appointment.js?v=protagonist-knight-appointment-v1';assert(html.includes(script));assert(html.includes('scripts/world/protagonist-authority.js?v=protagonist-authority-v1-knight'));assert(html.indexOf(script)>html.indexOf('scripts/world/protagonist-oath-allegiance.js?v=protagonist-oath-allegiance-v1'));assert(html.indexOf(script)>html.indexOf('scripts/world/protagonist-service-contracts.js?v=protagonist-service-contracts-v1'));assert(html.indexOf(script)<html.indexOf('scripts/world/protagonist-guard-duty-selection.js?v=protagonist-guard-duty-selection-v2'));
console.log(JSON.stringify({pass:true,wp:'WP-S014-006',classification:'FUNCTIONAL',visual:'N/A',qualification:'martial + completed squire service + local standing + formal oath + grounded patron/institution',appointedRole:knightAuthority.currentRole.roleId,knightScopes:knightAuthority.currentRole.scopes,authorityHistoryIsRoleTruth:true,duplicateIdempotent:true,conflictingReplayRejected:true,saveReload:true,replayStable:true,bounds:snap1.bounds,guards:{parallelRankState:false,directArmyControl:false,taxationAuthority:false,landOwnershipAuthority:false,lawmakingAuthority:false,nobleEstateAuthority:false,siegeAuthority:false,realmWarAuthority:false,fullWorldScan:false,fullSettlementScan:false,wholeHistoryScan:false,perFrameScan:false}},null,2));
