'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path');
global.window=global;global.TextEncoder=global.TextEncoder||require('util').TextEncoder;
function H(v){let h=2166136261>>>0;for(const ch of String(v??'')){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)>>>0}h^=h>>>16;h=Math.imul(h,2246822507);h^=h>>>13;return(h>>>0).toString(16).toUpperCase().padStart(8,'0')}
function C(v){return v==null||typeof v!=='object'?v:JSON.parse(JSON.stringify(v))}
function merge(a,b){const o=C(a||{});for(const[k,v]of Object.entries(b||{}))o[k]=v&&typeof v==='object'&&!Array.isArray(v)?merge(o[k],v):C(v);return o}
const stores=new Map();const fresh=s=>({seed:s,sequence:0,entries:{}});function ensure(s){if(!stores.has(s))stores.set(s,fresh(s));return stores.get(s)}
global.WorldState={structuralRef(s,k,p,key,initial){return{id:'STR|'+String(k).toUpperCase()+'|'+H([s,k,p,key].join('|')),kind:k,key:{initial:C(initial||{})}}},resolve(s,r){const st=ensure(s),e=st.entries[r.id];return{current:merge(r.key?.initial||{},e?.changes||{}),delta:e||null}},applyDelta(s,r,changes,reason){const st=ensure(s),p=st.entries[r.id];st.sequence++;st.entries[r.id]={revision:(p?.revision||0)+1,reason,changes:merge(p?.changes||{},changes)};return{ok:true,reason:'ok',entry:C(st.entries[r.id])}},serializeState(s){return C(ensure(s))},restoreSerializedState(c,x){stores.set(String(c.seed),C(x));return{ok:true}}};
global.ProtagonistProfile={derive(s,k='protagonist'){return{protagonistId:'PROTAGONIST-'+H(s+'|'+k+'|identity-v1')}}};
let now='1201-10-01 12:00:00';global.GameTime={getTimestampKey(){return now}};
const authorityPath=path.resolve(__dirname,'../world/protagonist-authority.js');delete require.cache[require.resolve(authorityPath)];const Authority=require(authorityPath);global.ProtagonistAuthority=Authority;
const seed='WP-S014-006-SEED',identity='protagonist';assert(Authority.initialize(seed,identity,now).ok);
assert.equal(Object.keys(Authority.ROLE_DEFS).filter(x=>x==='knight').length,1);assert.deepStrictEqual(Authority.ROLE_DEFS.knight.scopes,['self','local:protection','local:escort','local:patrol']);assert.equal(Authority.ROLE_DEFS.knight.rankTier,2);for(const term of ['army','tax','realm','siege','estate','law','land'])assert(!Authority.ROLE_DEFS.knight.scopes.some(x=>x.includes(term)));

let martialLevel=4,serviceStanding=12,serviceDelta=10,standingIds=['MER-SERVICE-1'];
let serviceResults=[{id:'SVR-1',contractId:'SVC-SQUIRE',dutyId:'attend-patron',resultState:'completed',simulationStatus:'terminal-success',fantasyTimestamp:'1201-09-15 09:00:00'},{id:'SVR-2',contractId:'SVC-SQUIRE',dutyId:'training-service',resultState:'completed',simulationStatus:'terminal-success',fantasyTimestamp:'1201-09-20 09:00:00'}];
let serviceContracts=[{id:'SVC-SQUIRE',roleType:'squire',state:'active',activatedAt:'1201-09-01 08:00:00',patronRef:{kind:'resident',id:'R01'},organizationRef:{kind:'workplace',id:'GUARD-POST'}}];
let oathRows=[{id:'OATH-SQUIRE',counterpartRef:{kind:'resident',id:'R01'},institutionRef:{kind:'workplace',id:'GUARD-POST'},state:'active',swornAt:'1201-09-01 08:00:00'}];
let roster=[{id:'R01',displayName:'Alda Reed',profession:'guard',workplaceId:'GUARD-POST',workplaceLabel:'Village Guard Post'},{id:'R02',displayName:'Mira Vale',profession:'shopkeeper',workplaceId:'SHOP',workplaceLabel:'Village Shop'}];
global.DailyActivity={build(){return C(roster)}};
global.ProtagonistSkills={qualificationCheck(_s,req){assert.deepStrictEqual(req,[{skillId:'martial',minLevel:4}]);const row={skillId:'martial',minLevel:4,currentLevel:martialLevel,currentPoints:martialLevel*1800};return{qualified:martialLevel>=4,passed:martialLevel>=4?[row]:[],failed:martialLevel>=4?[]:[row],readOnly:true}}};
global.ProtagonistServiceContracts={snapshot(){return{compatible:true,contracts:C(serviceContracts),results:C(serviceResults)}}};
global.ProtagonistStanding={summary(_s,scope){assert.deepStrictEqual(scope,{kind:'local',id:'GUARD-POST'});return{ok:true,scope:C(scope),domains:{service:{score:serviceStanding,scopedDelta:serviceDelta},reliability:{score:3,scopedDelta:0}},sourceRecordIds:C(standingIds),readOnly:true}}};
global.ProtagonistOathAllegiance={snapshot(){return{compatible:true,oaths:C(oathRows)}}};
global.SocialState={dialogueContext(){throw new Error('Knight eligibility must be grounded by service/oath/standing, not generic guild social thresholds')}};
const terminal=new Map();function put(id,{targetId='R01',action='accept-knight-appointment',status='terminal-success',time='1201-10-01 11:59:00',auth=true}={}){const row=Object.freeze({attemptId:id,resultId:'IRX-'+H(id+'|'+status),actorId:'protagonist',targetKind:'person',targetId,action,updatedFantasyTimestamp:time,status,simulation:Object.freeze({delegate:'SimulationTest',authoritativeTerminalSuccess:status==='terminal-success'&&auth})});terminal.set(id,row);return row}
global.ProtagonistInteractionPipeline={claimCompletion(_s,input){const row=terminal.get(input.attemptId);return row?.status==='terminal-success'&&row.simulation.authoritativeTerminalSuccess?{ok:true,interaction:row}:{ok:false,reason:'claimed-success-not-authoritative',interaction:row||null}}};
const modulePath=path.resolve(__dirname,'../world/protagonist-appointment-resolution.js');delete require.cache[require.resolve(modulePath)];const Appointment=require(modulePath);global.ProtagonistAppointmentResolution=Appointment;
assert.equal(Appointment.VERSION,'protagonist-appointment-resolution-v1');assert.equal(Appointment.catalog().filter(x=>x.targetRoleId==='knight').length,1);assert.equal(Appointment.ROLE_CATALOG.knight.appointmentAction,'accept-knight-appointment');assert.equal(Appointment.ROLE_CATALOG.knight.requiredCompletedServiceResults,2);
let q=Appointment.eligibility(seed,'knight',now,identity);assert(q.eligible,JSON.stringify(q));assert.equal(q.status,'eligible');assert.deepStrictEqual(q.blockers,[]);assert.equal(q.martial.currentLevel,4);assert.equal(q.employment.contractId,'SVC-SQUIRE');assert.deepStrictEqual(q.employment.paymentIds,['SVR-1','SVR-2']);assert.equal(q.oath.oathId,'OATH-SQUIRE');assert.deepStrictEqual(q.standing.scope,{kind:'local',id:'GUARD-POST'});assert.equal(q.employment.employerRef.id,'R01');assert.equal(q.employment.workplaceRef.id,'GUARD-POST');assert.equal(Authority.snapshot(seed,identity).currentRole.roleId,'local-resident');

martialLevel=3;q=Appointment.eligibility(seed,'knight',now,identity);assert(!q.eligible&&q.blockers.includes('martial-skill-insufficient'));martialLevel=4;
const goodResults=C(serviceResults);serviceResults=[serviceResults[0]];q=Appointment.eligibility(seed,'knight',now,identity);assert(!q.eligible&&q.blockers.includes('completed-squire-service-required'));serviceResults=goodResults;
serviceStanding=4;q=Appointment.eligibility(seed,'knight',now,identity);assert(!q.eligible&&q.blockers.includes('service-standing-insufficient'));serviceStanding=12;
serviceDelta=0;q=Appointment.eligibility(seed,'knight',now,identity);assert(!q.eligible&&q.blockers.includes('service-standing-insufficient'));serviceDelta=10;
const goodOaths=C(oathRows);oathRows=[];q=Appointment.eligibility(seed,'knight',now,identity);assert(!q.eligible&&q.blockers.includes('formal-service-oath-required'));oathRows=[{...goodOaths[0],state:'breached',endedAt:'1201-09-25 08:00:00',endReason:'breached'}];q=Appointment.eligibility(seed,'knight',now,identity);assert(!q.eligible&&q.blockers.includes('formal-service-oath-breached'));oathRows=goodOaths;
const goodRoster=C(roster);roster=[{...roster[0],profession:'shopkeeper'},roster[1]];q=Appointment.eligibility(seed,'knight',now,identity);assert(!q.eligible&&q.blockers.includes('grounded-squire-patron-authority-required'));roster=goodRoster;
const goodContracts=C(serviceContracts);serviceContracts=[{...serviceContracts[0],patronRef:{kind:'resident',id:'R02'}}];q=Appointment.eligibility(seed,'knight',now,identity);assert(!q.eligible&&q.blockers.includes('grounded-squire-patron-authority-required'));serviceContracts=goodContracts;

put('IAX-KNIGHT-1');const request={appointingActorId:'R01',institutionRef:{kind:'workplace',id:'GUARD-POST'},interactionAttemptId:'IAX-KNIGHT-1'},options={authority:'simulation',authoritative:true,operationId:'KNIGHT-APPOINT-1',fantasyTimestamp:now};
for(const source of ['ui','advisor','llm'])assert.equal(Appointment.appointment(seed,'knight',request,{...options,authority:source},identity).reason,'simulation-authority-required');
assert.equal(Appointment.appointment(seed,'knight',{...request,appointingActorId:'R02'},{...options,operationId:'KNIGHT-BAD-ACTOR'},identity).reason,'appointing-actor-not-authoritative-employer');
assert.equal(Appointment.appointment(seed,'knight',{...request,institutionRef:{kind:'workplace',id:'SHOP'}},{...options,operationId:'KNIGHT-BAD-INSTITUTION'},identity).reason,'appointing-institution-not-authoritative-workplace');
put('IAX-WRONG',{action:'accept-appointment'});assert.equal(Appointment.appointment(seed,'knight',{...request,interactionAttemptId:'IAX-WRONG'},{...options,operationId:'KNIGHT-WRONG-ACTION'},identity).reason,'appointment-evidence-mismatch');
put('IAX-STALE',{time:'1201-10-01 10:00:00'});assert.equal(Appointment.appointment(seed,'knight',{...request,interactionAttemptId:'IAX-STALE'},{...options,operationId:'KNIGHT-STALE'},identity).reason,'appointment-evidence-stale');
const beforeHistory=Authority.snapshot(seed,identity).history.length,appointed=Appointment.appointment(seed,'knight',request,options,identity);assert(appointed.ok,JSON.stringify(appointed));assert.equal(appointed.reason,'appointed');assert.equal(appointed.rankStateOwnedBy,'ProtagonistAuthority');assert.equal(appointed.resolverRankState,false);assert.equal(appointed.resolution.targetRoleId,'knight');assert(appointed.resolution.qualificationSignature);assert(appointed.resolution.evidenceRefs.some(x=>x.kind==='skill'&&x.id==='martial'));assert(appointed.resolution.evidenceRefs.some(x=>x.kind==='service-contract'&&x.id==='SVC-SQUIRE'));assert(appointed.resolution.evidenceRefs.filter(x=>x.kind==='service-result').length>=2);assert(appointed.resolution.evidenceRefs.some(x=>x.kind==='formal-oath'&&x.id==='OATH-SQUIRE'));assert(appointed.resolution.evidenceRefs.some(x=>x.kind==='standing-record'&&x.id==='MER-SERVICE-1'));
const knight=Authority.snapshot(seed,identity);assert.equal(knight.currentRole.roleId,'knight');assert.equal(knight.currentRole.rankTier,2);assert.deepStrictEqual(knight.currentRole.scopes,['self','local:protection','local:escort','local:patrol']);assert.equal(knight.history.length,beforeHistory+1);assert.equal(knight.history.at(-1).transitionId,appointed.resolution.authorityTransitionId);assert.deepStrictEqual(knight.history.at(-1).sourceRef,{kind:'workplace',id:'GUARD-POST'});
const dup=Appointment.appointment(seed,'knight',request,options,identity);assert(dup.ok&&dup.duplicate&&dup.reason==='duplicate-appointment');assert.equal(Authority.snapshot(seed,identity).history.length,beforeHistory+1);
put('IAX-CONFLICT');const conflict=Appointment.appointment(seed,'knight',{...request,interactionAttemptId:'IAX-CONFLICT'},options,identity);assert(!conflict.ok&&conflict.reason==='duplicate-appointment-conflict');

const snap1=Appointment.snapshot(seed,identity);assert.equal(snap1.resolutionCount,1);assert.equal(snap1.rankStateAuthority,'ProtagonistAuthority only');assert.equal(snap1.parallelRankState,false);assert.equal(snap1.fullWorldScan,false);assert.equal(snap1.fullSettlementScan,false);assert.equal(snap1.wholeHistoryScan,false);assert.equal(snap1.perFrameScan,false);assert(snap1.serializedBytes<=snap1.bounds.maxLedgerBytes);
const saved=WorldState.serializeState(seed),roleBefore=C(Authority.snapshot(seed,identity)),auditBefore=C(snap1);stores.set(seed,fresh(seed));assert.equal(Appointment.snapshot(seed,identity).resolutionCount,0);WorldState.restoreSerializedState({seed},saved);assert.deepStrictEqual(Authority.snapshot(seed,identity).currentRole,roleBefore.currentRole);assert.deepStrictEqual(Authority.snapshot(seed,identity).history,roleBefore.history);assert.deepStrictEqual(Appointment.snapshot(seed,identity).resolutions,auditBefore.resolutions);

const replaySeed='WP-S014-006-REPLAY',replayWhen='1201-10-02 12:00:00';put('IAX-REPLAY',{time:'1201-10-02 11:59:00'});function replay(){now=replayWhen;assert(Authority.initialize(replaySeed,identity,replayWhen).ok);const r=Appointment.appointment(replaySeed,'knight',{...request,interactionAttemptId:'IAX-REPLAY'},{...options,operationId:'KNIGHT-REPLAY',fantasyTimestamp:replayWhen},identity);assert(r.ok,JSON.stringify(r));return{resolution:C(r.resolution),transition:C(Authority.snapshot(replaySeed,identity).history.at(-1))}}const ra=replay();stores.set(replaySeed,fresh(replaySeed));const rb=replay();assert.deepStrictEqual(rb,ra);
assert.equal(Appointment.snapshot('OTHER-SEED',identity).resolutionCount,0);
const src=fs.readFileSync(modulePath,'utf8');for(const forbidden of ['Math.random','Date.now','new Date(','innerWidth','innerHeight','devicePixelRatio','navigator.','setPosition(','teleport(','army:','settlement:administration','region:adjudication','realm:advise'])assert(!src.includes(forbidden),'forbidden authority/non-determinism: '+forbidden);for(const required of ['requiredCompletedServiceResults:2','completed-squire-service-required','formal-service-oath-required','service-standing-insufficient','martial-skill-insufficient','rankStateAuthority:"ProtagonistAuthority only"','parallelRankState:false','fullWorldScan:false','fullSettlementScan:false','wholeHistoryScan:false','perFrameScan:false'])assert(src.includes(required),'missing guard '+required);
const html=fs.readFileSync(path.resolve(__dirname,'../../index.html'),'utf8');assert(html.includes('scripts/world/protagonist-authority.js?v=protagonist-authority-v1-knight'));assert(html.includes('scripts/world/protagonist-appointment-resolution.js?v=protagonist-appointment-resolution-v1-knight'));assert(!html.includes('protagonist-knight-appointment.js'),'parallel Knight appointment module must be removed');
console.log(JSON.stringify({pass:true,wp:'WP-S014-006',classification:'FUNCTIONAL',visual:'N/A',qualification:'martial level 4 + two terminal completed squire duties + exact local service standing + matching formal oath + grounded guard patron/workplace',appointedRole:knight.currentRole.roleId,knightScopes:knight.currentRole.scopes,authorityHistorySoleRoleTruth:true,auditEvidenceRefs:appointed.resolution.evidenceRefs,duplicateIdempotent:true,conflictingReplayRejected:true,saveReload:true,replayStable:true,bounds:snap1.bounds,guards:{parallelRankState:false,noArmyAuthority:true,noTaxationAuthority:true,noLandAuthority:true,noLawmakingAuthority:true,noSiegeAuthority:true,noRealmWarAuthority:true,fullWorldScan:false,fullSettlementScan:false,wholeHistoryScan:false,perFrameScan:false}},null,2));
