const assert=require('assert'),fs=require('fs'),path=require('path');global.window=global;global.TextEncoder=global.TextEncoder||require('util').TextEncoder;
const C=v=>v==null||typeof v!=='object'?v:Array.isArray(v)?v.map(C):Object.fromEntries(Object.entries(v).map(([k,x])=>[k,C(x)]));
function merge(a,b){const o=C(a||{});for(const[k,v]of Object.entries(b||{}))o[k]=v&&typeof v==='object'&&!Array.isArray(v)?merge(o[k],v):C(v);return o}
function H(s){let h=2166136261>>>0;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)>>>0}return(h>>>0).toString(16).toUpperCase().padStart(8,'0')}
const stores=new Map(),fresh=s=>({seed:s,sequence:0,entries:{}}),ensure=s=>(stores.has(s)||stores.set(s,fresh(s)),stores.get(s));
global.WorldState={structuralRef(s,k,p,key,initial){return{id:'STR|'+k.toUpperCase()+'|'+H([s,k,p,key].join('|')),kind:k,key:{initial:C(initial||{})}}},resolve(s,r){const st=ensure(s),e=st.entries[r.id];return{current:merge(r.key.initial,e?.changes||{}),delta:e||null}},applyDelta(s,r,changes,reason){const st=ensure(s),p=st.entries[r.id];st.sequence++;st.entries[r.id]={revision:(p?.revision||0)+1,reason,changes:merge(p?.changes||{},changes)};return{ok:true,reason:'ok',entry:C(st.entries[r.id])}},serializeState(s){return C(ensure(s))},restoreSerializedState(c,x){stores.set(String(c.seed),C(x));return{ok:true}}};
const seed='WP-S009-004-A',other='WP-S009-004-B';global.ProtagonistProfile={derive(s,k='protagonist'){return{protagonistId:'PROTAGONIST-'+H(s+'|'+k+'|identity-v1')}}};let now='1201-03-02 09:00:00';global.GameTime={getTimestampKey(){return now}};
const I=require(path.resolve(__dirname,'../world/protagonist-inventory.js')),sim=(operationId,x={})=>({authority:'simulation',authoritative:true,operationId,fantasyTimestamp:now,...x});
const ration={kind:'commodity',id:'RATION'},sword={kind:'unique-item',id:'SWORD-001'},bedroll={kind:'gear',id:'BEDROLL'};
let r=I.acquire(seed,{itemRef:ration,label:'travel ration',quantity:3},sim('A1'));assert(r.ok&&r.record.quantity===3);const stable=r.record.id;assert(/^POS-[0-9A-F]{8}$/.test(stable));
assert(I.acquire(seed,{itemRef:ration,quantity:3},sim('A1')).duplicate);assert.equal(I.get(seed,{itemRef:ration}).quantity,3);
now='1201-03-02 09:01:00';assert(I.acquire(seed,{itemRef:sword,label:'heirloom sword',unique:true},sim('A2')).ok);assert.equal(I.acquire(seed,{itemRef:sword,unique:true},sim('A3')).reason,'unique-item-already-owned');assert.equal(I.acquire(seed,{itemRef:{kind:'unique-item',id:'BAD'},unique:true,quantity:2},sim('A4')).reason,'unique-item-quantity-invalid');
now='1201-03-02 09:02:00';assert(I.acquire(seed,{itemRef:bedroll,label:'bedroll',carryState:'stored',metadata:{location:'home'}},sim('A5')).ok);const before=I.snapshot(seed);assert.equal(I.acquire(seed,{itemRef:{kind:'currency',id:'GOLD'},quantity:99},{authority:'ui',authoritative:true,operationId:'UI',fantasyTimestamp:now}).reason,'simulation-authority-required');assert.deepStrictEqual(I.snapshot(seed).records,before.records);
assert.equal(I.remove(seed,{itemRef:ration},sim('R0',{quantity:99})).reason,'insufficient-quantity');assert.equal(I.get(seed,{itemRef:ration}).quantity,3);now='1201-03-02 09:03:00';assert(I.remove(seed,{itemRef:ration},sim('R1',{quantity:1})).ok);assert.equal(I.get(seed,{itemRef:ration}).quantity,2);
now='1201-03-02 09:02:30';assert.equal(I.acquire(seed,{itemRef:ration,quantity:1},sim('A-OLD')).reason,'timestamp-before-current-state');assert.equal(I.get(seed,{itemRef:ration}).quantity,2,'stale acquire must not mutate quantity');
now='1201-03-02 09:04:00';r=I.update(seed,{itemRef:bedroll},{carryState:'carried',metadata:{location:'pack'}},sim('U1'));assert(r.ok&&r.record.carryState==='carried');assert.equal(I.update(seed,{itemRef:bedroll},{quantity:20},sim('U2')).reason,'ownership-fields-immutable-via-update');
assert(I.satisfies(seed,[{itemRef:ration,minQuantity:2,carried:true},{itemRef:sword,minQuantity:1,carried:true}]).ok);assert(!I.satisfies(seed,[{itemRef:{kind:'tool',id:'PICK'},minQuantity:1}]).ok);assert.deepStrictEqual(I.filterCandidateIds(seed,[{id:'eat',inventoryRequirements:[{itemRef:ration}]},{id:'mine',inventoryRequirements:[{itemRef:{kind:'tool',id:'PICK'}}]},{id:'wait',inventoryRequirements:[]}]).eligibleIds,['eat','wait']);assert(I.conversationSummary(seed).text.includes('travel ration'));assert(I.commandContext(seed).readOnly);
now='1201-03-02 09:05:00';r=I.transfer(seed,{itemRef:ration},sim('T1',{quantity:1,targetOwnerId:'NPC-1'}));assert(r.ok&&r.transfer.targetOwnerId==='NPC-1');assert.equal(I.get(seed,{itemRef:ration}).quantity,1);assert(I.transfer(seed,{itemRef:ration},sim('T1',{quantity:1,targetOwnerId:'NPC-1'})).duplicate);assert.equal(I.get(seed,{itemRef:ration}).quantity,1);
const saved=WorldState.serializeState(seed),pre=I.snapshot(seed);stores.set(seed,fresh(seed));assert.equal(I.snapshot(seed).recordCount,0);WorldState.restoreSerializedState({seed},saved);assert.deepStrictEqual(I.snapshot(seed).records,pre.records);assert.equal(I.get(seed,{itemRef:ration}).id,stable);
now='1201-03-02 09:06:00';assert(I.transfer(seed,{itemRef:sword},sim('T2',{targetOwnerId:'NPC-2'})).ok);assert.equal(I.get(seed,{itemRef:sword}),null);assert(I.acquire(other,{itemRef:{kind:'gear',id:'CLOAK'}},sim('B1')).ok);assert.equal(I.snapshot(other).recordCount,1);
let n=0;while(I.snapshot(seed).recordCount<I.MAX_ITEMS){now='1201-03-02 10:00:00';assert(I.acquire(seed,{itemRef:{kind:'fixture',id:'F'+n},unique:true},sim('F'+n)).ok);n++}assert.equal(I.acquire(seed,{itemRef:{kind:'fixture',id:'OVER'},unique:true},sim('OVER')).reason,'inventory-limit-reached');const snap=I.snapshot(seed);assert.equal(snap.recordCount,I.MAX_ITEMS);assert(snap.serializedBytes<=I.MAX_LEDGER_BYTES);assert(snap.operationIdCount<=I.MAX_OPERATION_IDS);assert.equal(I.list(seed,{limit:999}).length,I.MAX_QUERY_RESULTS);assert.equal(snap.persistenceAuthority,'WorldState CampaignStateDelta');assert.equal(snap.fullWorldScan,false);assert.equal(snap.perFrameScan,false);assert.equal(snap.directActionExecution,false);
global.innerWidth=320;global.navigator={userAgent:'a'};const pa=I.snapshot(seed);global.innerWidth=1920;global.navigator={userAgent:'b'};assert.deepStrictEqual(I.snapshot(seed).records,pa.records);
const root=path.resolve(__dirname,'../..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),script='scripts/world/protagonist-inventory.js?v=protagonist-inventory-v1';assert(html.includes(script));assert(html.indexOf(script)>html.indexOf('scripts/world/protagonist-profile.js?v=protagonist-profile-v1'));assert(html.indexOf(script)<html.indexOf('scripts/world/advisor-channel.js?v=advisor-chat-v1'));const src=fs.readFileSync(path.resolve(__dirname,'../world/protagonist-inventory.js'),'utf8');for(const x of['Math.random','Date.now','new Date(','innerWidth','navigator.'])assert(!src.includes(x));assert(src.includes('o.authority!=="simulation"'));assert(src.includes('fullWorldScan:false')&&src.includes('perFrameScan:false'));
console.log(JSON.stringify({wp:'WP-S009-004',classification:'FUNCTIONAL',visual:'N/A — authoritative inventory/ownership state adds no rendered surface',pass:true,stablePossessionIds:true,uniqueDuplicateRejected:true,overdrawRejected:true,transferValidated:true,forgedUiGrantRejected:true,saveReload:true,campaignIsolation:true,commandFiltering:true,recordCount:snap.recordCount,maxItems:I.MAX_ITEMS,serializedBytes:snap.serializedBytes,maxLedgerBytes:I.MAX_LEDGER_BYTES,operationIdCount:snap.operationIdCount,maxOperationIds:I.MAX_OPERATION_IDS,persistenceAuthority:snap.persistenceAuthority,fullWorldScan:snap.fullWorldScan,perFrameScan:snap.perFrameScan,directActionExecution:snap.directActionExecution},null,2));