'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'../..'),modulePath=path.join(root,'scripts/world/protagonist-economic-priority.js');
const source=fs.readFileSync(modulePath,'utf8'),index=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert(source.includes('VERSION="protagonist-economic-priority-v1"'));
for(const marker of ['MAX_CANDIDATES=12','MAX_MARKET_OFFERS=16','MAX_INVENTORY_ITEMS=24','MAX_WORK_OPPORTUNITIES=12','directPurchaseExecution:false','directCurrencyMutation:false','directInventoryMutation:false','directHousingMutation:false','directEmploymentMutation:false','simulationValidationBypass:false','wholeMarketScan:false','perFramePlanning:false'])assert(source.includes(marker),'missing '+marker);
for(const bad of ['Math.random(','Date.now(','new Date(','navigator.','devicePixelRatio','innerWidth','innerHeight','.debit(','.credit(','.acquire(','.remove(','.pay('])assert(!source.includes(bad),'forbidden direct/non-authoritative path '+bad);
const script='scripts/world/protagonist-economic-priority.js?v=protagonist-economic-priority-v1';
assert(index.includes(script),'canonical root must load ProtagonistEconomicPriority');
assert(index.indexOf(script)>index.indexOf('scripts/world/protagonist-housing.js?v=protagonist-housing-v1'));
assert(index.indexOf(script)<index.indexOf('scripts/world/conversation-transactions.js?v=conversation-transactions-v2'));

delete require.cache[require.resolve(modulePath)];
const Economic=require(modulePath);
const seed='AGENT6-WP-S012-007',when='1201-10-01 09:00:00';
const foodOffer={offerId:'OFFER-FOOD',category:'food',availabilityState:'available',unitPriceCopper:5,quantityAvailable:4,itemRef:{kind:'item',id:'ITEM-BREAD'}};
const toolOffer={offerId:'OFFER-TOOL',category:'basic',availabilityState:'available',unitPriceCopper:9,quantityAvailable:2,itemRef:{kind:'item',id:'ITEM-TOOL'}};
const luxuryOffer={offerId:'OFFER-LUX',category:'luxury',availabilityState:'available',unitPriceCopper:12,quantityAvailable:1,itemRef:{kind:'item',id:'ITEM-RIBBON'}};
const market={offers:[foodOffer,toolOffer,luxuryOffer]},workOps=[{opportunityId:'OPP-SMITH',open:true,prerequisites:{satisfied:true}}];
const food={id:'BUY-FOOD',kind:'purchase-essential',offerId:'OFFER-FOOD',priority:70,proposal:{proposalId:'PROP-FOOD',commandId:'advisor.propose_interaction',parameters:{interactionTargetId:'SHOP-COUNTER'},source:'economic-test'}};
const reserve={id:'RESERVE-RENT',kind:'reserve-obligation',obligationId:'HOB-RENT',priority:70};
const work={id:'SEEK-WORK',kind:'seek-paid-work',opportunityId:'OPP-SMITH',priority:60,proposal:{proposalId:'PROP-WORK',commandId:'advisor.propose_interaction',parameters:{interactionTargetId:'SMITH-NPC'},source:'economic-test'}};
const discretionary={id:'BUY-RIBBON',kind:'discretionary-purchase',offerId:'OFFER-LUX',priority:65,proposal:{proposalId:'PROP-RIBBON',commandId:'advisor.propose_interaction',parameters:{interactionTargetId:'SHOP-COUNTER'},source:'economic-test'}};
const goalTool={id:'BUY-GOAL-TOOL',kind:'goal-purchase',offerId:'OFFER-TOOL',priority:50,goalLinks:['GOAL-CRAFT'],proposal:{proposalId:'PROP-TOOL',commandId:'advisor.propose_interaction',parameters:{interactionTargetId:'SHOP-COUNTER'},source:'economic-test'}};
const neutralTool={id:'BUY-NEUTRAL-TOOL',kind:'goal-purchase',offerId:'OFFER-TOOL',priority:50,proposal:{proposalId:'PROP-TOOL-2',commandId:'advisor.propose_interaction',parameters:{interactionTargetId:'SHOP-COUNTER'},source:'economic-test'}};
const base={seed,when,market,workOpportunities:workOps,inventory:{records:[]},goals:{records:[]},authority:{scopes:['self']}};

const lowFood=Economic.evaluate({...base,needs:{pressureMilli:{hunger:90000}},housing:{obligation:{state:'none',amountCopper:0}},wealth:{balance:20},candidates:[reserve,work,food,discretionary]});
assert(lowFood.ok&&lowFood.status==='proposal-ready');assert.equal(lowFood.selectedCandidate.id,'BUY-FOOD');
const rent=Economic.evaluate({...base,needs:{pressureMilli:{hunger:20000}},housing:{obligation:{state:'due',obligationId:'HOB-RENT',amountCopper:12,priority:'medium'}},wealth:{balance:20},candidates:[food,reserve,work]});
assert.equal(rent.status,'reserve-funds');assert.equal(rent.reserveCopper,12);assert.equal(rent.selectedProposal,null);
const poor=Economic.evaluate({...base,needs:{pressureMilli:{hunger:65000}},housing:{obligation:{state:'none',amountCopper:0}},wealth:{balance:2},candidates:[food,work]});
assert.equal(poor.selectedCandidate.id,'SEEK-WORK');assert.equal(poor.evaluated.find(x=>x.id==='BUY-FOOD').reason,'insufficient-funds');
const defer=Economic.evaluate({...base,needs:{pressureMilli:{hunger:15000}},housing:{obligation:{state:'upcoming',obligationId:'HOB-RENT',amountCopper:8,priority:'low'}},wealth:{balance:12},candidates:[discretionary]});
assert.equal(defer.status,'deferred');assert.equal(defer.reason,'discretionary-spend-deferred-for-obligation');assert.equal(defer.selectedProposal,null);
const goals={records:[{id:'GOAL-CRAFT',status:'active',priority:90,topic:'Prepare tools for craft work'}]};
const goal=Economic.evaluate({...base,needs:{pressureMilli:{hunger:12000}},housing:{obligation:{state:'none',amountCopper:0}},wealth:{balance:20},goals,candidates:[neutralTool,goalTool]});
assert.equal(goal.selectedCandidate.id,'BUY-GOAL-TOOL');assert(goal.selectedCandidate.supportPriority>0);
const replayA=Economic.evaluate({...base,needs:{pressureMilli:{hunger:50000}},housing:{obligation:{state:'none',amountCopper:0}},wealth:{balance:20},candidates:[work,neutralTool]});
const replayB=Economic.evaluate({...base,needs:{pressureMilli:{hunger:50000}},housing:{obligation:{state:'none',amountCopper:0}},wealth:{balance:20},candidates:[neutralTool,work]});
assert.equal(replayA.selectionId,replayB.selectionId);assert.deepStrictEqual(replayA.selectedCandidate,replayB.selectedCandidate);assert.deepStrictEqual(replayA.selectedProposal,replayB.selectedProposal);
assert.equal(Economic.evaluate({...base,candidates:Array.from({length:Economic.MAX_CANDIDATES+1},(_,i)=>({...food,id:'F'+i}))}).reason,'candidate-limit-exceeded');
assert.equal(Economic.evaluate({...base,market:{offers:Array.from({length:Economic.MAX_MARKET_OFFERS+1},(_,i)=>({...foodOffer,offerId:'O'+i}))},candidates:[food]}).reason,'market-offer-read-limit-exceeded');

let reads={needs:0,housing:0,wealth:0,inventory:0,goals:0,authority:0,market:0,work:0};
global.ProtagonistNeeds={snapshot(){reads.needs++;return {pressureMilli:{hunger:90000}};}};
global.ProtagonistHousing={decisionContext(){reads.housing++;return {obligation:{state:'none',amountCopper:0}};}};
global.ProtagonistWealth={snapshot(){reads.wealth++;return {balance:20};}};
global.ProtagonistInventory={snapshot(){reads.inventory++;return {records:[]};}};
global.ProtagonistGoals={list(){reads.goals++;return [];}};
global.ProtagonistAuthority={decisionContext(){reads.authority++;return {scopes:['self']};}};
global.LocalMarket={snapshot(){reads.market++;return market;}};
global.ProtagonistProfessionOpportunities={list(){reads.work++;return workOps;}};
const live=Economic.fromLive(seed,when,{settlementPlan:{id:'SETTLEMENT-A'},candidates:[food]});
assert.equal(live.selectedCandidate.id,'BUY-FOOD');assert.deepStrictEqual(reads,{needs:1,housing:1,wealth:1,inventory:1,goals:1,authority:1,market:1,work:1});

let schedules=0,captured=null;const fakeRuntime={schedule(config){schedules++;captured=config;return {ok:true,reason:'scheduled',attempt:{attemptId:'PAX-ECON'}};}};
const snapshot={snapshotId:'SNAP-ECON',context:{seed,when},targets:{interactions:[{id:'SHOP-COUNTER'}]}},decisionContext={value:0.8,urgency:0.9,socialAcceptability:0.8};
const evalInput=Economic.evaluatorInput(lowFood,snapshot,decisionContext,{actorPosition:{x:'0',y:'0',level:0}});
assert(evalInput.ok&&evalInput.config.execute===false);
const scheduled=Economic.schedule(lowFood,snapshot,decisionContext,{runtime:fakeRuntime,actorPosition:{x:'0',y:'0',level:0}});
assert(scheduled.ok);assert.equal(schedules,1);assert.equal(captured.proposal.proposalId,'PROP-FOOD');assert.equal(scheduled.directActionExecution,false);assert.equal(scheduled.simulationValidationBypass,false);assert.equal(Economic.evaluatorInput(rent,null,null,{}).ok,false);
for(const key of ['directPurchaseExecution','directCurrencyMutation','directInventoryMutation','directHousingMutation','directEmploymentMutation','directWorldMutation','simulationValidationBypass','fullWorldScan','wholeMarketScan','wholeHistoryScan','perFramePlanning'])assert.equal(lowFood.authority[key],false,key);

console.log(JSON.stringify({wp:'WP-S012-007',classification:'FUNCTIONAL',visual:'N/A — autonomous economic priority selection and runtime handoff add no rendered surface',pass:true,cases:{lowFood:lowFood.selectedCandidate.id,rent:rent.status,insufficientFunds:poor.selectedCandidate.id,discretionary:defer.status,goalInfluenced:goal.selectedCandidate.id},deterministicReplay:true,liveReads:reads,runtimeBoundary:scheduled.boundary,bounds:lowFood.bounds,directPurchaseExecution:false,directCurrencyMutation:false,directInventoryMutation:false,directHousingMutation:false,directEmploymentMutation:false,simulationValidationBypass:false,fullWorldScan:false,wholeMarketScan:false,wholeHistoryScan:false,perFramePlanning:false},null,2));
