const assert=require('assert'),fs=require('fs'),path=require('path');global.window=global;
const clone=v=>v==null||typeof v!=='object'?v:Array.isArray(v)?v.map(clone):Object.fromEntries(Object.entries(v).map(([k,x])=>[k,clone(x)]));
let composeReads=0,resolveReads=0,mutations=0;
const plan={id:'SETTLEMENT-ALPHA',name:'Ashford',classId:'village',population:{planned:420},prosperity:{value:.56},tradeMarketTendency:.63,inputs:{local:{resources:{agriculture:.78,mineral:.44,timber:.61,water:.74}}},generation:{countryId:'COUNTRY-A',desiredCenter:{x:'1',y:'2'},role:'local'}};
const composition={id:'SBC-ALPHA',revision:'SBCF-ALPHA',settlementId:plan.id,selected:[
  {id:'general-shop',label:'Shop',category:'trade',count:1},
  {id:'inn-tavern',label:'Inn / Tavern',category:'trade',count:1},
  {id:'smithy',label:'Smithy',category:'production-storage',count:1}
]};
let aggregate={revision:4,lastSimulatedTimestamp:'1201-05-06 08:00:00',foodSupply:.82,productionOutput:.73,tradeActivity:.68,prosperity:.60,employmentPressure:.24,reconciliation:{lastAggregateTimestamp:'1201-05-06 08:00:00'}};
global.SettlementBuildingCatalog={compose(seed,p){composeReads++;assert.equal(p,plan);return composition;}};
global.WorldState={settlementRef(seed,p){assert.equal(p,plan);return{id:'SETREF-'+p.id}},resolve(seed,ref){resolveReads++;return{current:{state:{aggregate:clone(aggregate)}}}},applyDelta(){mutations++;throw new Error('LocalMarket must not mutate WorldState')}};
const M=require(path.resolve(__dirname,'../world/local-market.js')),seed='WP-S012-002-A',when='1201-05-06 10:00:00';
composeReads=0;resolveReads=0;const a=M.snapshot(seed,when,plan);assert(a.ok);assert.equal(composeReads,1);assert.equal(resolveReads,1);assert.equal(mutations,0);assert(a.providerCount<=M.MAX_PROVIDERS);assert(a.offerCount<=M.MAX_OFFERS);assert(a.offerCount>=5);assert(a.offers.some(x=>x.category==='food'));assert(a.offers.some(x=>x.category==='basic-good'));assert(a.offers.some(x=>x.category==='service'));assert(a.offers.every(x=>/^OFFER-[0-9A-F]{8}$/.test(x.offerId)));assert(a.offers.every(x=>x.providerRef.kind==='settlement-function'&&/^SFP-[0-9A-F]{8}$/.test(x.providerRef.id)));assert(a.offers.every(x=>x.availabilityState==='available'||x.availabilityState==='unavailable'));assert(a.offers.every(x=>x.unitPriceCopper>=1&&Number.isInteger(x.unitPriceCopper)));assert(a.offers.every(x=>Number.isInteger(x.quantityAvailable)&&x.quantityAvailable>=0));assert.equal(a.aggregate.stale,false);assert.equal(a.authority.readOnly,true);assert.equal(a.authority.fullWorldScan,false);assert.equal(a.authority.wholeSettlementScan,false);assert.equal(a.authority.perFrameScan,false);assert.equal(a.authority.currencyMutation,false);assert.equal(a.authority.inventoryMutation,false);assert.equal(a.authority.marketMutation,false);assert.equal(a.authority.sellerNpcFabrication,false);
const replay=M.snapshot(seed,when,plan);assert.deepStrictEqual(replay,a,'same SEED/time/context must replay exactly');
const alt=M.snapshot('WP-S012-002-B',when,plan);assert(alt.offers.some((x,i)=>x.providerRef.id!==a.offers[i]?.providerRef.id||x.unitPriceCopper!==a.offers[i]?.unitPriceCopper),'alternate SEED should alter stable provider identity or price tendency');
aggregate={revision:5,lastSimulatedTimestamp:'1201-05-06 09:00:00',foodSupply:0,productionOutput:.73,tradeActivity:.68,prosperity:.60,employmentPressure:.24};const scarce=M.snapshot(seed,when,plan);const scarceFood=scarce.offers.filter(x=>x.category==='food');assert(scarceFood.length>0);assert(scarceFood.some(x=>x.availabilityState==='unavailable'&&x.quantityAvailable===0),'zero food supply should expose zero-stock unavailable offers');assert.equal(mutations,0);
aggregate={revision:6,lastSimulatedTimestamp:'1201-05-01 09:00:00',foodSupply:.9,productionOutput:.9,tradeActivity:.9,prosperity:.7,employmentPressure:.1};const stale=M.snapshot(seed,when,plan);assert.equal(stale.aggregate.stale,true);assert(stale.offers.every(x=>x.availabilityState==='unknown'));assert(stale.offers.every(x=>x.unitPriceCopper===null&&x.quantityAvailable===null));assert(stale.offers.every(x=>x.lastKnownUnitPriceCopper>=1&&x.lastKnownQuantity>=0));
aggregate=null;const foundation=M.snapshot(seed,when,plan);assert(foundation.ok);assert.equal(foundation.aggregate,null);assert(foundation.offers.every(x=>x.freshness==='foundation'));assert(foundation.offers.every(x=>x.availabilityState!=='unknown'));
aggregate={revision:7,lastSimulatedTimestamp:'1201-05-06 09:30:00',foodSupply:.8,productionOutput:.7,tradeActivity:.7,prosperity:.6,employmentPressure:.2};const current=M.snapshot(seed,when,plan);const first=current.offers[0];assert.deepStrictEqual(M.get(seed,when,plan,first.offerId),first);assert(M.list(seed,when,plan,{limit:999}).length<=M.MAX_QUERY_RESULTS);assert(M.list(seed,when,plan,{category:'service'}).every(x=>x.category==='service'));const summary=M.summary(seed,when,plan);assert(summary.ok&&summary.grounded&&summary.readOnly);assert.equal(mutations,0);
const mismatched=M.snapshot(seed,when,{...plan,id:'OTHER'},{composition});assert.equal(mismatched.ok,false);assert.equal(mismatched.reason,'settlement-composition-unavailable');
const future=M.snapshot(seed,'1201-05-06 08:00:00',plan,{aggregate:{sourceSystem:'RegionalSettlementSimulation',settlementId:plan.id,validated:true,fantasyTimestamp:'1201-05-06 09:00:00',values:{foodSupply:.8,productionOutput:.8,tradeActivity:.8,prosperity:.6,employmentPressure:.2}}});assert(future.aggregate.future&&future.aggregate.stale);assert(future.offers.every(x=>x.availabilityState==='unknown'));
const root=path.resolve(__dirname,'../..'),index=fs.readFileSync(path.join(root,'index.html'),'utf8'),script='scripts/world/local-market.js?v=local-market-v1';assert(index.includes(script));assert(index.indexOf(script)>index.indexOf('scripts/world/regional-settlement-simulation.js?v=campaign-persistence-v1'));assert(index.indexOf(script)<index.indexOf('scripts/world/protagonist-profile.js?v=protagonist-profile-v1'));
const moduleSrc=fs.readFileSync(path.resolve(__dirname,'../world/local-market.js'),'utf8');for(const forbidden of ['Math.random','Date.now','new Date(','innerWidth','innerHeight','devicePixelRatio','navigator.','WorldState.applyDelta','RegionalSettlementSimulation.apply','ProtagonistWealth.','ProtagonistInventory.'])assert(!moduleSrc.includes(forbidden),'forbidden mutation/non-authoritative input: '+forbidden);for(const marker of ['fullWorldScan:false','wholeSettlementScan:false','perFrameScan:false','currencyMutation:false','inventoryMutation:false','marketMutation:false','sellerNpcFabrication:false'])assert(moduleSrc.includes(marker),'missing authority marker '+marker);
console.log(JSON.stringify({wp:'WP-S012-002',classification:'FUNCTIONAL',visual:'N/A — read-only local market query adds no rendered surface',pass:true,settlementId:a.settlementId,providers:a.providerCount,offers:a.offerCount,categories:[...new Set(a.offers.map(x=>x.category))],sameSeedReplay:true,alternateSeedVariation:true,zeroStockUnavailable:true,staleUnknown:true,foundationFallback:true,boundedQueries:true,maxProviders:M.MAX_PROVIDERS,maxOffers:M.MAX_OFFERS,maxQueryResults:M.MAX_QUERY_RESULTS,staleHours:M.STALE_HOURS,worldMutations:mutations,fullWorldScan:a.authority.fullWorldScan,wholeSettlementScan:a.authority.wholeSettlementScan,perFrameScan:a.authority.perFrameScan,currencyMutation:a.authority.currencyMutation,inventoryMutation:a.authority.inventoryMutation,marketMutation:a.authority.marketMutation,sellerNpcFabrication:a.authority.sellerNpcFabrication},null,2));
