const assert=require('assert'),fs=require('fs'),path=require('path');global.window=global;global.TextEncoder=global.TextEncoder||require('util').TextEncoder;
const C=v=>v==null||typeof v!=='object'?v:Array.isArray(v)?v.map(C):Object.fromEntries(Object.entries(v).map(([k,x])=>[k,C(x)]));
function merge(a,b){const o=C(a||{});for(const[k,v]of Object.entries(b||{}))o[k]=v&&typeof v==='object'&&!Array.isArray(v)?merge(o[k],v):C(v);return o}
function H(s){let h=2166136261>>>0;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)>>>0}h^=h>>>16;h=Math.imul(h,2246822507);h^=h>>>13;return(h>>>0).toString(16).toUpperCase().padStart(8,'0')}
const stores=new Map(),fresh=s=>({seed:s,sequence:0,entries:{}}),ensure=s=>(stores.has(s)||stores.set(s,fresh(s)),stores.get(s));
global.WorldState={structuralRef(s,k,p,key,initial){return{id:'STR|'+k.toUpperCase()+'|'+H([s,k,p,key].join('|')),kind:k,key:{initial:C(initial||{})}}},resolve(s,r){const st=ensure(s),e=st.entries[r.id];return{current:merge(r.key.initial,e?.changes||{}),delta:e||null}},applyDelta(s,r,changes,reason){const st=ensure(s),p=st.entries[r.id];st.sequence++;st.entries[r.id]={revision:(p?.revision||0)+1,reason,changes:merge(p?.changes||{},changes)};return{ok:true,reason:'ok',entry:C(st.entries[r.id])}},serializeState(s){return C(ensure(s))},restoreSerializedState(c,x){stores.set(String(c.seed),C(x));return{ok:true}}};
global.ProtagonistProfile={derive(s,k='protagonist'){return{protagonistId:'PROTAGONIST-'+H(s+'|'+k+'|identity-v1')}}};
let now='1201-08-01 07:00:00';global.GameTime={getTimestampKey(){return now}};
const payments=new Map();global.ProtagonistEmployment={recentPayments(s,{limit}){return Object.freeze((payments.get(s)||[]).slice(0,limit).map(C))}};
let socialWrites=0;global.SocialState={recordEvent(){socialWrites++;throw new Error('forbidden SocialState mutation')}};
global.ProtagonistAuthority={transition(){throw new Error('forbidden authority mutation')}};global.ProtagonistWealth={credit(){throw new Error('forbidden wealth mutation')},debit(){throw new Error('forbidden wealth mutation')}};
const Standing=require(path.resolve(__dirname,'../world/protagonist-standing.js')),seed='WP-S013-002-A',other='WP-S013-002-B',identity='protagonist',ref=(kind,id)=>({kind,id}),sim=(op,when=now,s=seed)=>({authority:'simulation',authoritative:true,campaignSeed:s,operationId:op,fantasyTimestamp:when});
assert(Standing.initialize(seed,identity,now).ok);const base=Standing.snapshot(seed,identity),foundation=C(base.foundation);assert(base.exists);assert.deepStrictEqual(Object.keys(foundation).sort(),Standing.DOMAINS.slice().sort());assert(Object.values(foundation).every(v=>Number.isInteger(v)&&v>=-4&&v<=4));
stores.set(seed,fresh(seed));assert(Standing.initialize(seed,identity,now).ok);assert.deepStrictEqual(Standing.snapshot(seed,identity).foundation,foundation);assert(Standing.initialize(other,identity,now).ok);assert(Object.keys(foundation).some(k=>Standing.snapshot(other,identity).foundation[k]!==foundation[k]));
payments.set(seed,[{id:'TXN-WAGE-1',reasonCode:'employment-wage',fantasyTimestamp:'1201-08-01 08:00:00',sourceRef:{kind:'employment-contract',id:'EMP-SMITH'},transferRef:{kind:'simulation-work-result',id:'IRX-WORK-1'}}]);now='1201-08-01 08:00:00';let r=Standing.recordEmploymentMerit(seed,'TXN-WAGE-1',identity);assert(r.ok&&!r.duplicate);assert(/^MER-[0-9A-F]{8}$/.test(r.record.id));assert.equal(r.record.domain,'professional');assert.deepStrictEqual(r.record.scope,{kind:'local',id:'EMP-SMITH'});assert.equal(r.record.delta,6);assert.equal(r.record.sourceSystem,'ProtagonistEmployment');
const local=Standing.summary(seed,{kind:'local',id:'EMP-SMITH'},identity),region=Standing.summary(seed,{kind:'region',id:'REGION-1'},identity);assert.equal(local.domains.professional.scopedDelta,6);assert.equal(region.domains.professional.scopedDelta,0);assert.equal(region.recordCount,0);
assert(Standing.recordEmploymentMerit(seed,'TXN-WAGE-1',identity).duplicate);assert.equal(Standing.snapshot(seed,identity).recordCount,1);
payments.set(seed,[{id:'TXN-WAGE-1',reasonCode:'employment-wage',fantasyTimestamp:'1201-08-01 08:00:00',sourceRef:{kind:'employment-contract',id:'EMP-OTHER'},transferRef:{kind:'simulation-work-result',id:'IRX-WORK-1'}}]);assert.equal(Standing.recordEmploymentMerit(seed,'TXN-WAGE-1',identity).reason,'duplicate-source-conflict');payments.set(seed,[{id:'TXN-WAGE-1',reasonCode:'employment-wage',fantasyTimestamp:'1201-08-01 08:00:00',sourceRef:{kind:'employment-contract',id:'EMP-SMITH'},transferRef:{kind:'simulation-work-result',id:'IRX-WORK-1'}}]);assert.equal(Standing.recordEmploymentMerit(seed,'TXN-MISSING',identity).reason,'authoritative-employment-payment-required');
now='1201-08-01 09:00:00';const misconduct={type:'standing-recognition',validated:true,terminal:true,domain:'reliability',scope:{kind:'settlement',id:'STARTING-VILLAGE'},direction:'negative',impact:'major',outcome:'misconduct',reasonCode:'service-misconduct',sourceRef:ref('simulation-result','SIM-MISCONDUCT-1')};r=Standing.recordSimulation(seed,misconduct,sim('OP-MISCONDUCT'));assert(r.ok&&!r.duplicate);assert.equal(r.record.delta,-10);assert.equal(Standing.summary(seed,{kind:'settlement',id:'STARTING-VILLAGE'},identity).domains.reliability.scopedDelta,-10);
now='1201-08-01 10:00:00';const service={type:'standing-recognition',validated:true,terminal:true,domain:'service',scope:{kind:'settlement',id:'STARTING-VILLAGE'},direction:'positive',impact:'minor',outcome:'service-completed',reasonCode:'local-service',sourceRef:ref('simulation-result','SIM-SERVICE-1')};assert(Standing.recordSimulation(seed,service,sim('OP-SERVICE')).ok);assert.equal(Standing.summary(seed,{kind:'settlement',id:'STARTING-VILLAGE'},identity).domains.service.scopedDelta,3);assert.equal(Standing.summary(seed,{kind:'realm',id:'REALM-A'},identity).domains.service.scopedDelta,0);
assert.equal(Standing.recordSimulation(seed,service,{...sim('UI'),authority:'ui'}).reason,'simulation-authority-required');assert.equal(Standing.recordSimulation(seed,service,sim('CROSS',now,other)).reason,'campaign-seed-mismatch');assert.equal(Standing.recordSimulation(seed,{...service,terminal:false,sourceRef:ref('simulation-result','SIM-NONTERM')},sim('NONTERM')).reason,'validated-terminal-standing-evidence-required');assert.equal(Standing.recordSimulation(seed,{...service,direction:'positive',outcome:'misconduct',sourceRef:ref('simulation-result','SIM-DIR')},sim('DIR')).reason,'standing-outcome-direction-mismatch');
now='1201-08-01 08:30:00';const stale={...service,sourceRef:ref('simulation-result','SIM-STALE')};assert.equal(Standing.recordSimulation(seed,stale,sim('STALE',now)).reason,'cannot-rewind-standing-state');
const saved=WorldState.serializeState(seed),pre=Standing.snapshot(seed,identity);stores.set(seed,fresh(seed));assert.equal(Standing.snapshot(seed,identity).exists,false);WorldState.restoreSerializedState({seed},saved);assert.deepStrictEqual(Standing.snapshot(seed,identity).records,pre.records);assert.equal(Standing.snapshot(other,identity).recordCount,0);
const replaySeed='WP-S013-002-REPLAY';function replay(){now='1201-09-01 11:00:00';Standing.initialize(replaySeed,identity,now);const e={type:'standing-recognition',validated:true,terminal:true,domain:'civic',scope:{kind:'settlement',id:'VILLAGE-R'},direction:'positive',impact:'standard',outcome:'commendation',reasonCode:'civic-help',sourceRef:ref('simulation-result','SIM-R')};return C(Standing.recordSimulation(replaySeed,e,{authority:'simulation',authoritative:true,campaignSeed:replaySeed,operationId:'OP-R',fantasyTimestamp:now}).record)}const ra=replay();stores.set(replaySeed,fresh(replaySeed));assert.deepStrictEqual(replay(),ra);
now='1201-08-02 12:00:00';for(let i=0;i<70;i++){const neg=i%3===0,e={type:'standing-recognition',validated:true,terminal:true,domain:Standing.DOMAINS[i%Standing.DOMAINS.length],scope:{kind:'local',id:'FIXTURE-'+(i%5)},direction:neg?'negative':'positive',impact:'minor',outcome:neg?'failed':'success',reasonCode:'bounded-fixture',sourceRef:ref('simulation-result','SIM-FIX-'+i)};assert(Standing.recordSimulation(seed,e,sim('OP-FIX-'+i)).ok)}
const bounded=Standing.snapshot(seed,identity);assert.equal(bounded.recordCount,Standing.MAX_RECORDS);assert(bounded.recentSourceCount<=Standing.MAX_RECENT_SOURCES);assert(bounded.serializedBytes<=Standing.MAX_STATE_BYTES);assert.equal(Standing.list(seed,{limit:999},identity).length,Standing.MAX_QUERY_RESULTS);const dc=Standing.decisionContext(seed,{kind:'settlement',id:'STARTING-VILLAGE'},identity);assert(dc.readOnly&&!dc.relationshipAuthority&&!dc.rankAuthority&&!dc.legitimateAuthorityGrant&&!dc.directActionExecution&&!dc.worldMutation);assert.equal(socialWrites,0);
const tel=Standing.telemetry();assert(tel.reads>0&&tel.writes>0&&tel.records>0&&tel.duplicates>0&&tel.rejections>0&&tel.queries>0&&tel.employmentReads>0);assert(!tel.fullWorldScan&&!tel.wholeHistoryScan&&!tel.perFrameScan);
for(const flag of ['relationshipAuthority','wealthAuthority','employmentAuthority','skillsAuthority','rankAuthority','legitimateAuthorityGrant','uiRecognitionAuthority','dialogueRecognitionAuthority','llmRecognitionAuthority'])assert.equal(bounded[flag],false);assert.equal(bounded.persistenceAuthority,'WorldState CampaignStateDelta');assert.equal(bounded.scopeAuthority,'exact recorded scope only; no implicit local-to-regional propagation');
const src=fs.readFileSync(path.resolve(__dirname,'../world/protagonist-standing.js'),'utf8');for(const x of['Math.random','Date.now','new Date(','innerWidth','innerHeight','devicePixelRatio','navigator.','SocialState.recordEvent','ProtagonistAuthority.transition','ProtagonistWealth.credit','ProtagonistWealth.debit','ProtagonistEmployment.settle'])assert(!src.includes(x),'forbidden authority/non-determinism: '+x);for(const m of['options.authority!=="simulation"','duplicate-source-conflict','no implicit local-to-regional propagation','relationshipAuthority:false','rankAuthority:false','fullWorldScan:false','wholeHistoryScan:false','perFrameScan:false'])assert(src.includes(m),'missing marker '+m);
const repoRoot=path.resolve(__dirname,'../..'),html=fs.readFileSync(path.join(repoRoot,'index.html'),'utf8'),script='scripts/world/protagonist-standing.js?v=protagonist-standing-v1';assert(html.includes(script));assert(html.indexOf(script)>html.indexOf('scripts/world/protagonist-skills.js?v=protagonist-skills-v1'));assert(html.indexOf(script)<html.indexOf('scripts/world/protagonist-goals.js?v=protagonist-goals-v1'));
console.log(JSON.stringify({wp:'WP-S013-002',classification:'FUNCTIONAL',visual:'N/A — authoritative standing/merit ledger introduces no rendered surface',pass:true,version:Standing.VERSION,foundationDeterministic:true,alternateSeedDiverges:true,employmentMeritGrounded:true,localDoesNotPropagate:true,negativeStanding:true,positiveService:true,forgedUiRejected:true,crossCampaignRejected:true,nonterminalRejected:true,directionMismatchRejected:true,rewindRejected:true,duplicateIdempotence:true,duplicateConflictRejected:true,saveReload:true,campaignIsolation:true,replayStable:true,maxRecords:Standing.MAX_RECORDS,maxRecentSources:Standing.MAX_RECENT_SOURCES,maxQueryResults:Standing.MAX_QUERY_RESULTS,maxStateBytes:Standing.MAX_STATE_BYTES,serializedBytes:bounded.serializedBytes,persistenceAuthority:bounded.persistenceAuthority,scopeAuthority:bounded.scopeAuthority,fullWorldScan:bounded.fullWorldScan,wholeHistoryScan:bounded.wholeHistoryScan,perFrameScan:bounded.perFrameScan,relationshipAuthority:bounded.relationshipAuthority,rankAuthority:bounded.rankAuthority,legitimateAuthorityGrant:bounded.legitimateAuthorityGrant,telemetry:tel},null,2));