const assert=require('assert'),fs=require('fs'),path=require('path');global.window=global;global.TextEncoder=global.TextEncoder||require('util').TextEncoder;
const C=v=>v==null||typeof v!=='object'?v:Array.isArray(v)?v.map(C):Object.fromEntries(Object.entries(v).map(([k,x])=>[k,C(x)]));
function merge(a,b){const o=C(a||{});for(const[k,v]of Object.entries(b||{}))o[k]=v&&typeof v==='object'&&!Array.isArray(v)?merge(o[k],v):C(v);return o}
function H(s){let h=2166136261>>>0;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)>>>0}return(h>>>0).toString(16).toUpperCase().padStart(8,'0')}
const stores=new Map(),fresh=s=>({seed:s,sequence:0,entries:{}}),ensure=s=>(stores.has(s)||stores.set(s,fresh(s)),stores.get(s));
global.WorldState={structuralRef(s,k,p,keyName,initial){return{id:'STR|'+k.toUpperCase()+'|'+H([s,k,p,keyName].join('|')),kind:k,key:{initial:C(initial||{})}}},resolve(s,r){const st=ensure(s),e=st.entries[r.id];return{current:merge(r.key?.initial||{},e?.changes||{}),delta:e||null}},applyDelta(s,r,changes,reason){const st=ensure(s),p=st.entries[r.id];st.sequence++;st.entries[r.id]={revision:(p?.revision||0)+1,reason,changes:merge(p?.changes||{},changes)};return{ok:true,reason:'ok',entry:C(st.entries[r.id])}},serializeState(s){return C(ensure(s))},restoreSerializedState(c,x){stores.set(String(c.seed),C(x));return{ok:true}}};
global.ProtagonistProfile={derive(s,k='protagonist'){return{protagonistId:'PROTAGONIST-'+H(s+'|'+k+'|identity-v1')}}};
const plan={id:'SETTLEMENT-ECON',name:'Ashford',classId:'village',population:{planned:420},prosperity:{value:.56},tradeMarketTendency:.63,inputs:{local:{resources:{agriculture:.78,mineral:.44,timber:.61,water:.74}}}};
const composition={id:'SBC-ECON',revision:'SBCF-ECON',settlementId:plan.id,selected:[{id:'general-shop',label:'Shop',category:'trade',count:1},{id:'inn-tavern',label:'Inn',category:'trade',count:1},{id:'smithy',label:'Smithy',category:'production-storage',count:1}]};
const seed='WP-S012-004-A',other='WP-S012-004-B',baseTime='1201-05-06 10:00:00';
const LocalMarket=require(path.resolve(__dirname,'../world/local-market.js')),Inventory=require(path.resolve(__dirname,'../world/protagonist-inventory.js')),Wealth=require(path.resolve(__dirname,'../world/protagonist-wealth.js'));global.LocalMarket=LocalMarket;global.ProtagonistInventory=Inventory;global.ProtagonistWealth=Wealth;
const Tx=require(path.resolve(__dirname,'../world/economic-transaction.js'));
const marketOptions={composition},sim=(when,extra={})=>({authority:'simulation',authoritative:true,campaignSeed:seed,fantasyTimestamp:when,marketOptions,...extra});
function snap(when,opts={}){return LocalMarket.snapshot(seed,when,plan,{composition,...opts})}
function offer(when,id){return snap(when).offers.find(x=>x.offerId===id)}
function findOffer(when,pred,opts={}){const s=LocalMarket.snapshot(seed,when,plan,{composition,...opts});return s.offers.find(pred)}
function quote(when,kind,off,quantity=1,opts={}){return Tx.quote(seed,when,plan,{kind,offerId:off.offerId,providerRef:off.providerRef,quantity},{marketOptions:{composition,...opts}})}
function inputFrom(q,requestId){const x=q.quote;return{requestId,quoteId:x.quoteId,marketSnapshotId:x.marketSnapshotId,offerId:x.offerId,providerRef:x.providerRef,subjectRef:x.subjectRef,kind:x.kind,quantity:x.quantity,unitPriceCopper:x.unitPriceCopper,totalPriceCopper:x.totalPriceCopper}}
function exec(q,requestId,when,opts={}){return Tx.execute(seed,plan,inputFrom(q,requestId),sim(when,{marketOptions:{composition,...opts}}))}
let m=snap(baseTime);assert(m.ok);const ration=m.offers.find(x=>x.itemRef?.id==='TRAVEL-RATION'),lodging=m.offers.find(x=>x.serviceRef?.id==='LODGING-NIGHT'),iron=m.offers.find(x=>x.itemRef?.id==='IRON-HAND-TOOL'),rope=m.offers.find(x=>x.itemRef?.id==='ROPE-COIL');assert(ration&&lodging&&iron&&rope);
const qBuy=quote(baseTime,'buy',ration,2);assert(qBuy.ok&&qBuy.currentMarketRevalidated);const wb0=Wealth.snapshot(seed).balance;const buy=exec(qBuy,'REQ-BUY-1',baseTime);assert(buy.ok&&!buy.duplicate&&buy.kind==='buy');assert.equal(Wealth.snapshot(seed).balance,wb0-qBuy.quote.totalPriceCopper);assert.equal(Inventory.get(seed,{itemRef:ration.itemRef}).quantity,2);assert(/^EXC-/.test(buy.transactionId)&&/^TXN-/.test(buy.wealthTransactionId));
const invBeforeService=JSON.stringify(Inventory.snapshot(seed).records),qService=quote('1201-05-06 10:01:00','service',lodging,1);assert(qService.ok);const service=exec(qService,'REQ-SERVICE-1','1201-05-06 10:01:00');assert(service.ok&&/^SRV-/.test(service.serviceResultId));assert.equal(JSON.stringify(Inventory.snapshot(seed).records),invBeforeService);
const qSell=quote('1201-05-06 10:02:00','sell',ration,1);assert(qSell.ok&&qSell.quote.resaleBps>=5500&&qSell.quote.resaleBps<=7000);const beforeSell=Wealth.snapshot(seed).balance,sell=exec(qSell,'REQ-SELL-1','1201-05-06 10:02:00');assert(sell.ok);assert.equal(Wealth.snapshot(seed).balance,beforeSell+qSell.quote.totalPriceCopper);assert.equal(Inventory.get(seed,{itemRef:ration.itemRef}).quantity,1);
let bal=Wealth.snapshot(seed).balance;assert(bal>1);assert(Wealth.debit(seed,bal-1,{reasonCode:'test-drain',sourceRef:{kind:'test',id:'DRAIN'}},{authority:'simulation',authoritative:true,campaignSeed:seed,operationId:'TEST-DRAIN',fantasyTimestamp:'1201-05-06 10:03:00'}).ok);const qIron=quote('1201-05-06 10:04:00','buy',iron,1);assert(qIron.ok);const low=exec(qIron,'REQ-NO-FUNDS','1201-05-06 10:04:00');assert(!low.ok&&low.reason==='insufficient-funds');assert.equal(Tx.get(seed,'REQ-NO-FUNDS'),null);assert(Wealth.credit(seed,100,{reasonCode:'test-topup',sourceRef:{kind:'test',id:'TOPUP'}},{authority:'simulation',authoritative:true,campaignSeed:seed,operationId:'TEST-TOPUP',fantasyTimestamp:'1201-05-06 10:05:00'}).ok);
const zeroAgg={sourceSystem:'RegionalSettlementSimulation',settlementId:plan.id,validated:true,fantasyTimestamp:'1201-05-06 10:05:00',revision:7,values:{foodSupply:0,productionOutput:.7,tradeActivity:.7,prosperity:.6,employmentPressure:.2}};const zeroOffer=findOffer('1201-05-06 10:06:00',x=>x.itemRef?.id==='TRAVEL-RATION',{aggregate:zeroAgg});const zeroQuote=Tx.quote(seed,'1201-05-06 10:06:00',plan,{kind:'buy',offerId:zeroOffer.offerId,providerRef:zeroOffer.providerRef,quantity:1},{marketOptions:{composition,aggregate:zeroAgg}});assert(!zeroQuote.ok&&zeroQuote.reason==='offer-unavailable');
const staleAgg={...zeroAgg,fantasyTimestamp:'1201-05-01 10:00:00',values:{...zeroAgg.values,foodSupply:.9}};const staleOffer=findOffer('1201-05-06 10:07:00',x=>x.itemRef?.id==='TRAVEL-RATION',{aggregate:staleAgg});const staleQuote=Tx.quote(seed,'1201-05-06 10:07:00',plan,{kind:'buy',offerId:staleOffer.offerId,providerRef:staleOffer.providerRef,quantity:1},{marketOptions:{composition,aggregate:staleAgg}});assert(!staleQuote.ok&&staleQuote.reason==='offer-stale-or-unknown');
const qForge=quote('1201-05-06 10:08:00','buy',ration,1),forged=inputFrom(qForge,'REQ-FORGED');forged.unitPriceCopper++;forged.totalPriceCopper=forged.unitPriceCopper;const beforeForge=Wealth.snapshot(seed).balance,forgeResult=Tx.execute(seed,plan,forged,sim('1201-05-06 10:08:00'));assert(!forgeResult.ok&&forgeResult.reason==='forged-quote-terms');assert.equal(Wealth.snapshot(seed).balance,beforeForge);
const unowned=Tx.quote(seed,'1201-05-06 10:09:00',plan,{kind:'sell',offerId:rope.offerId,providerRef:rope.providerRef,quantity:1},{marketOptions});assert(!unowned.ok&&unowned.reason==='sale-item-not-owned');
const qDup=quote('1201-05-06 10:10:00','buy',ration,1),dupInput=inputFrom(qDup,'REQ-DUP');const firstDup=Tx.execute(seed,plan,dupInput,sim('1201-05-06 10:10:00')),balanceAfterDup=Wealth.snapshot(seed).balance,qtyAfterDup=Inventory.get(seed,{itemRef:ration.itemRef}).quantity;assert(firstDup.ok&&!firstDup.duplicate);const duplicate=Tx.execute(seed,plan,dupInput,sim('1201-05-06 11:00:00'));assert(duplicate.ok&&duplicate.duplicate&&duplicate.transactionId===firstDup.transactionId);assert.equal(Wealth.snapshot(seed).balance,balanceAfterDup);assert.equal(Inventory.get(seed,{itemRef:ration.itemRef}).quantity,qtyAfterDup);const conflict={...dupInput,quantity:2,totalPriceCopper:dupInput.unitPriceCopper*2};assert.equal(Tx.execute(seed,plan,conflict,sim('1201-05-06 11:01:00')).reason,'duplicate-transaction-conflict');
const qRollback=quote('1201-05-06 11:02:00','buy',rope,1),rollbackInput=inputFrom(qRollback,'REQ-ROLLBACK'),beforeRollbackBalance=Wealth.snapshot(seed).balance,beforeRollbackInv=JSON.stringify(Inventory.snapshot(seed).records),realInventory=global.ProtagonistInventory;global.ProtagonistInventory={...realInventory,acquire(){return{ok:false,reason:'injected-inventory-failure'}}};const rolled=Tx.execute(seed,plan,rollbackInput,sim('1201-05-06 11:02:00'));global.ProtagonistInventory=realInventory;assert(!rolled.ok&&rolled.rolledBack&&rolled.atomicOutcome);assert.equal(Wealth.snapshot(seed).balance,beforeRollbackBalance);assert.equal(JSON.stringify(Inventory.snapshot(seed).records),beforeRollbackInv);assert(Tx.get(seed,'REQ-ROLLBACK').state==='rolled-back');
const qRecover=quote('1201-05-06 11:02:30','buy',rope,1),recoverInput=inputFrom(qRecover,'REQ-RECOVERY'),beforeRecoveryBalance=Wealth.snapshot(seed).balance,beforeRecoveryInv=JSON.stringify(Inventory.snapshot(seed).records),realWealth=global.ProtagonistWealth;global.ProtagonistInventory={...realInventory,acquire(){return{ok:false,reason:'injected-inventory-failure'}}};global.ProtagonistWealth={...realWealth,credit(seedValue,amount,details,opts,identity){if(details?.reasonCode==='economic-rollback')return{ok:false,reason:'injected-rollback-failure'};return realWealth.credit(seedValue,amount,details,opts,identity)}};const recoveryRequired=Tx.execute(seed,plan,recoverInput,sim('1201-05-06 11:02:30'));global.ProtagonistInventory=realInventory;global.ProtagonistWealth=realWealth;assert(!recoveryRequired.ok&&recoveryRequired.state==='recovery-required'&&!recoveryRequired.atomicOutcome&&recoveryRequired.atomicRollbackFailed);assert(Wealth.snapshot(seed).balance<beforeRecoveryBalance);assert.equal(JSON.stringify(Inventory.snapshot(seed).records),beforeRecoveryInv);assert.equal(Tx.get(seed,'REQ-RECOVERY').state,'recovery-required');const qBlocked=quote('1201-05-06 11:02:40','buy',rope,1),blockedByRecovery=Tx.execute(seed,plan,inputFrom(qBlocked,'REQ-BLOCKED-BY-RECOVERY'),sim('1201-05-06 11:02:40'));assert(!blockedByRecovery.ok&&blockedByRecovery.reason==='transaction-recovery-required');const recovered=Tx.execute(seed,plan,recoverInput,sim('1201-05-06 11:02:50'));assert(!recovered.ok&&recovered.state==='rolled-back'&&recovered.atomicOutcome&&!recovered.atomicRollbackFailed);assert.equal(Wealth.snapshot(seed).balance,beforeRecoveryBalance);assert.equal(JSON.stringify(Inventory.snapshot(seed).records),beforeRecoveryInv);
const stockSeed='WP-S012-004-STOCK',stockTime='1201-05-06 09:00:00',stockSnapshot=LocalMarket.snapshot(stockSeed,stockTime,plan,{composition}),stockOffer=stockSnapshot.offers.find(x=>x.itemRef?.id==='TRAVEL-RATION');assert(stockOffer&&stockOffer.quantityAvailable>0);assert(Wealth.credit(stockSeed,1000,{reasonCode:'test-stock-funds',sourceRef:{kind:'test',id:'STOCK-FUNDS'}},{authority:'simulation',authoritative:true,campaignSeed:stockSeed,operationId:'STOCK-FUNDS',fantasyTimestamp:'1201-05-06 08:59:00'}).ok);const stockQuote=Tx.quote(stockSeed,stockTime,plan,{kind:'buy',offerId:stockOffer.offerId,providerRef:stockOffer.providerRef,quantity:stockOffer.quantityAvailable},{marketOptions:{composition}}),stockInput=inputFrom(stockQuote,'REQ-STOCK-FULL'),stockBuy=Tx.execute(stockSeed,plan,stockInput,{authority:'simulation',authoritative:true,campaignSeed:stockSeed,fantasyTimestamp:stockTime,marketOptions:{composition}});assert(stockBuy.ok);const stockTime2='1201-05-06 09:01:00',stockOffer2=LocalMarket.snapshot(stockSeed,stockTime2,plan,{composition}).offers.find(x=>x.offerId===stockOffer.offerId),stockQuote2=Tx.quote(stockSeed,stockTime2,plan,{kind:'buy',offerId:stockOffer2.offerId,providerRef:stockOffer2.providerRef,quantity:1},{marketOptions:{composition}}),stockSecond=Tx.execute(stockSeed,plan,inputFrom(stockQuote2,'REQ-STOCK-OVERSELL'),{authority:'simulation',authoritative:true,campaignSeed:stockSeed,fantasyTimestamp:stockTime2,marketOptions:{composition}});assert(!stockSecond.ok&&stockSecond.reason==='insufficient-market-stock'&&stockSecond.available===0);
const qReplay=quote('1201-05-06 11:03:00','buy',rope,1),replayInput=inputFrom(qReplay,'REQ-REPLAY'),saved=C(WorldState.serializeState(seed));const replayA=Tx.execute(seed,plan,replayInput,sim('1201-05-06 11:03:00')),stateA={wealth:Wealth.snapshot(seed),inventory:Inventory.snapshot(seed),tx:Tx.get(seed,'REQ-REPLAY')};WorldState.restoreSerializedState({seed},saved);const replayB=Tx.execute(seed,plan,replayInput,sim('1201-05-06 11:03:00')),stateB={wealth:Wealth.snapshot(seed),inventory:Inventory.snapshot(seed),tx:Tx.get(seed,'REQ-REPLAY')};assert.deepStrictEqual(replayB,replayA);assert.deepStrictEqual(stateB,stateA);
const preReload=Tx.snapshot(seed);delete require.cache[require.resolve(path.resolve(__dirname,'../world/economic-transaction.js'))];const Reloaded=require(path.resolve(__dirname,'../world/economic-transaction.js'));assert.deepStrictEqual(Reloaded.snapshot(seed).records,preReload.records);const dupReload=Reloaded.execute(seed,plan,replayInput,sim('1201-05-06 12:00:00'));assert(dupReload.ok&&dupReload.duplicate);
assert.equal(Reloaded.execute(other,plan,replayInput,{authority:'simulation',authoritative:true,campaignSeed:seed,fantasyTimestamp:'1201-05-06 12:01:00',marketOptions}).reason,'campaign-seed-mismatch');
const finalSnap=Reloaded.snapshot(seed);assert(finalSnap.compatible&&finalSnap.recordCount<=Reloaded.MAX_RECORDS&&finalSnap.serializedBytes<=Reloaded.MAX_LEDGER_BYTES);assert.equal(finalSnap.fullWorldScan,false);assert.equal(finalSnap.wholeInventoryScan,false);assert.equal(finalSnap.perFrameScan,false);assert.equal(finalSnap.directMarketMutation,false);assert.equal(finalSnap.directCurrencyMutation,false);assert.equal(finalSnap.directInventoryMutation,false);
const root=path.resolve(__dirname,'../..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),script='scripts/world/economic-transaction.js?v=economic-transaction-v1';assert(html.includes(script));assert(html.indexOf(script)>html.indexOf('scripts/world/protagonist-employment.js?v=protagonist-employment-v1'));assert(html.indexOf(script)<html.indexOf('scripts/world/protagonist-social-contact.js?v=protagonist-social-contact-v1'));
const src=fs.readFileSync(path.resolve(__dirname,'../world/economic-transaction.js'),'utf8');for(const bad of ['Math.random(','Date.now(','new Date(','innerWidth','innerHeight','devicePixelRatio','navigator.'])assert(!src.includes(bad));for(const marker of ['currentMarketRevalidated:true','directMarketMutation:false','directCurrencyMutation:false','directInventoryMutation:false','fullWorldScan:false','wholeInventoryScan:false','perFrameScan:false'])assert(src.includes(marker));
console.log(JSON.stringify({wp:'WP-S012-004',classification:'FUNCTIONAL',visual:'N/A — validated economic transaction authority adds no rendered surface',pass:true,buyTransaction:buy.transactionId,sellTransaction:sell.transactionId,serviceTransaction:service.transactionId,serviceResult:service.serviceResultId,insufficientFundsRejected:true,missingStockRejected:true,forgedPriceRejected:true,unownedSaleRejected:true,staleOfferRejected:true,duplicateIdempotence:true,duplicateConflictRejected:true,saveReload:true,deterministicReplay:true,atomicRollback:true,rollbackFailureRecovery:true,cumulativeOversellRejected:true,bounds:finalSnap.bounds,fullWorldScan:false,wholeInventoryScan:false,wholeHistoryScan:false,perFrameScan:false,directMarketMutation:false,directCurrencyMutation:false,directInventoryMutation:false},null,2));
