const assert=require('assert'),fs=require('fs'),path=require('path');global.window=global;global.TextEncoder=global.TextEncoder||require('util').TextEncoder;
const C=v=>v==null||typeof v!=='object'?v:Array.isArray(v)?v.map(C):Object.fromEntries(Object.entries(v).map(([k,x])=>[k,C(x)]));
function merge(a,b){const o=C(a||{});for(const[k,v]of Object.entries(b||{}))o[k]=v&&typeof v==='object'&&!Array.isArray(v)?merge(o[k],v):C(v);return o}
function H(s){let h=2166136261>>>0;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)>>>0}return(h>>>0).toString(16).toUpperCase().padStart(8,'0')}
const stores=new Map(),fresh=s=>({seed:s,sequence:0,entries:{}}),ensure=s=>(stores.has(s)||stores.set(s,fresh(s)),stores.get(s));
global.WorldState={structuralRef(s,k,p,key,initial){return{id:'STR|'+k.toUpperCase()+'|'+H([s,k,p,key].join('|')),kind:k,key:{initial:C(initial||{})}}},resolve(s,r){const st=ensure(s),e=st.entries[r.id];return{current:merge(r.key.initial,e?.changes||{}),delta:e||null}},applyDelta(s,r,changes,reason){const st=ensure(s),p=st.entries[r.id];st.sequence++;st.entries[r.id]={revision:(p?.revision||0)+1,reason,changes:merge(p?.changes||{},changes)};return{ok:true,reason:'ok',entry:C(st.entries[r.id])}},serializeState(s){return C(ensure(s))},restoreSerializedState(c,x){stores.set(String(c.seed),C(x));return{ok:true}}};
const seed='WP-S012-001-A',other='WP-S012-001-B';global.ProtagonistProfile={derive(s,k='protagonist'){return{protagonistId:'PROTAGONIST-'+H(s+'|'+k+'|identity-v1')}}};let now='1201-03-02 09:00:00';global.GameTime={getTimestampKey(){return now}};
const W=require(path.resolve(__dirname,'../world/protagonist-wealth.js')),src=(kind,id)=>({kind,id}),sim=(operationId,x={})=>({authority:'simulation',authoritative:true,campaignSeed:seed,operationId,fantasyTimestamp:now,...x});
const opening=W.snapshot(seed).balance;assert(Number.isInteger(opening)&&opening>=18&&opening<=36);assert.equal(W.snapshot(seed).openingBalance,opening);assert([other,'WP-S012-001-C','WP-S012-001-D'].some(s=>W.snapshot(s).balance!==opening),'alternate SEED should alter opening wealth');
let r=W.credit(seed,50,{reasonCode:'work-wage',sourceRef:src('work-result','WORK-1'),transferRef:src('employer','NPC-SMITH')},sim('C1'));assert(r.ok&&!r.duplicate);assert(/^TXN-[0-9A-F]{8}$/.test(r.transactionId));assert.equal(r.transaction.balanceBefore,opening);assert.equal(r.transaction.balanceAfter,opening+50);const creditId=r.transactionId;
assert(W.credit(seed,50,{reasonCode:'work-wage',sourceRef:src('work-result','WORK-1'),transferRef:src('employer','NPC-SMITH')},sim('C1')).duplicate);assert.equal(W.snapshot(seed).balance,opening+50);assert.equal(W.credit(seed,51,{reasonCode:'work-wage',sourceRef:src('work-result','WORK-1')},sim('C1')).reason,'duplicate-operation-conflict');assert.equal(W.snapshot(seed).balance,opening+50);
now='1201-03-02 09:01:00';r=W.debit(seed,7,{reasonCode:'market-purchase',sourceRef:src('offer','OFFER-1'),transferRef:src('seller','NPC-BAKER')},sim('D1'));assert(r.ok);assert.equal(r.transaction.balanceAfter,opening+43);assert.deepStrictEqual(r.transaction.transferRef,src('seller','NPC-BAKER'));const debitId=r.transactionId;
const beforeReject=W.snapshot(seed);assert.equal(W.debit(seed,beforeReject.balance+1,{reasonCode:'overspend',sourceRef:src('offer','OFFER-2')},sim('D2')).reason,'insufficient-funds');assert.equal(W.snapshot(seed).balance,beforeReject.balance);assert.equal(W.credit(seed,0,{reasonCode:'bad',sourceRef:src('test','BAD')},sim('BAD0')).reason,'transaction-amount-invalid');assert.equal(W.credit(seed,1.5,{reasonCode:'bad',sourceRef:src('test','BAD')},sim('BAD1')).reason,'transaction-amount-invalid');assert.equal(W.credit(seed,1,{reasonCode:'bad',sourceRef:src('test','BAD')},{authority:'ui',authoritative:true,campaignSeed:seed,operationId:'UI',fantasyTimestamp:now}).reason,'simulation-authority-required');assert.equal(W.credit(seed,1,{reasonCode:'bad',sourceRef:src('test','BAD')},sim('CROSS',{campaignSeed:other})).reason,'campaign-seed-mismatch');assert.equal(W.snapshot(seed).balance,beforeReject.balance);
now='1201-03-02 09:00:30';assert.equal(W.credit(seed,2,{reasonCode:'stale',sourceRef:src('test','STALE')},sim('OLD')).reason,'timestamp-before-current-state');assert.equal(W.snapshot(seed).balance,beforeReject.balance);
assert(W.canAfford(seed,opening).affordable);assert(!W.canAfford(seed,W.snapshot(seed).balance+1).affordable);assert(W.conversationSummary(seed).grounded);assert(W.commandContext(seed).readOnly);assert.equal(W.get(seed,creditId).id,creditId);assert.equal(W.get(seed,debitId).id,debitId);
const saved=WorldState.serializeState(seed),pre=W.snapshot(seed);stores.set(seed,fresh(seed));assert.equal(W.snapshot(seed).balance,opening);WorldState.restoreSerializedState({seed},saved);assert.equal(W.snapshot(seed).balance,pre.balance);assert.deepStrictEqual(W.snapshot(seed).transactions,pre.transactions);
now='1201-03-02 09:02:00';const otherOpening=W.snapshot(other).balance;assert.equal(W.credit(other,9,{reasonCode:'other-campaign',sourceRef:src('event','OTHER')},{...sim('B1'),campaignSeed:other}).ok,true);assert.equal(W.snapshot(other).balance,otherOpening+9);assert.equal(W.snapshot(seed).balance,pre.balance);
const replay='WP-S012-001-REPLAY';function runReplay(){now='1201-05-01 10:00:00';const open=W.snapshot(replay).balance;const a=W.credit(replay,11,{reasonCode:'wage',sourceRef:src('work','R1')},{authority:'simulation',authoritative:true,campaignSeed:replay,operationId:'R-C',fantasyTimestamp:now});now='1201-05-01 10:01:00';const b=W.debit(replay,3,{reasonCode:'food',sourceRef:src('offer','R2')},{authority:'simulation',authoritative:true,campaignSeed:replay,operationId:'R-D',fantasyTimestamp:now});return{open,credit:a.transactionId,debit:b.transactionId,balance:W.snapshot(replay).balance,totalCredited:W.snapshot(replay).totalCredited,totalDebited:W.snapshot(replay).totalDebited}}
const replayA=runReplay();stores.set(replay,fresh(replay));const replayB=runReplay();assert.deepStrictEqual(replayB,replayA);
now='1201-03-02 10:00:00';for(let i=0;i<100;i++)assert(W.credit(seed,1,{reasonCode:'bounded-credit',sourceRef:src('fixture','F'+i)},sim('F'+i)).ok);const snap=W.snapshot(seed);assert.equal(snap.transactionCount,W.MAX_TRANSACTIONS);assert(snap.operationIdCount<=W.MAX_OPERATION_IDS);assert(snap.serializedBytes<=W.MAX_LEDGER_BYTES);assert.equal(W.list(seed,{limit:999}).length,W.MAX_QUERY_RESULTS);assert.equal(snap.persistenceAuthority,'WorldState CampaignStateDelta');assert.equal(snap.foundationAuthority,'Campaign SEED only');assert.equal(snap.mutationAuthority,'explicit Simulation-authorized transactions only');assert.equal(snap.fullWorldScan,false);assert.equal(snap.wholeHistoryScan,false);assert.equal(snap.perFrameScan,false);assert.equal(snap.directActionExecution,false);assert.equal(snap.directInventoryMutation,false);assert.equal(snap.settlementEconomyAuthority,false);
global.innerWidth=320;global.navigator={userAgent:'a'};const portable=W.snapshot(seed);global.innerWidth=1920;global.navigator={userAgent:'b'};assert.deepStrictEqual(W.snapshot(seed).transactions,portable.transactions);assert.equal(W.snapshot(seed).balance,portable.balance);
const root=path.resolve(__dirname,'../..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),script='scripts/world/protagonist-wealth.js?v=protagonist-wealth-v1';assert(html.includes(script));assert(html.indexOf(script)>html.indexOf('scripts/world/protagonist-inventory.js?v=protagonist-inventory-v1'));assert(html.indexOf(script)<html.indexOf('scripts/world/protagonist-health.js?v=protagonist-health-v1'));const source=fs.readFileSync(path.resolve(__dirname,'../world/protagonist-wealth.js'),'utf8');for(const x of['Math.random','Date.now','new Date(','innerWidth','navigator.','ProtagonistInventory.acquire','ProtagonistInventory.remove','RegionalSettlementSimulation.'])assert(!source.includes(x),'forbidden authority/non-determinism: '+x);for(const marker of['o.authority!=="simulation"','campaign-seed-mismatch','duplicate-operation-conflict','fullWorldScan:false','wholeHistoryScan:false','perFrameScan:false','directInventoryMutation:false','settlementEconomyAuthority:false'])assert(source.includes(marker),'missing marker '+marker);
console.log(JSON.stringify({wp:'WP-S012-001',classification:'FUNCTIONAL',visual:'N/A — authoritative currency/transaction state introduces no rendered surface',pass:true,openingBalance:opening,creditId,debitId,balance:snap.balance,totalCredited:snap.totalCredited,totalDebited:snap.totalDebited,transactionCount:snap.transactionCount,maxTransactions:W.MAX_TRANSACTIONS,operationIdCount:snap.operationIdCount,maxOperationIds:W.MAX_OPERATION_IDS,serializedBytes:snap.serializedBytes,maxLedgerBytes:W.MAX_LEDGER_BYTES,sameInputReplay:true,saveReload:true,campaignIsolation:true,forgedUiMutationRejected:true,crossCampaignMutationRejected:true,overdraftRejected:true,duplicateConflictRejected:true,persistenceAuthority:snap.persistenceAuthority,foundationAuthority:snap.foundationAuthority,mutationAuthority:snap.mutationAuthority,fullWorldScan:snap.fullWorldScan,wholeHistoryScan:snap.wholeHistoryScan,perFrameScan:snap.perFrameScan,directInventoryMutation:snap.directInventoryMutation,settlementEconomyAuthority:snap.settlementEconomyAuthority},null,2));
