const assert=require('assert'),fs=require('fs'),path=require('path');global.window=global;global.TextEncoder=global.TextEncoder||require('util').TextEncoder;
const C=v=>v==null||typeof v!=='object'?v:Array.isArray(v)?v.map(C):Object.fromEntries(Object.entries(v).map(([k,x])=>[k,C(x)]));
function merge(a,b){const o=C(a||{});for(const[k,v]of Object.entries(b||{}))o[k]=v&&typeof v==='object'&&!Array.isArray(v)?merge(o[k],v):C(v);return o}
function H(s){let h=2166136261>>>0;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)>>>0}h^=h>>>16;h=Math.imul(h,2246822507);h^=h>>>13;return(h>>>0).toString(16).toUpperCase().padStart(8,'0')}
const stores=new Map(),fresh=s=>({seed:s,sequence:0,entries:{}}),ensure=s=>(stores.has(s)||stores.set(s,fresh(s)),stores.get(s));
global.WorldState={structuralRef(s,k,p,key,initial){return{id:'STR|'+k.toUpperCase()+'|'+H([s,k,p,key].join('|')),kind:k,key:{initial:C(initial||{})}}},resolve(s,r){const st=ensure(s),e=st.entries[r.id];return{current:merge(r.key.initial,e?.changes||{}),delta:e||null}},applyDelta(s,r,changes,reason){const st=ensure(s),p=st.entries[r.id];st.sequence++;st.entries[r.id]={revision:(p?.revision||0)+1,reason,changes:merge(p?.changes||{},changes)};return{ok:true,reason:'ok',entry:C(st.entries[r.id])}},serializeState(s){return C(ensure(s))},restoreSerializedState(c,x){stores.set(String(c.seed),C(x));return{ok:true}}};
global.ProtagonistProfile={derive(s,k='protagonist'){return{protagonistId:'PROTAGONIST-'+H(s+'|'+k+'|identity-v1')}}};
let now='1201-06-01 07:00:00';global.GameTime={getTimestampKey(){return now}};
const Skills=require(path.resolve(__dirname,'../world/protagonist-skills.js'));
const seed='WP-S013-001-A',other='WP-S013-001-B',identity='protagonist';
const src=(kind,id)=>({kind,id});
const sim=(operationId,skillId,practiceBand='standard',extra={})=>({authority:'simulation',authoritative:true,campaignSeed:seed,operationId,fantasyTimestamp:now,evidence:{type:'validated-skill-practice',validated:true,skillId,practiceBand,outcome:'completed',sourceRef:src('simulation-result','RESULT-'+operationId)},...extra});

const init=Skills.initialize(seed,identity,now);assert(init.ok&&init.created);const base=Skills.snapshot(seed,identity);assert(base.exists);assert.equal(base.skills.length,Object.keys(Skills.SKILL_DEFS).length);assert(base.skills.every(s=>s.points>=400&&s.points<=1300));assert(base.skills.every(s=>s.level===0||s.level===1));assert.equal(base.foundationAuthority,'Campaign SEED only');
const sameBaseline=base.skills.map(s=>[s.skillId,s.points]);stores.set(seed,fresh(seed));assert(Skills.initialize(seed,identity,now).ok);assert.deepStrictEqual(Skills.snapshot(seed,identity).skills.map(s=>[s.skillId,s.points]),sameBaseline,'same SEED must reproduce the same competence foundation');assert(Skills.initialize(other,identity,now).ok);assert.notDeepStrictEqual(Skills.snapshot(other,identity).skills.map(s=>s.points),base.skills.map(s=>s.points),'alternate SEED should alter at least one competence baseline');

const craftBefore=Skills.getSkill(seed,'craft',identity),laborBefore=Skills.getSkill(seed,'labor',identity);now='1201-06-01 08:00:00';let r=Skills.recordPractice(seed,'craft',sim('PRACTICE-1','craft','standard'),identity);assert(r.ok&&!r.duplicate);assert(/^SKP-[0-9A-F]{8}$/.test(r.practice.id));assert.equal(r.practice.pointsAwarded,Skills.PRACTICE_BANDS.standard);assert.equal(Skills.getSkill(seed,'craft',identity).points,craftBefore.points+Skills.PRACTICE_BANDS.standard);assert.equal(Skills.getSkill(seed,'labor',identity).points,laborBefore.points,'practice must not mutate unrelated competence');
const afterOne=Skills.snapshot(seed,identity),dup=Skills.recordPractice(seed,'craft',sim('PRACTICE-1','craft','standard'),identity);assert(dup.ok&&dup.duplicate);assert.equal(Skills.snapshot(seed,identity).history.length,afterOne.history.length);assert.equal(Skills.recordPractice(seed,'craft',sim('PRACTICE-1','craft','intensive'),identity).reason,'duplicate-operation-conflict');
assert.equal(Skills.recordPractice(seed,'craft',{...sim('UI-FORGE','craft'),authority:'ui'}).reason,'simulation-authority-required');assert.equal(Skills.recordPractice(seed,'craft',{...sim('CROSS','craft'),campaignSeed:other}).reason,'campaign-seed-mismatch');assert.equal(Skills.recordPractice(seed,'unknown',sim('UNKNOWN','unknown')).reason,'unsupported-skill');assert.equal(Skills.recordPractice(seed,'craft',{authority:'simulation',authoritative:true,campaignSeed:seed,operationId:'NO-EVIDENCE',fantasyTimestamp:now}).reason,'validated-practice-evidence-required');assert.equal(Skills.recordPractice(seed,'craft',sim('MISMATCH','labor')).reason,'practice-evidence-skill-mismatch');
now='1201-06-01 07:30:00';assert.equal(Skills.recordPractice(seed,'craft',sim('REWIND','craft'),identity).reason,'cannot-rewind-skills-state');

const currentCraft=Skills.getSkill(seed,'craft',identity);let q=Skills.qualificationCheck(seed,[{skillId:'craft',minLevel:currentCraft.level},{skillId:'administration',minLevel:5}],identity);assert.equal(q.qualified,false);assert.equal(q.passed.length,1);assert.equal(q.failed.length,1);assert.equal(q.readOnly,true);assert.equal(q.grantsProfession,false);assert.equal(q.grantsRank,false);assert.equal(q.grantsAuthority,false);
q=Skills.qualificationCheck(seed,[{skillId:'craft',minLevel:currentCraft.level}],identity);assert.equal(q.qualified,true);assert.equal(q.failed.length,0);

const saved=WorldState.serializeState(seed),preReload=Skills.snapshot(seed,identity);stores.set(seed,fresh(seed));assert.equal(Skills.snapshot(seed,identity).exists,false);WorldState.restoreSerializedState({seed},saved);const restored=Skills.snapshot(seed,identity);assert.deepStrictEqual(restored.skills,preReload.skills);assert.deepStrictEqual(restored.history,preReload.history);

const replaySeed='WP-S013-001-REPLAY';function replayRun(){now='1201-07-01 09:00:00';Skills.initialize(replaySeed,identity,now);const opts={authority:'simulation',authoritative:true,campaignSeed:replaySeed,operationId:'R1',fantasyTimestamp:now,evidence:{type:'validated-skill-practice',validated:true,skillId:'labor',practiceBand:'brief',outcome:'success',sourceRef:src('work-result','R-WORK')}};const result=Skills.recordPractice(replaySeed,'labor',opts,identity);return{baseline:Skills.snapshot(replaySeed,identity).skills.map(s=>[s.skillId,s.points-(s.skillId==='labor'?Skills.PRACTICE_BANDS.brief:0)]),practice:C(result.practice),snapshot:C(Skills.snapshot(replaySeed,identity).skills)}}const replayA=replayRun();stores.set(replaySeed,fresh(replaySeed));const replayB=replayRun();assert.deepStrictEqual(replayB,replayA);

now='1201-06-01 09:00:00';for(let i=0;i<80;i++){const skillId=i%2?'labor':'survival';assert(Skills.recordPractice(seed,skillId,sim('BOUND-'+i,skillId,'brief'),identity).ok)}const bounded=Skills.snapshot(seed,identity);assert.equal(bounded.history.length,Skills.MAX_HISTORY);assert(bounded.recentOperationCount<=Skills.MAX_RECENT_OPERATIONS);assert(bounded.serializedBytes<=Skills.MAX_STATE_BYTES);assert.equal(Skills.list(seed,{limit:999},identity).length,Object.keys(Skills.SKILL_DEFS).length);assert.equal(Skills.qualificationCheck(seed,Array.from({length:20},(_,i)=>({skillId:['labor','craft','social','administration','martial','survival'][i%6],minLevel:0})),identity).requestedCount<=Skills.MAX_QUALIFICATION_REQUIREMENTS,true);
const decision=Skills.decisionContext(seed,identity);assert.equal(decision.readOnly,true);assert.equal(decision.professionAuthority,false);assert.equal(decision.rankAuthority,false);assert.equal(decision.directActionExecution,false);assert.equal(decision.worldMutation,false);
global.innerWidth=320;global.navigator={userAgent:'device-a'};const portable=Skills.snapshot(seed,identity);global.innerWidth=1920;global.navigator={userAgent:'device-b'};assert.deepStrictEqual(Skills.snapshot(seed,identity).skills,portable.skills);assert.deepStrictEqual(Skills.snapshot(seed,identity).history,portable.history);
const telem=Skills.telemetry();assert(telem.reads>0&&telem.writes>0&&telem.practiceAwards>0&&telem.duplicates>0&&telem.rejections>0&&telem.qualificationQueries>0);assert.equal(telem.fullWorldScan,false);assert.equal(telem.wholeHistoryScan,false);assert.equal(telem.perFrameScan,false);assert.equal(telem.authority,false);
assert.equal(bounded.practiceAuthority,'explicit validated Simulation practice evidence only');assert.equal(bounded.persistenceAuthority,'WorldState CampaignStateDelta');assert.equal(bounded.qualificationAuthority,'read-only prerequisite evaluation');assert.equal(bounded.professionAuthority,false);assert.equal(bounded.rankAuthority,false);assert.equal(bounded.legitimateAuthorityGrant,false);assert.equal(bounded.inventoryAuthority,false);assert.equal(bounded.economyAuthority,false);assert.equal(bounded.combatAuthority,false);assert.equal(bounded.uiPracticeAuthority,false);assert.equal(bounded.dialoguePracticeAuthority,false);assert.equal(bounded.llmPracticeAuthority,false);

const source=fs.readFileSync(path.resolve(__dirname,'../world/protagonist-skills.js'),'utf8');for(const x of['Math.random','Date.now','new Date(','innerWidth','innerHeight','devicePixelRatio','navigator.','ProtagonistAuthority.transition','ProtagonistEmployment.','ProtagonistInventory.','ProtagonistWealth.'])assert(!source.includes(x),'forbidden authority/non-determinism: '+x);for(const marker of['options?.authority!=="simulation"','campaign-seed-mismatch','duplicate-operation-conflict','fullWorldScan:false','wholeHistoryScan:false','perFrameScan:false','professionAuthority:false','rankAuthority:false','combatAuthority:false'])assert(source.includes(marker),'missing marker '+marker);
const root=path.resolve(__dirname,'../..'),htmlPath=path.join(root,'index.html');if(fs.existsSync(htmlPath)){const html=fs.readFileSync(htmlPath,'utf8'),script='scripts/world/protagonist-skills.js?v=protagonist-skills-v1';assert(html.includes(script),'canonical root must load ProtagonistSkills');assert(html.indexOf(script)>html.indexOf('scripts/world/protagonist-profile.js?v=protagonist-profile-v1'));assert(html.indexOf(script)<html.indexOf('scripts/world/protagonist-goals.js?v=protagonist-goals-v1'));}
console.log(JSON.stringify({wp:'WP-S013-001',classification:'FUNCTIONAL',visual:'N/A — authoritative competence/qualification state introduces no rendered surface',pass:true,version:Skills.VERSION,skillCount:base.skills.length,seedBaselineDeterministic:true,alternateSeedDiverges:true,validatedPractice:true,unrelatedSkillStable:true,duplicateIdempotence:true,duplicateConflictRejected:true,forgedUiPracticeRejected:true,crossCampaignRejected:true,rewindRejected:true,qualificationPassAndFail:true,saveReload:true,campaignIsolation:true,sameInputReplay:true,maxHistory:Skills.MAX_HISTORY,maxRecentOperations:Skills.MAX_RECENT_OPERATIONS,maxQualificationRequirements:Skills.MAX_QUALIFICATION_REQUIREMENTS,maxStateBytes:Skills.MAX_STATE_BYTES,serializedBytes:bounded.serializedBytes,foundationAuthority:bounded.foundationAuthority,practiceAuthority:bounded.practiceAuthority,persistenceAuthority:bounded.persistenceAuthority,qualificationAuthority:bounded.qualificationAuthority,fullWorldScan:bounded.fullWorldScan,wholeHistoryScan:bounded.wholeHistoryScan,perFrameScan:bounded.perFrameScan,directActionExecution:bounded.directActionExecution,professionAuthority:bounded.professionAuthority,rankAuthority:bounded.rankAuthority,legitimateAuthorityGrant:bounded.legitimateAuthorityGrant,combatAuthority:bounded.combatAuthority,telemetry:telem},null,2));
