const assert=require("assert"),fs=require("fs"),path=require("path");global.window=global;global.TextEncoder=global.TextEncoder||require("util").TextEncoder;
const C=v=>v==null||typeof v!=="object"?v:Array.isArray(v)?v.map(C):Object.fromEntries(Object.entries(v).map(([k,x])=>[k,C(x)]));
function merge(a,b){const o=C(a||{});for(const[k,v]of Object.entries(b||{}))o[k]=v&&typeof v==="object"&&!Array.isArray(v)?merge(o[k],v):C(v);return o}
function H(s){let h=2166136261>>>0;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)>>>0}return(h>>>0).toString(16).toUpperCase().padStart(8,"0")}
const stores=new Map();let writes=0;const fresh=s=>({seed:s,sequence:0,entries:{}}),ensure=s=>(stores.has(s)||stores.set(s,fresh(s)),stores.get(s));
global.WorldState={structuralRef(s,k,p,keyName,initial){return{id:"STR|"+k.toUpperCase()+"|"+H([s,k,p,keyName].join("|")),kind:k,key:{initial:C(initial||{})}}},resolve(s,r){const st=ensure(s),e=st.entries[r.id];return{current:merge(r.key?.initial||{},e?.changes||{}),delta:e||null}},applyDelta(s,r,changes,reason){writes++;const st=ensure(s),p=st.entries[r.id];st.sequence++;st.entries[r.id]={revision:(p?.revision||0)+1,reason,changes:merge(p?.changes||{},changes)};return{ok:true,reason:"ok",entry:C(st.entries[r.id])}},serializeState(s){return C(ensure(s))},restoreSerializedState(c,x){stores.set(String(c.seed),C(x));return{ok:true}}};
global.ProtagonistProfile={derive(s,k="protagonist"){return{protagonistId:"PROTAGONIST-"+H(s+"|"+k+"|identity-v1")}}};
global.HousePlans={build(){return[{id:"H1",kind:"house"},{id:"H2",kind:"house"}]}};
const root=path.resolve(__dirname,"../.."),authorityPath=path.join(root,"scripts/world/protagonist-authority.js"),housingPath=path.join(root,"scripts/world/protagonist-housing.js"),modulePath=path.join(root,"scripts/world/protagonist-status-obligations.js");
delete require.cache[require.resolve(authorityPath)];const Authority=require(authorityPath);global.ProtagonistAuthority=Authority;
delete require.cache[require.resolve(housingPath)];const Housing=require(housingPath);global.ProtagonistHousing=Housing;
let employmentReads=0;global.ProtagonistEmployment={current(seed,when){employmentReads++;return{ok:true,status:"active",contract:{id:"EMP-SMITH",professionId:"smith",employerRef:{kind:"resident",id:"R01"},workplaceRef:{kind:"building",id:"BLD-SMITHY"},workBlocks:[{id:"day",startMinute:540,endMinute:1020}]}}}};
delete require.cache[require.resolve(modulePath)];const Status=require(modulePath);global.ProtagonistStatusObligations=Status;
const seed="WP-S013-007-SEED",identity="protagonist",t0="1201-06-01 08:00:00";
assert(Authority.initialize(seed,identity,t0).ok);
assert(Housing.establish(seed,{occupancyBasis:"rented",residenceRef:{kind:"house-plan",id:"H1"},rentCopper:12,cadenceDays:1,sourceRef:{kind:"simulation-outcome",id:"RENT-1"}},{authority:"simulation",authoritative:true,campaignSeed:seed,fantasyTimestamp:t0}).ok);
const setupWrites=writes;
const ordinary=Status.resolve(seed,"1201-06-01 09:00:00",identity);assert(ordinary.ok);assert.equal(ordinary.role.roleId,"local-resident");assert.deepEqual(ordinary.privileges.map(x=>x.category),["self-directed-local-action"]);assert(!ordinary.duties.some(x=>x.category==="settlement-administration"));assert(ordinary.restrictedActions.some(x=>x.category==="settlement-administration"));assert(ordinary.obligations.some(x=>x.kind==="employment-duty"));assert(ordinary.obligations.some(x=>x.kind==="housing-obligation"&&x.state==="upcoming"));assert.equal(Status.checkPrivilege(seed,"settlement-administration","1201-06-01 09:00:00",identity).reason,"missing-authority-scope");assert.equal(writes,setupWrites,"read-only resolver must not persist or mutate source systems");
const beforeHistory=Authority.snapshot(seed,identity).history.length;
const trans=Authority.transition(seed,identity,"village-steward",{authority:"simulation",authoritative:true,transitionId:"STATUS-ROLE-1",fantasyTimestamp:"1201-06-01 10:00:00",evidence:{validated:true,type:"legitimate-role-transition",targetRoleId:"village-steward",sourceRef:{kind:"institution",id:"VILLAGE-COUNCIL"}}});assert(trans.ok);
const higher=Status.resolve(seed,"1201-06-01 10:01:00",identity);assert(higher.ok);assert.equal(higher.role.roleId,"village-steward");assert(higher.privileges.some(x=>x.category==="settlement-administration"));assert(higher.privileges.some(x=>x.category==="request-local-assistance"));assert(higher.duties.some(x=>x.category==="settlement-administration"));assert(higher.obligations.some(x=>x.kind==="status-duty"&&x.category==="settlement-administration"&&x.state==="standing"));const permitted=Status.checkPrivilege(seed,"settlement-administration","1201-06-01 10:01:00",identity);assert(permitted.ok&&permitted.permitted&&permitted.guaranteedSuccess===false&&permitted.simulationValidationRequired===true);assert.equal(Authority.snapshot(seed,identity).history.length,beforeHistory+1,"resolver must not create role transitions");
const due=Status.resolve(seed,"1201-06-02 08:00:00",identity),overdue=Status.resolve(seed,"1201-06-03 08:00:00",identity);assert(due.obligations.some(x=>x.kind==="housing-obligation"&&x.state==="due"&&x.dueAt==="1201-06-02 08:00:00"));assert(overdue.obligations.some(x=>x.kind==="housing-obligation"&&x.state==="overdue"));assert.equal(writes,setupWrites+1,"only explicit authority transition may write during status checks");
const saved=C(WorldState.serializeState(seed)),beforeReload=Status.resolve(seed,"1201-06-03 08:00:00",identity);stores.set(seed,fresh(seed));WorldState.restoreSerializedState({seed},saved);delete require.cache[require.resolve(authorityPath)];global.ProtagonistAuthority=require(authorityPath);delete require.cache[require.resolve(housingPath)];global.ProtagonistHousing=require(housingPath);delete require.cache[require.resolve(modulePath)];const Reloaded=require(modulePath);global.ProtagonistStatusObligations=Reloaded;const afterReload=Reloaded.resolve(seed,"1201-06-03 08:00:00",identity);assert.deepStrictEqual(afterReload.role,beforeReload.role);assert.deepStrictEqual(afterReload.obligations,beforeReload.obligations);
assert(global.ProtagonistAuthority.initialize("OTHER-SEED",identity,t0).ok);const other=Reloaded.resolve("OTHER-SEED","1201-06-01 09:00:00",identity);assert(other.ok&&other.role.roleId==="local-resident");assert(!other.duties.some(x=>x.category==="settlement-administration"));
const context=Reloaded.decisionContext(seed,"1201-06-03 08:00:00",identity),telemetry=Reloaded.telemetry();assert(context.ok&&context.readOnly&&context.proposalOnly&&context.directActionExecution===false);assert(context.obligations.length<=Reloaded.MAX_OBLIGATIONS&&context.privileges.length<=Reloaded.MAX_PRIVILEGES&&context.restrictedActions.length<=Reloaded.MAX_RESTRICTIONS);assert(beforeReload.serializedBytes<=Reloaded.MAX_RESULT_BYTES);for(const key of ["fullWorldScan","fullSettlementScan","wholeHistoryScan","perFrameScan","directActionExecution","authorityMutation","economyMutation","propertyMutation","militaryMutation","legalMutation","relationshipMutation","worldMutation"])assert.equal(telemetry[key],false,key);
const src=fs.readFileSync(modulePath,"utf8");for(const bad of ["Math.random(","Date.now(","new Date(","innerWidth","innerHeight","devicePixelRatio","navigator.","ProtagonistAuthority?.transition","applyDelta("])assert(!src.includes(bad),"forbidden authority/mutation/presentation input: "+bad);assert(src.includes("privilegeGuaranteesSuccess:false")&&src.includes("simulationValidationRequired:true"));
const html=fs.readFileSync(path.join(root,"index.html"),"utf8"),script="scripts/world/protagonist-status-obligations.js?v=protagonist-status-obligations-v1";assert(html.includes(script));assert(html.indexOf(script)>html.indexOf("scripts/world/protagonist-authority.js?v=protagonist-authority-v1"));assert(html.indexOf(script)>html.indexOf("scripts/world/protagonist-employment.js?v=protagonist-employment-v1"));assert(html.indexOf(script)>html.indexOf("scripts/world/protagonist-housing.js?v=protagonist-housing-v1"));
console.log(JSON.stringify({wp:"WP-S013-007",classification:"FUNCTIONAL",visual:"N/A — read-only status duty/privilege/obligation context introduces no rendered surface",pass:true,version:Reloaded.VERSION,ordinaryRole:ordinary.role.roleId,higherRole:higher.role.roleId,ordinaryPrivileges:ordinary.privileges.map(x=>x.category),higherPrivileges:higher.privileges.map(x=>x.category),dueState:"due",overdueState:"overdue",saveReload:true,campaignIsolation:true,employmentReads,bounds:context.bounds,guards:telemetry},null,2));
