#!/usr/bin/env python3
"""Attempt 3 for WP-S003-010-003-005-002.

Restore the bounded canonical focus authority that the renderer already prepares
for each physical LOD, and make the focus texture consume that authority instead
of only the 12x shared surround raster. Also raise the three broadest focus
texture resolutions enough that a landscape viewport does not magnify a tiny
regional raster into a soft wash.

All added detail remains deterministic, Campaign-SEED/world-coordinate registered,
viewport bounded, cache bounded, and cooperatively generated by the existing
resource preparation generator.
"""
from pathlib import Path

PATH = Path("scripts/world/planet-stage.js")
text = PATH.read_text(encoding="utf-8")

replacements = [
    (
'''  Object.freeze({id:"regional-overview",band:"regional-overview",visibleHeightMeters:400000,sampleSpacingMeters:12000,textureSize:160,reliefClampMeters:7000,reliefGain:6,maxHeightUnits:.58,staticWorld:false}),
  Object.freeze({id:"regional-detail",band:"regional-detail",visibleHeightMeters:140000,sampleSpacingMeters:4000,textureSize:192,reliefClampMeters:7000,reliefGain:5.5,maxHeightUnits:.56,staticWorld:false}),
  Object.freeze({id:"district",band:"district",visibleHeightMeters:50000,sampleSpacingMeters:1400,textureSize:256,reliefClampMeters:6000,reliefGain:9,maxHeightUnits:.65,staticWorld:false}),''',
'''  Object.freeze({id:"regional-overview",band:"regional-overview",visibleHeightMeters:400000,sampleSpacingMeters:12000,textureSize:320,reliefClampMeters:7000,reliefGain:6,maxHeightUnits:.58,staticWorld:false}),
  Object.freeze({id:"regional-detail",band:"regional-detail",visibleHeightMeters:140000,sampleSpacingMeters:4000,textureSize:384,reliefClampMeters:7000,reliefGain:5.5,maxHeightUnits:.56,staticWorld:false}),
  Object.freeze({id:"district",band:"district",visibleHeightMeters:50000,sampleSpacingMeters:1400,textureSize:448,reliefClampMeters:6000,reliefGain:9,maxHeightUnits:.65,staticWorld:false}),'''
    ),
    (
'''function broadAuthorityRasterSizes(levelIndex){
  // Expensive PlanetGeography sampling stays on the proven cooperative ladder.
  // Closer LODs still refine this canonical base in world space, while the
  // per-output-texel Campaign-SEED registered detail fields supply the additional
  // local frequencies without multiplying geography queries or offscreen work.
  const index=Math.max(0,Number(levelIndex)||0);
  if(index===0)return Object.freeze({shared:80,focus:64});
  if(index===1)return Object.freeze({shared:96,focus:72});
  if(index===2)return Object.freeze({shared:128,focus:80});
  if(index===3)return Object.freeze({shared:160,focus:112});
  if(index===4)return Object.freeze({shared:160,focus:128});
  return Object.freeze({shared:160,focus:144});
}''',
'''function broadAuthorityRasterSizes(levelIndex){
  // Expensive PlanetGeography sampling stays on a bounded cooperative ladder.
  // The shared 12x authority remains intentionally coarse context, while the
  // viewport-bounded focus authority now has enough canonical samples to add
  // real source information as physical LODs refine instead of magnifying the
  // surround raster and relying on presentation-only residuals.
  const index=Math.max(0,Number(levelIndex)||0);
  if(index===0)return Object.freeze({shared:80,focus:192});
  if(index===1)return Object.freeze({shared:96,focus:224});
  if(index===2)return Object.freeze({shared:128,focus:256});
  if(index===3)return Object.freeze({shared:160,focus:288});
  if(index===4)return Object.freeze({shared:160,focus:320});
  if(index<=7)return Object.freeze({shared:160,focus:352});
  return Object.freeze({shared:160,focus:384});
}'''
    ),
    (
'''  const surfaceAuthority=sharedSurfaceAuthority(job),focusAuthority=null;
  const mixSample=(ux,vz,coarseSample=null)=>{
    const east=(ux-.5)*spanEast,north=(.5-vz)*spanNorth,coarse=coarseSample||surfaceAuthority.sample(east,north);
    if(!focusAuthority)return coarse;
    const refine=localTextureHandoffCoverage(ux,vz,false);
    return refine<=0?coarse:blendSurfaceAuthoritySamples(coarse,focusAuthority.sample(east,north),refine);
  };''',
'''  // Only the 1x focus layer may consume the bounded fine authority. Medium
  // and outer coverage remain on the shared parent so their larger physical
  // spans never clamp or stretch the child raster. The focus patch itself is
  // three viewport heights wide and edge-feathered inside that spare coverage,
  // so every viewport-relevant focus pixel is backed by the finer canonical
  // source before the child becomes the visible owner.
  const surfaceAuthority=sharedSurfaceAuthority(job),focusAuthority=contextRing?null:focusSurfaceAuthority(job);
  const mixSample=(ux,vz,coarseSample=null)=>{
    const east=(ux-.5)*spanEast,north=(.5-vz)*spanNorth,coarse=coarseSample||surfaceAuthority.sample(east,north);
    if(!focusAuthority)return coarse;
    const refine=localTextureHandoffCoverage(ux,vz,false);
    return refine<=0?coarse:blendSurfaceAuthoritySamples(coarse,focusAuthority.sample(east,north),refine);
  };'''
    ),
    (
'''      const parentSample=surfaceAuthority.sample(east,north),sample=mixSample(ux,vz,parentSample);
      const sourceColor=Array.isArray(parentSample?.color)?parentSample.color:(parentSample?.land?[.28,.46,.20]:[.06,.22,.42]);''',
'''      const parentSample=surfaceAuthority.sample(east,north),sample=mixSample(ux,vz,parentSample);
      const sourceSample=sample||parentSample;
      const sourceColor=Array.isArray(sourceSample?.color)?sourceSample.color:(sourceSample?.land?[.28,.46,.20]:[.06,.22,.42]);'''
    ),
    (
'''      const elevationBase=Number(parentSample?.elevationMeters||0),moistureBase=clamp(Number(parentSample?.moisture||.5),0,1);
      const mountainIdentity=clamp(Number(parentSample?.mountainInfluence||0),0,1);''',
'''      const elevationBase=Number(sourceSample?.elevationMeters||0),moistureBase=clamp(Number(sourceSample?.moisture||.5),0,1);
      const mountainIdentity=clamp(Number(sourceSample?.mountainInfluence||0),0,1);'''
    ),
    (
'''      const worldEast=parentSample.registeredEastMeters,worldNorth=parentSample.registeredNorthMeters;''',
'''      const worldEast=sourceSample.registeredEastMeters,worldNorth=sourceSample.registeredNorthMeters;'''
    ),
    (
'''      topographicSignalRevision:"canonical-continuous-cross-lod-source-v37",topographicSignalAuthority:"PlanetGeography elevation/color/moisture stays on the bounded 64→144 focus / 80→160 shared raster ladder; the uploaded focus texture itself refines from 160 to 448 pixels and adds only physically resolvable Campaign-SEED registered-meter terrain and land-cover frequencies per output texel.",sharedAuthorityRasterSize,focusAuthorityRasterSize,sharedAuthorityMetersPerSample:sharedAuthorityMetersPerSample===null?null:Number(sharedAuthorityMetersPerSample.toFixed(3)),focusAuthorityMetersPerSample:focusAuthorityMetersPerSample===null?null:Number(focusAuthorityMetersPerSample.toFixed(3)),sharedAuthorityReusedAcrossRings:true,focusAuthorityEdgeMatched:true,''',
'''      topographicSignalRevision:"canonical-continuous-cross-lod-source-v38",topographicSignalAuthority:"PlanetGeography elevation/color/moisture uses the bounded 192→384 canonical focus raster for the 1x child and the 80→160 shared raster only for 3x/12x context; uploaded focus textures refine from 320 to 512 pixels while registered-meter residual frequencies add only when physically resolvable.",sharedAuthorityRasterSize,focusAuthorityRasterSize,sharedAuthorityMetersPerSample:sharedAuthorityMetersPerSample===null?null:Number(sharedAuthorityMetersPerSample.toFixed(3)),focusAuthorityMetersPerSample:focusAuthorityMetersPerSample===null?null:Number(focusAuthorityMetersPerSample.toFixed(3)),sharedAuthorityReusedAcrossRings:true,focusAuthorityEdgeMatched:true,focusAuthorityApplied:true,'''
    ),
]

for old, new in replacements:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"Expected exactly one patch anchor, found {count}: {old[:120]!r}")
    text = text.replace(old, new, 1)

if "focusAuthority=null" in text:
    raise SystemExit("focusAuthority=null remains after patch")
if "focusAuthority=contextRing?null:focusSurfaceAuthority(job)" not in text:
    raise SystemExit("focus authority activation missing")
if "focusAuthorityApplied:true" not in text:
    raise SystemExit("focus authority telemetry missing")

PATH.write_text(text, encoding="utf-8")
print("Applied WP-S003-010-003-005-002 Attempt 3 canonical focus source refinement")
# Harness revision 2: source patch unchanged; rerun after removing invalid npm step.
